### ISSUE TITLE
Warhammer World exclusive - Campaign Supplement Blood Oath

### ISSUE THREAD

**Issue by senpai514** [BSData/wh40k-7th-edition#1014]
Got some new formations for a few armies. I'll get the 3 formations for my 2 armies and the datasheet images can be found at:
http://www.bolterandchainsword.com/topic/307722-warhammer-world-exclusive-campaign-blood-oath/

Codex Space Marines - SENPAI514
- [ ] Ultramarines 1st Company
- [ ] The Spear of Sicarius

Codex Imperial Knights - SENPAI514
- [x] Anvil of the Emperor

Codex Grey Knights - @amis92
- [x] Grey Knights Emperors Hand Strike Force

Codex Khorne Daemonkin
- [x] The Bloodied Horde
- [x] The Fist of Khorne
- [x] The Goreguard
- [x]  Hellforged Hunting Pack

**Comment by NebSeele** [comment]
I will be tackling the daemonkin items sometime this afternoon (I have some time available for the first time in a couple of weeks).

Edit: On a note for the Daemonic engines/units from FW. Until a copy of the dataslates are made known as to how these units work inside the Khorne Daemonkin, I am making a few assumptions based on how the rules of Khorne Daemonkin work when it comes to reworking them from CSM and Daemons respectively. 

May or may not be wrong but as FW has not released an official statement  it's all I can do.

**Comment by cartag** [comment]
Add the BftBG to the FW models (since literally everything in the book has it)
Make the Khorne dedication worked into the points for the Decimator (the fluff in IA:13 says the Khornate ones have dual siege claws with flamers)
Remove Daemonic Instability from An'ggrath, add SftST
Change Blood Slaughterer to have just a checkbox for Impaler instead of checkbox and number counter for CCW

Sound good?

**Comment by NebSeele** [comment]
more or less around what I was thinking, though the engines have Daemon of Khorne over flat Daemon, however as the hunting pack confers it I doubt it'll be much of an issue anyways. Blood and Skulls I haven't done yet, and I am not sure that they'll get it (if Samus is any indication). An'ggrath does have Fearless over Instability.

Edit: I will add Bftbg and Skulls after all, otherwise it makes no sense for certain selections in the formations.

**Comment by cartag** [comment]
@NebSeele: There's been a clearer image leaked of the Goreguard formation, it's 8 bloodthirsters, not 3.

**Comment by senpai514** [comment]
@amis I hope you don't mind if I close this I have the 2 Ultramarines formations added to the list of codex updates so don't really need this one as well to track the updates twice.
