### ISSUE TITLE
Khorne Daemonkin

### ISSUE THREAD

**Issue by Critacal** [BSData/wh40k-7th-edition#1023]
Missile launchers has no profile

Close combat weapons show up with powerfist profile for champions

Samus has blank toughness value

Daemon Prince has missing gifts of Khorne options Collar of Khorne, combat familiar, and Ichor Blood
(Already has Aura of Dark Glory, has the option for Daemonic Flight, and technically can take a Juggernaut as there is no restriction in the codex just like Chaos Lord in Termie armour can take it)

and thank you in advance for fixing these.

**Comment by Critacal** [comment]
Just remembered Havoc Launcher profile is blank too

**Comment by NebSeele** [comment]
I will get to fixing most of these later when I can, although in the prince taking a herald case, I don't see how a mc can take/become cavalry. I've always believed it was against the rules of the game

**Comment by cartag** [comment]
Daemon Prince cannot take a Juggy, it says "Juggernaut of  Khorne - Chaos Lord and Herald only.  Not available to a model wearing Terminator armour." 

Aura of Dark Glory is specified as Chaos Lord only in the same section. 

Changed the formatting slightly to make it more readable here.

**Comment by NebSeele** [comment]
The CC and Samus bugs are addressed now, and thought that the DP couldn't take the juggernaut. I have also added the missing Gifts of Khorne to the DP profile.

Havoc Launcher is blank on which model? because the shared launcher is not blank, which means something's gone wrong elsewhere. <i>Edit: Found the Defiler being the culprit</i>
