### ISSUE TITLE
Khorne Daemonkin - formation bugs

### ISSUE THREAD

**Issue by cartag** [BSData/wh40k-7th-edition#1024]
Hellforged Hunting Pack
Blood Slaughterer should be set to either single model, or taking one selection with three Slaughterers in it should count for three choices rather than one. 

Fist of Khorne
Kharybdis Assault Claw should be included by default

**Comment by NebSeele** [comment]
The lack of (a full copy of) Blood Oath to clarify what is and isn't legal really does hurt the FW models, because the Blood Slaughterers in IA:13 are a unit of 1-3. Granted I have taken liberties already with the FW items, especially daemonic but still... <b><i>(Edit: Re-read the wording, I'll fix it specificially for the formation)</i></b>

As for the Kharybdis: I'll duplicate the profile specifically for the formation, it's a battlescribe issue (doesn't auto rollover for modifiers as it does for the fixed numbers).

**Comment by NebSeele** [comment]
Fixed in a recent commit, closing
