### ISSUE TITLE
Adeptus Mechanicus War Convocation

### ISSUE THREAD

**Issue by Flashpoint-** [BSData/wh40k-7th-edition#1047]
Do you guys have the rules to this formation?
I can supply them if you need them.

**Comment by Toreador13** [comment]
I actually had mis-understood what the previous bug poster had posted, but I think the biggest issue we have now, is how to implement it. I was thinking about this last night. The Congregation is missing because it is a formation composed of 3 different datafiles, and whichever files want to contain the formation will have to have all options for all units available in the formation. Not sure there is an easy way to do it. Anyone have ideas other than making a copy of everything and putting it in each data file?

**Comment by senpai514** [comment]
Check terminology as well when referring to items please for correctness.
The battle congregation is the CultMechanicus detachment name. The adeptus
mechanicus war convocation is the 3 codex formation.

**Comment by Toreador13** [comment]
Pulled down the data file and it looks to me like there are no formations in the Cult Mechanicus data file right now. 

At work right now so my connections as well as resources are limited. 

The adeptus mechanicus war convocation will be problematic. That is what we will need ideas on. 

Also, the Cohort Mechanicus is the web exclusive formation that we need to get a hold of?

**Comment by senpai514** [comment]
Actually I recently had a thought that might work for multi-codex
formations. I'll post it up a lil later on when I have the time.

**Comment by Flashpoint-** [comment]
Sorry for the confusion.
Cult Mechanicus Battle Congregation 
Is a detachment. Not a formation.
Do you need the rules to it?

**Comment by Flashpoint-** [comment]
Rules: Detachment

Cult Mechanicus Battle Congregation 

Compulsory
1 HQ
2 Troops

Optional
6 Troops
4 Elites
2 Heavy Support

1 Fortification

Restrictions
All units in this Detachment must have the Cut Mechanicus Faction (or have no Faction)

Command Benefits
Tech-Adept: if this Detachment is your Primary Detachment, you can re-roll the result when rolling on the Warlord Traits table in Codex: Cult Mechanicus.

**Comment by senpai514** [comment]
all data for cult mechanicus is already done the remaining items are just
pending release

**Comment by Flashpoint-** [comment]
Cool, do you know the release date ?

**Comment by Throtard** [comment]
senpai514, I would love to know your ideas about the multcodex formation, I was trying to figure how to make it but didn't come anything to my mind.

**Comment by amis92** [comment]
Hey, how do that bunch of codexes look in terms of Factions? Are they declared as different factions?

**Comment by senpai514** [comment]
Yes

**Comment by amis92** [comment]
Damn. 

Pozdrawiam,
Amadeusz Sadowski

wysłane z Lumii 820

-----Original Message-----

**Comment by Throtard** [comment]
I tried that:
![example](https://cloud.githubusercontent.com/assets/12465591/8020041/27419652-0c6b-11e5-9e7b-4c9b2d9a2f84.png)
And it works (more or less). You have to add the detachments separately from a selection. Hope this can be useful.

**Comment by senpai514** [comment]
Ok so here goes; I think the easiest way to make this formation possible in BS is by creating the formation entry in each affected catalogue using that catalogues portion of the formation so for example in the Skitarii we will have the entry labeled: Adeptus Mechanicus War Convocation (Skitarii portion) and then configure the entries along inline with the Battle Maniple detachment force org. Yeah we would kind of be forced to duplicate the entries again but all 3 of the affected catalogues are quite small so its not really as much as any other full codices. Also what would need to be done is all entries and such that are links in the catalogues would need to be replaced with a copy of the options themselves so that way the points cost for wargear and weapon options can be set to 0. Also the Special Rule Canticles can be added to all Skitarii units and profiles with Gets Hot can be removed.  The same can then be done to Cult Mechanicus and Imperial Knights.

I am hoping that if we label the Formation entries:

 Adeptus Mechanicus War Convocation (Cult Mechanicus portion)
 Adeptus Mechanicus War Convocation (Skitarii portion)
 Adeptus Mechanicus War Convocation (Imperial Knights portion)

that when folks go into one catalogue and see its just that part they will look for the other 2 parts as well in the respective catalogues.

So what do you think @amis92

**Comment by amis92** [comment]
Ugh. Pure evil, I say. :D
I have honestly no idea how to make it better, tough. An alternative earlier proposed (I think?) was to create completely separate catalogue, which is not _that_ stupid, considering we need to copy all those things anyway.

So to straight things up for me (I don't have paper, so): the convocation is a Formation (not a detachment?). All units which are part of it can take any upgrades for free. It consists of three other formations, which have their respective factions required. Anything more?

**Comment by amis92** [comment]
I'm not sure though if @Throtard 's version isn't cleaner?

**Comment by Throtard** [comment]
@amis92 To clear things (as you say) the "Ad.Mech. War Convocation" is a Formation which is composed of 3 detachments, one per codex, that retain their own faction. Free upgrades and Cult Mech. special rule (canticles) for everyone.
The problem with my previous idea is that you can choose the units correctly, but I don't see how I can override the cost of upgrades.
I really think that the separate catalogue would be the lesser evil.

**Comment by Throtard** [comment]
To worsen the subject a little more, the web exclusive has the same problem: Formation with Cult Mech. and Skitarii factions (I suppose, considering the bundle).

**Comment by amis92** [comment]
jeez. Do they hate us so much?

**Comment by Throtard** [comment]
Adeptus Mechanicus War Convocation
FORMATION:
• 1 Cult Mechanicus Battle Congregation Detachment (see Codex: Cult Mechanicus)
• 1 Skitarii Battle Maniple (see Codex: Skitarii)
• 1 Imperial Knight Oathsworn Detachment (see Codex: Imperial Knights)

I really have to understand what I read xD. 2 detachments and 1 Formation.

**Comment by amis92** [comment]
;(

**Comment by Toreador13** [comment]
I would bet more of these are going to come along. 

IMO the best way would be to do each piece in its own data file. If we start making more data rifles and they put out more of these it will just get messier and messier.  If we keep all contained in the data file that is its master, we also keep it easier to maintain those files. Maybe put a note in each about what else you have to do for the full formation. It's going to be a lot of work for one formation. Does the exclusive one also give free upgrades?

**Comment by Throtard** [comment]
Who knows, but i can see in the thumbnail a lot of text. Until it leaks, we can't take anything for sure.

**Comment by amis92** [comment]
Well, I agree with @Toreador13. Let's put it all in existing files. Make appropriate formation/detachments nested in the Convocation Formation force type (new one, as @Throtard shown) and just copy/paste'em units like @senpai514  said.

Whoever has time...? ;)

**Comment by Throtard** [comment]
I just uploaded some changes. It should be like this.
![screenshot 2](https://cloud.githubusercontent.com/assets/12465591/8037737/e7b89abc-0dff-11e5-9a64-028de268ecb6.jpg)
![screenshot 1](https://cloud.githubusercontent.com/assets/12465591/8037736/e7b5783c-0dff-11e5-8701-3841746822ad.jpg)
Duplicated units are always visible, I hope it wouldn't be too confusing. I din't modify Skitarii and Knights yet.
Opinions are welcome.

**Comment by amis92** [comment]
I'd swap 'portion' for 'part', other than that - seems best we could think of.

**Comment by Throtard** [comment]
Well, it's finished. I close the issue.
