### ISSUE TITLE
Old SM codex issue not fixed

### ISSUE THREAD

**Issue by Elorm123** [BSData/wh40k-7th-edition#1071]
Issue #1068 https://github.com/BSData/wh40k/issues/1068 is marked as closed, but it is still bugged, I re-added the repositories to make sure, but it is still asking for the weird troops requirements on Space Marines.

**Comment by Stribbs** [comment]
I think @senpai514 is working on Space Marines' new Codex and bringing the catalogue in line.
I'd believe that's why there's odd errors.

**Comment by senpai514** [comment]
@Elorm123 I reverted the last change that had been done to the 6th edition Space Marine file. you should be back to V118 for that file. Since the codex revision number is less you may need to delete the current data files and re download to work proper and as @Stribbs  mentioned I am working on the 7th Edition version of the codex. it is a entirely new file that I should have ready soon.

**Comment by Elorm123** [comment]
I had to fully delete battlescribe and purge every last file of it from my pc and then reinstall it, but it finally reverted back to 118, thank you for the help and the work you are doing!

**Comment by amis92** [comment]
@senpai514 when you do something like that (reverting), you should also increase revision to overwrite what people downloaded, so _that_ doesn't happen again.

**Comment by senpai514** [comment]
@amis92 got it. Sorry
