### ISSUE TITLE
Space Marines - Codex (2015) v2 crashes/locks BattleScribe

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1119]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Battlescribe crashes when trying to add any unit or formation since last codex update

**Comment by NiklasLeide** [comment]
It does not crash to homescreen but it locks up.

**Comment by LurkinLarkin** [comment]
I have the same problem

**Comment by pretzalcohuatl** [comment]
Not our fault

**Comment by amis92** [comment]
Are we sure it is not our fault?

**Comment by pretzalcohuatl** [comment]
Given that it's Apple only, yeah.

e: Tested working on PC and Android

**Comment by NiklasLeide** [comment]
But it worked fine before the v2. Might be something in the Codex that trigger a crash only on iOS.

**Comment by pretzalcohuatl** [comment]
Obviously it's something with the catalogue, but given that it works on other platforms, it's probably on the app's end

**Comment by amis92** [comment]
@NiklasLeide could you please report that issue (as it's probably BattleScribe's fault) on UserVoice for BattleScribe? http://battlescribe.uservoice.com/forums/55066-general

**Comment by amis92** [comment]
Hm. Last time I remember something like that crashed BS was that a shared entry had a category assigned. Could've happened during copy-paste. Would someone check and report if the thesis is correct? Fixing will involve manually editing xml and changing shared entry's category to "(No category)" or whatever is that in xml.

**Comment by pretzalcohuatl** [comment]
yeah i'l take a look

**Comment by whiskeyjuvenile** [comment]
at least crusader squad... still looking

**Comment by pretzalcohuatl** [comment]
reopen in case this fixes it in next release

**Comment by pretzalcohuatl** [comment]
no luck so far

http://www.dakkadakka.com/dakkaforum/posts/list/300/617215.page#7930254

**Comment by NiklasLeide** [comment]
@amis92 Posted on uservoice!

**Comment by pretzalcohuatl** [comment]
Closed now that we're on v4

**Comment by amis92** [comment]
@NiklasLeide give us a link, I'll vote for it.

**Comment by NiklasLeide** [comment]
@amis92  http://battlescribe.uservoice.com/forums/55066-general/suggestions/8545201-chrash-on-ios

**Comment by pretzalcohuatl** [comment]
#1152

**Comment by Jonskichov** [comment]
Hey guys, just wanted to let you know what in the data is actually causing the crash:

Battle Demi Company (ID: 165d-32c9-8555-5e1c, Category ID: bf93-7277-bf48-16f7) (that's the "Core" category).

The crash is a null pointer error when you have a combined arms detachment in your roster (or any force without the Core category in it). BattleScribe is trying to get the parent Core category when validating the demi company, and of course not finding it since the CAD doesn't have one...

Why is this is only happening on iOS? No idea. It shouldn't be any different to Android or desktop. Probably something to do with the tooling I'm using when moving code to iOS.
