### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by doczaius** [BSData/wh40k-7th-edition#1244]
I love your product and it seems really good and maybe I  am technologically challenged but I can't seem to get codex craft world to work. I see all the formations but there are no options for taking engines of vaul or Rangers. You can have 1 to 12 of these other formations once you take a primary detachment.  I just can't seem to locate these options? Am I missing something?..

**Comment by amis92** [comment]
These are not formations for primary detachment. That is another Eldar specific detachment type (can't remember it's name), and there they are Auxiliary choices.

**Comment by doczaius** [comment]
Why is issue closed? I still can't design an army on the product I paid for at app store. How do I get full list? Where are theas auxiliary choices ? What files need to be downloaded ?

**Comment by senpai514** [comment]
What force type did you choose when selecting the army codex to begin
building?

**Comment by doczaius** [comment]
I select craft world eldar and select formations the program has all the gaurdian host selections and aspect host wraith and lords of war etc. There  is engines of vault or plain wraith constructs. Phoenix lords missing too. If I combine with another list for eldar it doesn't work. Sorry to be problem just want what I bought to work or ditch it i guess

**Comment by senpai514** [comment]
If you select formation detachment then you are only building a list using
the bad formations as they standalone. You need to change the force type
from formation detachment to the name of the detachment type listed in the
Craftworlds codex.

**Comment by amis92** [comment]
Ok, there is a misunderstanding here. @doczaius, the help you received from **senpai514** is his good will. You should not argument your issue with "I paid for the app". Because that is exactly what you did: you paid for BattleScribe. Data files on the other hand are created by our group of free-willed contributors, who sacrifice their time voluntarily developing the datafiles you have the problem with. We do not have any gain nor profit out of you buying the app.

Please remember the difference next time. Happy list building.

**Comment by amis92** [comment]
And per you issue, @doczaius: since some time, we have new Detachment types. There is the 'standard' Combined-Arms Detachment, Formation Detachment, Allied Detachment. Then we have Codex-specific detachment types, like Great Wolves detachment and so on. What you seek is a 'Cratfworld Warhost' Detachment, which you have to select as Force Type, and with it select Codex Craftworlds to get what you want: There are then three categories, 'Core', 'Auxiliary' and 'Command' - from there you should know what to do, if you have the Codex.

Cheers.
