### ISSUE TITLE
Dark Angels - Codex (2015), assault marine stats always register as having Jump Packs

### ISSUE THREAD

**Issue by Itsacon** [BSData/wh40k-7th-edition#1262]
Currently, regardless of the selection you make, the stat line for assault marines and assault marine sergeants always lists them as having (Jump Packs). 

I've tried to fix this, and fixed bug #1261 (Infantry/Jump Infantry switch), but I can't see where the wargear text is coming from. 

Related: The way of implementing jump packs as used in the Space Marine datafile (a seperate checkbox) is cleaner than how it's currently done in the Dark Angel datafile (option under dedicated transports).

**Comment by Thairne** [comment]
I disagree. Since you can trade the Jump Packs for a ded. Transport, they basically are the same thing - an option that is exclusive to the others. That way you save yourself the trouble of all the modifiers and conditions (especially with 10 man squads, bulky and whatnot)
I have NO idea where the Jump Pack comes from too.. Neither a link, nor in the profile or anywhere else... it's weird. It does list the correct profile, so the hide/show modifiers work.
Might be a very minor BS Bug.

**Comment by senpai514** [comment]
Technically your not trading the jump packs for a transport like you did in the last edition of the codex since you don't have the jump packs to start with any more. All that would be required is just a simple modifier setting max selection to zero for dedicated transports if jump packs are selected.

Sent from Windows Mail

**Comment by Itsacon** [comment]
As Senpai said, in the new codex, the jump packs are bought as a per-model upgrade, while the transports are a per-unit upgrade. Similar to, for example, camo cloaks for scouts.

With the scouts (and the identical Assault Squad in the Vanilla SM file), this is done with a checkbox. I feel that this is a nicer way of doing this.

As for the Jump Pack text, I actually did a local branch and completely rebuild the Assault Squad entry from scratch, and the bug still returned. I might see if changing the Jump Packs over to the SM style (checkbox) solves the issue, seeing how the SM file doesn't have this problem.

**Comment by amis92** [comment]
I think this is closed, technically.
