### ISSUE TITLE
Dark Angels Tac/Dev Sarges weapon options

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#128]
Merged from #99, #100

Seems like we need to rebuild the choices, as Anon correctly pointed out we can't take combos like Boltgun/Thunder Hammer.

So, what I can read is, we either:
- take default boltgun and bolt pistol _OR_
- take boltgun and **CHANGE** _bolt pistol_ for one of **Melee Weapons** _OR_
- change _boltgun_ for **Melee Weapon** **AND** change _bolt pistol_ for **Ranged Weapon**

Am I correct?

**Comment by axisofentropy** [comment]
I can handle this.  It's been on my list too. I'll figure something out with the codex.

Note that this will probably invalidate existing rosters, is that much of a concern?

**Comment by amis92** [comment]
I don't think it should, as I don't see any way to fix it without invalidating them. And we need to fix things, not care of old rosters ;D

**Comment by axisofentropy** [comment]
I don't think Battlescribe can implement this perfectly.  For now, I've replaced Techmarine, Devestator, Scout, and Tactical Sergeant wargear with links to Shared Entry Groups for Melee and Ranged Weapons.  Bolt pistols and Boltguns appear in both lists for flexibility.

Unfortunately this allows some combinations that appear illegal, like two bolt pistols, and I don't see a way to set a condition on selections from a neighbouring Shared Entry Group.  Maybe that's not such a big issue since gunslinging is well-known not allowed on Sergeants? Is it better to allow legal combinations than to prevent illegal edge cases?  (The other illegal combinations are not desirable.)

And we may need different lists for other units with different defaults, like Assault Squads, Ravenwing, and Librarians.

Pull request #144

**Comment by amis92** [comment]
Thank you for this commit.

It _is_ better to allow illegal combinations than disallow legal ones.

If you think of something better, you know what to do :)

In the meantime, it's the best we could possibly do.
