### ISSUE TITLE
Codex: Orks - Boyz with Rokkit/Big Shoota too cheap.

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#130]
In the Codex you can upgrade your Boyz to a Shoota-unit.
This costs 1 point per model. That's 1 point per model regardless if they actually change their weapon or not.
This would mean that a Rokkit Boy in a Shoota-unit would be 6 + 1 + 5 = 12 points.
At the moment they are only 11 points.

I would fix this by making 'Shoota' a collective upgrade and then have a Special Weapon-option for 5 instead of the "Boy with Special Weapon"-option.

Thoughts?

**Comment by ghost** [comment]
I think you're reading too much into it; the "entire mob" bit is just there to stop you mixing Sluggas and Shootas together.
It was established before that upgrades can be applied in any order, so you select the special weapons first, then give the remaining guys Shootas for 1pt each. Expanding on your method, the Boss Nob would also have to pay that extra pt for any Ranged Weapon he takes... No, the pt is because the individual weapon is better, not because the unit becomes a different unit overall.

I did seriously consider using a collective radio button for the Shootas/Sluggas and fiddled about with a couple of different layouts, but it's important to keep a consistent style within a catalogue, to avoid confusing people. The DA file uses collective weapons everywhere; I like having the weapon tied to the model (it means using fewer modifiers). In the end though, it's personal preference, whichever way you do it.

**Comment by Kangodo** [comment]
You might be right, we can just close this issue for now.

I personally play a lot around on my phone and I don't really like the current method.
At the moment I have to click way too often just to take 10 Shoota-boyz.
Luckily I only play BA/Necrons and most of my work goes in their catalogues ;)
Isn't there a thread where developers can discuss how they make options/etc? Seems weird to talk about it in issues.
