### ISSUE TITLE
Enhancements: Include faction name in detachments / formations

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#1324]
You should Include the faction's name at the beginning of each detachment's name  in the "New Roster Forces" menu

ex:

40k General - Combined Arms Detachment
40k General - Allied Detachment
40k Formations
40k Unbound
40k Orks - Great Waagh! 
40k Orks - Ork Horde
40k Grey Knights - Nemesis strike Force 
40k Multiple Factions - Cohort Mechanicus
40k Fortifications  
...

in the same way as those:

Planetstrike - Attacker
Planetstrike - Defender
Apocalypse - Formations
...

And put General, Formations and Fortifications categories first if possible beacause they are the most common ones.

Not a big thing but I think it would be quite easier to the eye and easier to search in the list. (listed by faction, in alphabetical order would even be better)

**Comment by Thairne** [comment]
I like this idea.
However, there is one problem - we cannot sort the entrys, at least afaik.
I tried naming every detachment, and while the game catalogue editor sorts it alphabetically, the roster editor doesn't. He seems to sort by some internal ID... The entrys are sorted by order of being created.
So while we currently could add the faction (40k is a useless prefix though since there is nothing else in the 40k game file), there won't be any sorting.
Unless anyone knows how to sort it?

**Comment by pretzalcohuatl** [comment]
I believe that I've read that the next version of Battlescribe will address this issue in some way.

**Comment by afraeve** [comment]
A quick cut & paste in an xml editor is all it would need. It'd need a sensible naming convention. I chucked this together just to give a rough idea what to expect - it looks scruffy & unprofessional with those abbreviations, though.

![list](https://cloud.githubusercontent.com/assets/13020665/9021057/7233965a-3827-11e5-9ff5-0d9b008c2da7.jpg)

**Comment by amis92** [comment]
@Thairne yes indeed it's probably sorted by the ID, and @whiskeyjuvenile yep, it's heavily under development as per Twitter progress updates: https://twitter.com/BattleScribe

**Comment by amis92** [comment]
Oh, I closed because it'll get sorted out when new BattleScribe hits.
