### ISSUE TITLE
Black Legion VotLW bug

### ISSUE THREAD

**Issue by evilflow** [BSData/wh40k-7th-edition#134]
I got following warning: "All Chaos Space Mariness(sic!) must have the same number of Veteran(sic!) of the long war". I do not understand the meaning of this fact as all Black Legion CSM automatically get VotLW (and they get it in the correct amount).

![1](https://cloud.githubusercontent.com/assets/8115021/3526079/070c1e4a-0779-11e4-8404-8e6b29e3a251.png)

**Comment by amis92** [comment]
It seems in latest BS version it's not happening. Closing.

**Comment by evilflow** [comment]
It is not true, the issue is still present in version 1.14.06b. Please see
the roster file I attached and reopen the issue.​

Edited:
Oh, I see that attaching file via e-mail does not work. How to attach my roster file to this post?

**Comment by amis92** [comment]
It's undoable. Please just write in plain text what choices to take to recreate the bug. That, or give a link to some Dropbox/OneDrive file.

**Comment by Kangodo** [comment]
I've replicated this bug.
It happens when you have an army with both normal Chaos Marines (without Veteran of the Long war) and the Black Legion Chaos Marines (with Veteran of the Long War).

If you click on the error, it automatically selects the unit with the issue.
It's not the Black Legion-squad that is causing the error, but the regular CSM-squad.

The Black Legion has the upgrade as 'collective'.
Chaos Space Marines in both codices have the exact same unique-ID.
I think that is causing the issue, that the Black Legion-squad is "forcing" the regular CSM to also have the upgrade.

**Comment by evilflow** [comment]
Yes, that was my case: CSM (primary) + Black Legion (allies).

2014-08-26 14:40 GMT+02:00 Tim Sijben notifications@github.com:

**Comment by amis92** [comment]
Thank you @Kangodo for finding the issue. I have now removed the "collective" flag as it served no purpose except creating this bug.
@evilflow  in a few hours the release will include these fixes.
