### ISSUE TITLE
Csm codex unit selection and option issues

### ISSUE THREAD

**Issue by pruneface** [BSData/wh40k-7th-edition#1359]
In chaos cultists and chaos chosen the champion isnt counting as park of the unit size (they should) and when special or heavy weapons are taken as part of the unit its adding a model to the unit when it shouldnt as its also adding extra points if a mark is taken for each weapon selection  also showing up errors when two heavy weapons are selected in a squad of cultists containing more than 20 (error says you can only have 2 heavy weapons if you have equal to 20 models)
Also theres an error with chaos terminators saying you cant have a heavy weapon if you have anything other than 10 total models including the heavy weapon model, 8 terminators and the champion and it allways says 2 heavy weapon terminators is wrong no matter what setup or options you select i believe the termie issue has been there for a while but the others are only from the newest update

**Comment by pruneface** [comment]
Any progress on this? I would attempt to fix it myself but have no idea how to create and edit them

**Comment by NebSeele** [comment]
Hey. At present I have been bogged down with alot of RL matters (moreso than usual) that has prevented me from doing bugfixes. I will try to look over this and other bugs this evening and fix them. The champion bugs are likely an easy fix anyways.

Edit: In regards to the Cultist champion and the Marine champion not counting towards the unit size.... might I ask for a little bit extra information on it? If it's because the unit group entry doesn't display so... it still technically works as intended. I am looking at the terminator entry now.
