### ISSUE TITLE
Bug Report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by Fatno** [BSData/wh40k-7th-edition#1472]
Blood Claws, Grey Hunters Wolf Guard Pack Leader and Lone Wolf. Only one weapon is available.

**Comment by Lunawolve** [comment]
In the codex Blood Claws, Grey Hunters Wolf Guard Pack Leaders and Lone Wolf have a default selection of weapons which can be exchanged for ranged or melee weapons not taken as additional. The datafiles don't show this correctly because of the way the weapons are laid out and will require a fair amount of change to adjust this. I will look into making these changes.

**Comment by Lunawolve** [comment]
I have made some changes to the Grey Hunter Wolf Guard Pack Leader which I think makes this work. I will make a release so you can see the changes and let me know if there is something I missed. Keep in mind that the Grey Hunter WG has a bolt pistol and a chainsword that he can exchange for melee and ranged weapons. I will make changes to the other pack leaders soon in a similar way.

**Comment by Lunawolve** [comment]
A new release has been pushed which should allow all wolf guard pack leaders to exchange bolt pistol and chainsword for melee and/or ranged weapons except for wolf scout pack leader which can only exchange bolt pistol for melee and/or ranged weapon.
