### ISSUE TITLE
Points inconsistent w/ IA v2 2nd edition

### ISSUE THREAD

**Issue by Captain-Joystick** [BSData/wh40k-7th-edition#1542]
Was looking at assembling a chaplain dreadnought and noticed a lot of the weapon costs were zero. The unit breakdown uses terms like 'left arm' and 'right arm' which aren't consistent with the way the unit is broken down in the book (or, on reflection, the layout in the demo pictures either.)

I presume this is due to the transition to 2nd edition, so it probably impacts other entries from that book, right?

**Comment by Thairne** [comment]
The right and left arm thingy primarily is there because we use an Entry Group to select the weapon.
The Entry Group needs a name - you could call it whatever you like - "red bunny" and "blue bunny" if you want.
After all, this is completely irrelevant to the function of the unit and the rules.

While I don't have the rules here right now, I can check on the points cost later. SM Codex however is consistent with my DA Codex.

**Comment by Thairne** [comment]
Totally forgot this one.
