### ISSUE TITLE
Repository corrupted on iOS

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#160]
Says error loading data and error loading catalogue. 7th edition tyranids

**Comment by Kangodo** [comment]
Hmm, did you remove all the files and load them again?
I am not experiencing this on Windows and Android.

#159 has the same issue.

**Comment by ghost** [comment]
May be related to #161 as well, cos all I did to that was add a flyer.

**Comment by Kangodo** [comment]
I created a roster, saved it, closed down Battlescribe and opened the roster.
No issues!

I thought it might have something to do with the BS-Beta, but I have no issues with the regular version.

**Comment by amis92** [comment]
I do not have any problems, too. But I'd leave the issue open, as there seems to be a problem with the files evidently.

**Comment by axisofentropy** [comment]
have we tested the new tyranids with the older version of battlescribe? It could be that some peoples haven't upgrade.

have we tested loading rosters created with the old cataloge?

**Comment by Szaraq** [comment]
I have just installed the newest version of Battlescribe on my iOS and downloaded the most recent repository. After trying to create new tyranid roster, this problem occured. The same situation is with Dark Angels but other armies seem to be ok.

**Comment by axisofentropy** [comment]
Are all of these reports from iOS devices?

**Comment by Szaraq** [comment]
I have just installed the Windows desktop version and it works fine, so it seems, that there is a bug somewhere in iOS (mobile) version. I checked the other armies too and besides Tyranids and DA the error also occured in the case of Space Wolves and Imperial Knights.

I have a dropbox sync turned on if it matters.

**Comment by ghost** [comment]
I don't own any Apples to check this on, but I had a look around for info anyway, since most of these bugs mention it. Seems iOS had an update that's caused a few issues:
http://www.digitaltrends.com/mobile/ios-7-problems/#!bptt1G

Could someone with an iPhone confirm if that sounds relevant?

**Comment by Szaraq** [comment]
Nope. I have v. 6.0 and have this problem.

**Comment by axisofentropy** [comment]
I'm new here, but this seems like A Big Deal. Are the BattleScribe developers aware of this? How would we contact them?

**Comment by amis92** [comment]
Not many ways. @Jonskichov is BattleScribe author. You can also open a ticket on uservoice page (link on BS's homepage), or try contacting him on Facebook/G+/Twitter.

**Comment by amis92** [comment]
Ok I'll close other issues of the same problem, and change title of this issue.

**List**

Known to be corrupted:
- Tyranids
- Dark Angels
- Space Wolves
- Farsight Enclaves
- Imperial Knights

**Summary**
- **First**, it's quite possible all these reports are only from **iOS**, because Desktop and Android have been checked to produce no similar issues.
- **Second**, if anyone has any ideas what these catalogues may have in common, share your ideas.
- **Third**, there comes a list of issues for similar problems:
  - #159,
  - **#162 (java exception stack included)**,
  - #163, #164,
  - #166 (mentions iOS platform),
  - #167 (a comment about how Space Wolves stopped working after last update),
  - #168 (Dark Angels on iPad, stopped after last update),
  - #169 (iPhone 5S, mentions re-release didn't do the trick),
  - #171 (re-downloading fails mentioned, Farsight and Imperial Knights)
  - #172

**Comment by amis92** [comment]
A temporary solution would be to go back to last known working release on master branch, and make the current master a dev branch. That way nothing is lost, and iOS users have something to work with.

It's not trivial tough, so I'll only do it if there will be voices agreeing to do it.

**Comment by ghost** [comment]
I don't think the files have much in common. They're from different devs, and the Imperial Knights cat is pretty simple.

**Comment by axisofentropy** [comment]
I'm not familiar with the repository release process; Could the new .catz files with issues be replaced in the published repository without touching the working ones or the git repo?

**Comment by amis92** [comment]
No, unfortunately not. What we _can_ do is as I said, call current state 'dev' (create a new branch called 'dev'), and rewind master back to working commit, and then release it. However that would mean that we'd have two branches, and anyone who wouldn't know could commit into master, creating huge mess (because it would be a commit creating a _really_ separate branch).

It may be hard to understand. To sum up: everyone would have to be informed to change currently used branch to 'dev'.

**Comment by Jonskichov** [comment]
Hi guys, I'll be looking into this on my end too tomorrow.

Just finally got the beta for .04 out after much gnashing of teeth getting some of the global/shared stuff working as required. Delayed things a little :/

**Comment by Jonskichov** [comment]
@BSData/data-authors 
@BSData/data-admins 

Found the problem!

In 1.14.03 I changed the "page" fields to be text (string) rather than number (integer). I then realised I wanted to do a couple more bits (1.14.04), and considering the turnaround getting updates to iOS, I decided to skip 1.14.03 on there and just roll straight up to 1.14.04. Thus iOS has missed the update to treat the page fields as text.

This means that if a page field in a file now has text in it, it will cause this error when 1.14.02 on iOS tries to load the file.

To compound this, changing the text field page to blank (deleting the field contents) will actually save the page field as a blank string ("") rather than removing the field entirely (setting it null). This means you end up with page="" attributes inside the data file.

Ultimately I overlooked this string/int mismatch and it seems like it's just coming to light.

Whether the page attribute is blank as above, or is some text other than an integer (a round number without decimal places - i.e. the field contains _only_ number characters), it will cause iOS to error loading the file.

This will be fixed in 1.14.04 for iOS, which I'm just finalizing now. I will tick the "expedite approval" box when submitting this to Apple to request they consider this update as urgent and put it through approval faster. There's no guarantee they will agree to do that though, so worst case is about a week wait for approval.

For now:

1) I have replaced the .04 beta (http://files.battlescribe.net/BattleScribe_1.14.04_b04_Multi.zip) to ensure that changing a page field to be blank will set the xml attribute to be null. You might want to use this beta for now. There aren't any more data structure changes in 04 that will affect iOS. (Also, it'd be nice to hear if the min/max in roster/force works as you expect, especially for shared items).

2) Testing with the Tyranids file, I did a find-and-replace in the XML to remove instances of page="" (XML attribute called page with a blank value). This fixed the problem and I could use the file again in 1.14.02 on iOS.

3) If the file still causes the error, you'd have to remove page attributes that had a value other than just numeric/integer.

4) Avoid changing page fields until 1.14.04 comes out on iOS (pain in the ass I know, sorry).

So, good news: The error is in the data, meaning it can be fixed with a bit of hacking so iOS users can get back to using the app. Bad news: It's my error (sorry!) and will be up to a week wait for an iOS version to come out that'll be fixed.

Hope that helps, and makes some sense...

An example in the Tyranids file (https://raw.githubusercontent.com/BSData/wh40k/master/Tyranids%20-%20Codex.cat) is the first entry (Barbed Hierodule). You can see the page attribute causing the problem right at the end of the line.

```
<entry id="ec0f9ad2-131d-f270-4ea6-b92ea3e4c4e0" name="Barbed Hierodule" points="565.0" categoryId="c888f08a-6cea-4a01-8126-d374a9231554" type="model" minSelections="0" maxSelections="-1" minInForce="0" maxInForce="-1" minInRoster="0" maxInRoster="-1" minPoints="0.0" maxPoints="-1.0" collective="false" hidden="false" book="IA4 - 2nd" page="">
```

**Comment by Kangodo** [comment]
That is surely great news! It has been a confusing week for everyone.
(Damn, I was the last to edit the Hierodule.)

**Comment by Jonskichov** [comment]
@Kangodo Haha don't worry, it's my fault not yours. I guess this has been a bit of a "slow burn" issue so it's been hard to pin down what was going on.

Hopefully a quick find/replace as I described will put the data back into a usable state for iOS users. That should be enough to prevent bug reports until 1.14.04 shows up in iTunes.

**Comment by amis92** [comment]
Fixed (removed blank page attributes) using [BSReshaper](https://github.com/amis92/bs-xml-reshaper/releases/latest) with this XSLT:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output omit-xml-declaration="no" encoding="UTF-8" standalone="yes" version="1.0" indent="yes" method="xml"/>

  <!-- The Identity Transformation -->
  <!-- Whenever you match any node or any attribute -->
  <xsl:template match="node()|@*">
    <!-- Copy the current node -->
    <xsl:copy>
      <!-- Including any attributes it has and any child nodes -->
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

  <!-- remove blank page attributes -->
  <xsl:template match="@page[../@page = '']" ></xsl:template>

</xsl:stylesheet>
```

**Comment by Jonskichov** [comment]
Update: Submitted to Apple last night and it's currently under review. Now we play the waiting game...
