### ISSUE TITLE
Space Marines - Special Character Bug

### ISSUE THREAD

**Issue by Samueras** [BSData/wh40k-7th-edition#1618]
All Special Charakter Like Lysander oder Vulcan can't be taken. Nor in the Formations or the CAD

**Comment by Itsacon** [comment]
Have you tried selecting the correct chapter tactics first?

**Comment by Samueras** [comment]
... no thanks for the Tipp, but still doesn't it still is a bug? You should be able to select them no matter what Chapter tactics you choose.

**Comment by senpai514** [comment]
You are in the regular Codex Space Marine file correct? What OS version are you using? Are your files up to date? I tested on my desktop and works as it is supposed to.

I have that catalogue set that the relevant characters/units will appear and become available when the appropriate chapter tactic is selected since you can only have models or units that match your selected chapter tactic for each detachment taken.
