### ISSUE TITLE
AM Emperor's Wrath Artillery Company should include Hydra Battery as an option

### ISSUE THREAD

**Issue by epvanhouten** [BSData/wh40k-7th-edition#1653]
Emperor's Wrath Artillery Company currently only provides Basilisk and Wyvern batteries to fulfill the 2 of requirement. Hydra battery is also a valid choice to fulfill that requirement.

**Comment by amis92** [comment]
@ecrousseau please remember to assign yourself to issues you're fixing too (great you've remembered to mark it as closed in commit message). Also while I'm at it, please take note of release version markings. They all (mostly) contain 'v' prefix, as in 'v4.10.10' instead of simple '4.10.10'. Now that's all, please proceed with your great contributions. :)

**Comment by ecrousseau** [comment]
Ok, will do :)
