### ISSUE TITLE
Ws scar blade

### ISSUE THREAD

**Issue by korsarro** [BSData/wh40k-7th-edition#1705]
When you add a lib conclave you can't add librarians.

There are formations missing from auxiliary. The armoured task force, and strike force ultra are missing.

**Comment by amis92** [comment]
I guess it's invalid, then.

**Comment by korsarro** [comment]
The scarblade formation was moved to the Gladius formation so the error exists but I don't think anyone is working on that now

**Comment by senpai514** [comment]
@korsarro since the supplement catalogues were rolled together into the
main space marine file the issue reported becomes obsolete since the file
you were talking about then doesn't exist any more. If you still see any
problems from where it was combined please create a new issue so it can be
addressed.

Thanks
