### ISSUE TITLE
Add Hide/Show FW option to codex Imperial Knights

### ISSUE THREAD

**Issue by hisop** [BSData/wh40k-7th-edition#1749]
As requested (as a side note) in #1725

**Comment by francoisbeaulieu** [comment]
@hisop @senpai514 

Seeing as thread https://github.com/BSData/wh40k/issues/1725 has a discussion whether or not this fix should be applied, I have another aspect of this to discuss:

Since 7th edition, ForgeWorld seems to be classifying all Imperial titan-type LoWs under the Imperial Knights faction (as is reflected in the IK catalogue). Should said FW units still be available in the C:SM and Astra Militarum catalogues? It doesn't make much sense that the FW units are there, but not the GW Imperial Knights. Do any post-7th IA references discuss these units' factions?

**Comment by ghost** [comment]
No, no IA book has yet covered Knights.

On Mon, Jan 11, 2016 at 7:28 PM, François Beaulieu <notifications@github.com

**Comment by hisop** [comment]
@francoisbeaulieu Knights are a specific type of titan and the reason they (the FW ones) can be taken there is it states in its rules "may be taken as per codex imperial knights or as a LOW in any other imperial army" - or something to that effect. No knight is in IA all of there rules are freely available on forgeworld see below : (officially hosted by FW so no rules breach)
http://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/Cerastus_Knight_Castigator.pdf

**Comment by francoisbeaulieu** [comment]
Good to know! Thanks!
