### ISSUE TITLE
Enhancement Request; Codex: Space Marines - Invulnerable save

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#1761]
Hi @senpai514, all,

In some catalogues, such as Chaos Space Marines, the profile of a model/unit changes to indicate the invulnerable save when an option is chosen that gives it such. (e.g. Selecting terminator armour for a Sorcerer.) It is often indicated by adding the InvSv after the armour save, seperated by a slash. (2+/5++) This is very good information to have on the roster.

I was wondering if it might be considered worthwhile to add this to the C:SM catalogue? 

Thanks,

**Comment by francoisbeaulieu** [comment]
Is anyone working in this?

**Comment by DrTobogganMD** [comment]
I've taken over C:SM since we haven't seen Senpai in a while - I'll work on adding this in but it will be a lower priority fix at the moment.  Currently I'm trying to get AOD content functioning properly.

**Comment by DrTobogganMD** [comment]
Issue is under discussion at the moment.  I'm thinking we should leave profile entries as just what is on the army list entry and keep the additional rules on the wargear entry.  We can't modify profiles via modifier's to link them.  I'll ask Jon if we can add it as a feature though, I'd like that.

**Comment by DrTobogganMD** [comment]
Gah, ignore me - I can modify profiles from other profiles, i'm just blind.  Still a lower priority but This will be next after I finish the relics from AOD.

**Comment by DrTobogganMD** [comment]
After looking further - the amount of overhaul required to do this in the current catalog is not worth it.  I am re-doing the entire catalog to be both smaller in size and streamlined for the 2.0 release.  I will include this functionality for all items that give this (except Gorgon's Chain because that gives varying saves based on wounds taken).

Closing this issue as I am working on 2.0 version in another branch.  The overhaul will be ready by the time 2.0 is released.
