### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by penguin20000** [BSData/wh40k-7th-edition#1767]
Hi guys & gals.

Looking to pitch in and help where i can, currently play Space Marines (who doesn't) and Tau, also dabling with Orks :).

But i try to keep up with most the armies as it pays to know what you're up against.

I've already forked the repo and might put in a pull request in the next day or two :)

**Comment by amis92** [comment]
Great! Pull requests are very good for starters, because we get to see your work and in case something can be more in line with our efforts, give a hint and let you fix it.

So, welcome aboard! Have a look at:
https://github.com/BSData/bsdata/wiki/Developer-Guide
https://github.com/BSData/wh40k/wiki/Catalogue-Keepers
https://gitter.im/BSData/wh40k
