### ISSUE TITLE
Question: Fortification detachment

### ISSUE THREAD

**Issue by francoisbeaulieu** [BSData/wh40k-7th-edition#1797]
As a followup to https://github.com/BSData/wh40k/issues/1689 I was wondering if there is actually such a thing as a "fortification detachment" in the rules? If not, and it's meant simply as a workaround to not have to add all fortifications to each catalogue, then there is an issue: It allows (at least on iOS) to select multiple fortifications without raising an error, but if used with a combined arms detachment, it should limit to one fortification.

**Comment by cartag** [comment]
AFAIK that is why the Fortification Detachment exists. I don't know if it is possible to limit it to one per CAD in the current version of BS.

**Comment by hisop** [comment]
You could do it in a similar way to war convocations. that's a multi codex force in one detachment.

**Comment by efalsken** [comment]
The Fortification Detachment itself is unnecessary. It was a hack for an old Battlescribe bug and our use of the Fortifications catalog. Yes, these days, you should be able to add them to your CAD, but since the Fortifications do not exist in each catalog (with the exception of a few faction-specific fortifications like the Tau Tidewalls) then we still needed to have some place to put them. Unfortunately there's no easy way to share the Fortifications between the Catalogs. Nor is there an easy way to put them in a different Catalog and allow them to still validate as part of a Faction Detachment. We're stuck with the Fortifications in their own Catalog and the Fortification Detachment. But the good news is that the Battlescribe Author (oh holy is is name) is working on a mechanism for us to be able to get around this without too much more trouble. Until then, yes, Fortifications won't be able to validate and people are just going to have to know that and know the basic rules.

Worst case, if you select multiple Fortifications or bring Fortifications with one of the newer Detachments-of-Formations, then the extra Fortifications all end up in an Unbound Detachment (speaking from an RAW standpoint). Someday, probably at about the time GW changes the entire basis of these rules, people will figure it out.

**Comment by hisop** [comment]
I agree, i mean it is possible to do so but the effort would be great, hopefully Battlescribe .16 will resolve this at some point before general release.

**Comment by amis92** [comment]
@hisop I think, per alpha, you can already add units to game system file - and that would be the exact case for Fortifications. :)

**Comment by amis92** [comment]
I think it's answered then.
