### ISSUE TITLE
Move Fortifications INTO CAD etc

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#181]
So it struck me lately that we may enhance the error-proofness of our game system by including ~~Formation~~ _Fortification_ category _into_ the Combined-Arms Detachment.

It would mean that you cannot take a ~~Formation~~ _Fortification_ Detachment, instead you take ~~Formation~~ _Fortification_ directly in CAD. However, because we currently have a single catalogue with fortifications, it would have to be done as a nested force type inside CAD.

Or we just wait until there is that new awesome version of BattleScribe enabling us to move these into gst. (See https://github.com/BSData/bsdata/issues/39)

Well, after a second thought, maybe we better wait.

**Comment by Kangodo** [comment]
My vote goes to waiting too!

**Comment by coruptcopy** [comment]
Sounds brilliant, but if it'll be easier later, then perhaps it is best to
wait. Maybe when we do this, we can combine all the factions too (except
Imperial) so there will just be, for instance, 1 Chaos Space Marines
faction that has all the vanilla, Black Legion, and Crimson Laughter in it.

**Comment by ghost** [comment]
As things stand, you could copy the Formation section into the CAD, but not move it, since a formation can be taken on its own as an ally.

What are the mechanics of nested force types? I'm thinking of when the Orks select the Great Waaagh detachment & get a different set of relics.

**Comment by amis92** [comment]
@khambatta where/how else can it be taken? Looking through 7th edition I see Fortifications included only in CAD. Additionally if I remember correctly it can be taken in Ork detachment. But as an ally?

S for nested mechanics: Each force type, including nested, can choose different catalogue filter for starters. Further on, each force type must include at least one category.

I could tell more, but I don't understand how it could be used for relics for Orks?

**Comment by Kangodo** [comment]
Khambatta speaks of Formations, not Fortifications.
So far each non-Allied Detachment can also take a Fortification. (CAD, Great Waaagh! and Ork Horde)

**Comment by amis92** [comment]
Ah. I see.

But Formation Detachment as per logic contained in 7th ed is a detachment on the same level as CAD etc.

My goal here would be to be with force types as close to detachments as possible. That would mean we'd be nearly perfect in terms of allowing only legal combinations. One thing we cannot assert right now, and probably never will be, is taking Allied Detachment only with Faction other than the one with Primary.

**Comment by axisofentropy** [comment]
Don't nest any other detachments within Combined Arms Detachments.  They're all first-class detachments. If the user experience issue is caused by poor documentation or poor interface, fix that instead.

**Comment by Kangodo** [comment]
I've been thinking some more about this lately.
Especially now that we have the Assassins and the Imperial Knights.
Users want to quickly 'take' that extra Detachment and I think the current way of adding them is quite sluggish.
The weirdest part is that, for an Assassin, I have to go through all possible Detachments even though they can only use one of those. Same goes for Imperial Knights.
Wouldn't there be an easier way to handle these things? Or things like the Inquisition and the Legion of the Damned, it's not like they can use any other Detachment.

If things continue this way with GW, we will be flooded with Detachments and that could make things complicated and bloated.

**Comment by amis92** [comment]
@Kangodo I think that's more to be aimed at @Jonskichov than us devs (cat authors).

I fully agree. We absolutely need a way to stop this bloated flood of Detachments/Force Types for a user experience. And on the account of doing these importing thing, which will bloat number of catalogue files; some kind of control over what is displayed in a Add Force windows is essential.

**Comment by Viper666-Qc** [comment]
Just realised I posted something similar for this topic

---

It's getting pretty crowded in the Force Type as we find every possible detachments from every codice/dataslates/supplements.

Is their any way it could be improved?

I see the Parent Force section is always limited to "Roster". Could we use this for different 40k game system like Standard game, Apocalypse, Zone Mortalis, Planetstrike, Kill team and Spearhead. Using this section could allow to reduce the number of detachments available in the Force Type section.

ex:

Parent Force: Zone Mortalis
Force Type available: Attacker, defender, combattant

Parent Force: Planetstrike
Force Type : attacker, defender

Parent force : Standard Game
Force type: any standard game detachment available (excluding those mentioned above)

Also, could it be possible to choose the Catalogue "before" choosing the Force Type in a way that it would limit the number of detachment available?

ex:
Catalogue: Space Wolves codex
Force Type available: CAD, Space wolves detachment, Company of the Great Wolf, Wolves Unleached, Allied detachment

Catalogue Imperial Knight
Force Type: Imperial Knight Detachment

This last thing would be great because right now, for example, you can select a Inquisitorial Detachment with the Chaos Space Marine codex and once you fill an HQ slot with a CSM HQ, the detachment is valid.....

---

**Comment by amis92** [comment]
@Viper666 see the link in OP.

**Comment by amis92** [comment]
Half a year later and we have more force types than catalogues (or close to that ;) ). If any one has any new ideas, please share... We're in a dire need of improvement.

**Comment by amis92** [comment]
Okay, seeing absolutely no chance of it being in any way changed, I'm closing it here.
