### ISSUE TITLE
Bug, or me being blind: Space Marines formation Armoured Vanguard Squadron

### ISSUE THREAD

**Issue by SilverStrike16** [BSData/wh40k-7th-edition#1814]
Specifically, I've looked through the variations of putting in SM, whether bound, unbound, formation, gladius, apocalypse, what have you. I cannot find a way to put this formation into Battlescribe so that I can give my Rhinos assault vehicle. It's from Warzone Damocles, and a really good formation. Am I being blind, or is it not where it oughta be? I did try looking!

**Comment by efalsken** [comment]
If it's in the old Apocalypse Warzone Damocles book, then the formation should be in the Apocalypse Detachment. It looks like it was never added to the Space Marine catalog.

**Comment by senpai514** [comment]
There is relatively little in the space marine file for apocalyspe formations due to the huge amount of formations and options the datafile itself would end up being too large and cumbersome for mobile platforms.

But yes the formation / ruleset your looking for is an apocalypse formation so not available in a standard 40K army list.(and yes it is an awesome formation)

**Comment by penguin20000** [comment]
This formation is in the Apocalypse Warzone Damocles book, is the consensus to not add it?

**Comment by DrTobogganMD** [comment]
I'd lean on not adding it. GW has FAQed that Apoc formations cannot be used in non apoc games.  If @penguin20000 's 2.0 enhancement about shared datafiles makes it in, we could strip out all apoc things into their own catalog file.

**Comment by DrTobogganMD** [comment]
Closing this issue Consensus to not add apoc formation for now.  Will revisit with 2.0 battlescribe.
