### ISSUE TITLE
Space Marine - Codex (2015) Relics

### ISSUE THREAD

**Issue by Cancleout** [BSData/wh40k-7th-edition#1832]
there is a rule attached to the captain that reduces the number of relics the army can take by 1 every time a relic is equipped.  it makes it error if say a captain takes both a burning blade and a shield eternal.

this rule is attached to each arm (bolt pistol and chainsword) of each armour type for both captain and chapter master

**Comment by cartag** [comment]
If this behaves like the KDK book, you should only be able to take ONE relic per model. It states "A model may replace one weapon with one of the following" implying that only one may be taken per model, not two. In the KDK book it states "A model may take one of the following." I may be wrong on the Space Marines book, but for all of the other new books that I'm aware of, it's a one relic/artefact per model setup.

**Comment by Cancleout** [comment]
In both books it says "Only one of each of the following items may be chosen per army."
pg. 118 in KDK and pg. 198 in C:SM

Which would be only one of each relic, but any number of relics.  
Is there something on another page I am missing?

**Comment by cartag** [comment]
Read the next sentence. It says Only one of each relic/artefact can be taken, then literally the next sentence states a model may only take one of the available choices.

**Comment by Cancleout** [comment]
a model may replace one weapon with one of the following.
pg. 115, i found were you were reading.

first, this is saying you have to have a weapon to replace in order to take one of the relics.

second, the rule i was talking about in the op reduces the army's total relics.

**Comment by hisop** [comment]
The problem here stems from a difference of wording, and some mis-understandings about the use of grammar here i will try and clear it up.

In KDK it states: A model may take ONE of the following.
IN C:SM it states: A model may replace ONE Weapon with ONE of the following:

Admittedly this for C:SM is a little unclear (given the way we use the language some times context is lost), but if we look else where for clarification.

In special issue war-gear it states : A model may take up to one of EACH of the following:
this is not a direct comparison however.

In terminator weapons it states : may replace his STORM BOLTER with one of the following.
Now this is very clear one weapon for one choice.

And again lets look at ranged weapons: A Model may replace his Bolt-gun, bolt pistol and/or his melee weapon with one of the following.
Here its clear gain he has up to three things to give up for one choice so up to three options the trick here is the AND.

The above (using a little grammatical understanding) states one weapon for one choice,  
To mean what you are inferring it would need to say A model may replace EACH Weapon with ONE of the following (or a list).

I hope this helps to clear things up.

**Comment by ddarz** [comment]
Fixed and committed

**Comment by hisop** [comment]
@ddarz this didnt require a fix, it functions exacly as RAW wich is how the data is supposed to be maintained, so bar an FAQ or some further discussion by the seniors here i would say to revert... @amis92 @senpai514 @efalsken  any opinions? @cartag

**Comment by ddarz** [comment]
Apologies, my understanding is that more than one relic are allowed on the same model assuming he can equip it. So teeth of terra in one hand and the shield eternal in the other.
Got the codex right here, it's seems pretty clear - "Only one of each of the following items may be chosen per army" 
I see no mention of a per model restriction (as per some other codices)
So that would be RAW no?
More to the point, the individual entry for a captain says: "...may take items from the ... and/or relic list..."

 Warhammer World Meta seems to agree.

Please let me know and if needed I will revert

Also, the rule was lowering the global limit, not the limit per character. That's what I fixed

**Comment by hisop** [comment]
Ahh i see, sorry for that, the confusion stems from the war gear page, where in the relic section it states:
A model may replace one Weapon with one of the following:

look at my post above for a breakdown of points. in the past we have always aired against going with meta opinion until there is an official word on the matter.

As far as i take the RAW:
Each relic may be taken once per army.
Each character may replace one weapon with one relic.

**Comment by hisop** [comment]
@ddarz look at the gitter discussion https://gitter.im/BSData/wh40k

**Comment by hisop** [comment]
@ddarz When you say global limit what do you mean? it works fine for me "pre-Fix"?

from gitter:

@OftKilted 14:01
Based on the general (conservative) consensus that this is a replacement that only allows (One Weapon) not (Any Weapon) for One item. Until it's FAQ'd go for the more conservative interpretation.

**Comment by ddarz** [comment]
(copied from gitter)
Hey guys, I really don't mean to be difficult,  just want to make 100% sure before reverting the work.

You say that we don't go with the 'meta' for the catalogues, but the (conservative) consencus mentioned baove is just that, a reddit thread which is far from conclusive itself. So I am trying to get to the bottom of this and find the RAW version. Would like to hear more opinions

I have the codex right here, both in print and digital (bear in mind the digital versions have some issues, see Eldar craftwold rangers having jetbikes, heh)
There are 3 points in the codex that concern the use of the relics:
The Entry for character who can take them (captains/masters, chaplains and librarians)
The short Chapter relics list on page 250
The full chapter relics list on page 453

Point 1 supports the case of more than one relic per model  - " ...can take ITEMS from..."
Point 2 has the (not so) ambiguous wording of "switch one weapon for one relic". They way I read it is, switch one weapon for this, and my other weapon for that.
Point 3 makes no reference to swapping, just says that you can take one of each relic per army

From the above, I see nothing in C:SM to restrict taking multiple relics on one character. The BSData guidlines say to be permissive - and that is what I am aiming for. RAW it is supported as per the above points. RAI is that because other codexes don't allow it RAW, neither should C:SM. I can't agree with that.

I would also like to note that I am not debating this for any personal gain as seems to be inferred. I don't personally use relics

Finally and most importantly, the Kauyon and Mont'Ka books  supports taking more than one relic on the same character. So there's that too
Which also lead me to the Tau codex, that also allows multiple signature systems on the same model - explicitly so! (page 75)

**Comment by cartag** [comment]
For Tau it just states "Only one of each Signature System can be taken per army." Full stop, no additional sentences. C:SM states "Only one of each Chapter Relic may be taken per army. A model may replace one weapon with one of the following:"

Reading only one of the sentences is deliberately omitting information to try and make the codex say what you want it to say.

**Comment by ddarz** [comment]
Hi, this has escalated into a large discussion on gitter and we are awaiting more opinions before making a decision.
With regard to Cartag's post above, I have not committed anything, and I apologise for the heat, but I resent the implication. 
I have provided page numbers for each statement and stand by them. One of the referenced entries has the "A model may replace one weapon with one of the following" statement, the other doesn't.
Please do no make accusations on my character.

**Comment by hisop** [comment]
This conversation has been cleaned active and lively discussion is to be kept in the appropriate PRIVATE gitter forum. we are all volunteers separate conversations are not conducive. I am almost certain that this side of the debate was unproductive and further comments here pre- consensus from BS Members not addressing users points will be deleted.  users feel free to contribute...

**Comment by ddarz** [comment]
Clarification and justification added following further discussion
