### ISSUE TITLE
Space Wolves - The Ironwolves

### ISSUE THREAD

**Issue by JusticarGames** [BSData/wh40k-7th-edition#1901]
- Auxiliaries missing.

~~\- Incorrect requirements for Wolf Guard or Wolf Guard Terminators, it should be 0-1.~~
- **Restrictions** You must include enough Dedicated Transports with sufficient Transport Capactity to carry all non-vehicle models from this Formation. \* Currently no warning or error message when non-vehicle models do not have a dedicated transport.

~~\- **Overwhelming Firepower** : All weapons and wargear options taken by Ironwolves vehicles are FREE. \* This is not working. Points are not being deducted.~~

See attached pictures for clarification.
![img_0662](https://cloud.githubusercontent.com/assets/17251427/13206775/2d188df8-d8d3-11e5-835d-19a970ce0ac0.JPG)
![img_0663](https://cloud.githubusercontent.com/assets/17251427/13206776/2d1b180c-d8d3-11e5-9c7b-ff4aa273a1ae.JPG)

**Comment by hisop** [comment]
Will strike through as i work.. the iron wolves "free upgrades" take a long time to fix as you have to manually re make every option been working on it today and will be resolved tonight. black marines are done. the dedicated transport thing is a nightmare as its the first time any such requirement has been needed thus we have no way to do it, i am making one now but just wanted to abridge you, i thought someone else was handling SW but i am going to take over all SW bugs due to the level of work needed.

**Comment by JusticarGames** [comment]
Cool. Thanks for the update!

**Comment by grugknuckle** [comment]
Great work on this so far +hisop. 

~~I noticed that the current (as of 4pm EST 23Feb16) Ironwolves Legendary Great Pack is requiring a minimum of 1 unit of Wolf Guard or WG Terminators. It should be minimum of zero, maximum of 1. I'm putting this here because this bug thread is in regard to the Ironwolves. Would you prefer that I open a separate thread?  ~~

**Comment by hisop** [comment]
Thanks i will fix that now. Here is good, while its still open.

**Comment by hisop** [comment]
Everything raised here is addressed, a decision has been made to defer validation for transports in 1.16 so for the mean time i have added a "please check validation of dedicated transports" "rule" to ironwolves to advise.
