### ISSUE TITLE
Bug report Eldar Craftworlds - Codex (2015).catz: Autarch

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#2054]
File: Eldar Craftworlds - Codex (2015).catz

BattleScribe version: 1.15.07

Platform: Windows

Dropbox: No

Description: Three issues with the Autarch entree
1] Initiative on the statline shows as 8, it should be 6
2] Pistol - choose 1 should not have the (None) option, a pistol is mandatory
3] Weapons - up to 2 and Power Weapon should have yes/no options, not numerical choice. No use taking any of those options twice

**Comment by efalsken** [comment]
Two of the same weapons is still a legal choice, even if useless.

**Comment by Owlsbane** [comment]
Agreed, strictly speaking the wording allows it. But if you look at the way the Codex words it with the Wraithlord and the Wraithknight, they explicitly say "May take up to two of the following in any combination". I think "May take up to two weapons from the following list" is meant to convey picking two different weapons from a list that is limited to one specimen per weapon.

Great work on the revamp of the Codex and FW list btw! Sorry for the deluge of reports, hope you find most of them helpful.

**Comment by efalsken** [comment]
I'll let it stand just because we have to take a "most permissive" stance on things rather than "most restrictive" interpretation, if for no reason other than to prevent bugs from people arguing that they should be able to take the same weapon twice, and since in this case it really doesn't matter, I'm not so worried. Thanks for the bugs! Next time you might want to group them up in a single bug report so I can fix them all at once.

**Comment by Owlsbane** [comment]
Okay, thanks for the explanation, sounds like a reasonable solution.
I wasn't sure grouping stuff like this would make it potentially unclear which issues had been tackled and which hadn't, but next time (hopefully not!) I'll make one report.
Glad I could help, you did amazing work incorporating those Pale Courts!
