### ISSUE TITLE
New Black Legion formations

### ISSUE THREAD

**Issue by Aetherion** [BSData/wh40k-7th-edition#2087]
Update for the Black Legion supplement missing

**Comment by OftKilted** [comment]
New 'Update' for the Black Legion supplement is pending as it was just released and will be updated shortly to the best ability that Battlesribe v1.15 allows. This update is currently being worked on by @cartag and will be released as part of the standard datafile  update process.

Some items may not be available until after the 2.0 release of the Battlescribe tool due to changes and functionality required for managing the new formations and data.

**Comment by Drachnyen** [comment]
Same status for the new Crimson Slaughter supplement I assume?

**Comment by OftKilted** [comment]
The status is the same for the Crimson Slaughter supplement as well.

**Comment by Drachnyen** [comment]
Good stuff !

Thanks in advance @cartag :)

**Comment by cartag** [comment]
The updated book was just put up for preorder today. It won't be updated until the book is actually released. Same goes for Crimson Slaughter. They are going to be added though.

**Comment by Drachnyen** [comment]
FYI: The updated Crimson Slaughter and Black Legion Codex are available right now from the Black Library.   (Digital editions)  

The physical books are arriving later.
