### ISSUE TITLE
Space marine: angels of death [improvement]

### ISSUE THREAD

**Issue by Maglorum** [BSData/wh40k-7th-edition#2105]
Hi, with the angels of death exit, the codex supplements sentinels and clan, are now obsolete.

The new strike forces need to be added to w40k in order to use the codex marine as only source.
And now the "supplements" have the base relics and the main codex relics to chose from, and many new formations and non formations (es. sternhammer can take devastator as aux, but they aren't a formation in the common sense of the word)

It's a big work guys...
I don't know if is better broke the issue in more small "step" issue.

Main changes:
Add new angels of death formations
Add new angels of death strike forces (IF and Salamanders)
Add new relics and chance to choice from core and chapter specific at the same time
Add new "non formations" for specific strike forces

Update old formations as the Skyhammer formation, to be used as aux for specific new strike forces
Update angels of death strike forces (Ravenguard and Clan Raaukan)
Update IF trait, to change the centurions force slot as in sentinels of terra

Remove old bsi for clan raaukan and sentinels of terra (obsolete/redundant)

**Comment by TDog117** [comment]
Yes and no.

In this case, from what I've seen across the net, nothing has been said by GW that any of the supplements are not still usable.

Sure, if you're playing Sentinels of Terra, you can't use the Sternhammer strike force and the perks therein.
But that doesn't stop you from using the formations out of the book as strictly Sentinels of Terra.
Having the segregated supplements has pro and cons, as a great example: the Sternhammer strike force, Dorn's Legacy: if your warlord is alive, all units from the formations are stubborn. 

Now, for most codex marine players, getting locked in combat with your rank and file marines doesn't end well, you want to hopefully lose combat and get away. Now try that without taking penalties to Ld.
As someone who used Pedro and Lysander and found out the hard way why they were bad because of that switch out of Chapter Tactics for Stubborn in 5ed... Stubborn isn't your friend.

Where as you could say... take the main codex Gladius Strike Force, run it as Sentinels of Terra and have 90% of the Sternhammer's functionality without the accursed Dorn's Legacy of the sternhammer strike force dragging you down.

I know, this is only one vague instance where how things before and after Angles of Death may minutely affect how a select few players play their armies. It is never the less still there and does offer that niche few players some rare chances to diversify while maintaining their own already unique play styles.

All I'm saying is: till GW actually comes out and says the supplements are obsolete/redundant, they should be maintained.

**Comment by Maglorum** [comment]
At least the addition of the sternhammer and the others Strike forces need to be added to update the use the up to date space marine codex + angels of death, like it was done for the white scars and ravenguard strike forces.

**Comment by penguin20000** [comment]
I've been tempted to look at adding the new Decurion style detachments from Angels of Death Chapter by Chapter but work is a bit hectic at the moment and I can't give it the time that it needs currently :(.

Hopefully soon, unless someone else jumps on it.

**Comment by DrTobogganMD** [comment]
I've taken up sm as the maintainer. I'll work on adding the supplement things first to get them in. I agree that none of the old supplements should be decommissioned. GW had said in the wolves supplement that rules from either could be used for conflicting. So until they say that they are obsolete, if err on keeping them available.
