### ISSUE TITLE
Necron Mephrit Dynasty Relics

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-7th-edition#2121]
The 3 relics from Shield of Baal: Extermiantus need to be limited to the Mephrit formations/detachments per rules on page 353 of the supplement:  "Certain units chosen from the Mephrit Dynasty Detachment and Formations can also make use of the Relics and Warlord Traits listed below."

The valid detachment/formations are: 

Detachment: Mephrit Dynasty Cohort
Formation: Zarathusa's Royal Decurion
Formation: Anrakyr's Strategic Decurion
Formation: Conclave of the Burning One
Formation: Guardians of Perdita (Really just a formation of the 3 formations above, but not a detachment)

The 3 relics to limit are:

The God Shackle
Solar Thermasite
Edge of Eternity

**Comment by OftKilted** [comment]
Please clarify on which Battlescribe platform you see the issue. (IOS/Android/PC or Mac)

**Comment by OftKilted** [comment]
Due to BattleScribe 1.15 issues, the requisite items are not hidden in IOS (and potentially Android) whether or not Exterminatus Mephrit Dynasty is taken. These items are already 'hidden' unless the Mephrit Dynasty is taken. But this will not be resolved until the release of BattleScribe 2.0 due to issues with show/hide. (On the desktop version, the show/hide functions correctly.)

**Comment by DrTobogganMD** [comment]
@cartag offered a solution to the show/hide issue, if you don't get time before 2.0 I'll see what I can do about fixing it and throw a pull request your way.
