### ISSUE TITLE
Eldar Exarch

### ISSUE THREAD

**Issue by wah22** [BSData/wh40k-7th-edition#2147]
In the 2015 Craftworld codex, exarch upgrades cost 10 pts. But the data file says they are around 40 pts. Can someone fix this?

**Comment by efalsken** [comment]
The cost is correct. In Battlescribe, the cost per Exarch also includes the cost of the base model (who is then "upgraded" to an exarch) and the cost of any required gear that must be purchased separately. (the cheapest option, if applicable)

**Comment by wah22** [comment]
So this means it is the cost of an exarch upgrade and the lowest cost upgrade of gear? Is it really required to add gear?

**Comment by wah22** [comment]
Also, will there be a future option in selecting gear for exarches?

**Comment by efalsken** [comment]
That option already exists. The cost includes gear only if the option is required. For example, the Aspect Host formation includes (pre-selected) a few units of Dire Avengers since they are the cheapest of the aspect units. In most cases, the Exarch does not have a "required" option, so it does not apply. They are equipped with their default wargear, and you click or tap into the Exarch to change their gear.

![image](https://cloud.githubusercontent.com/assets/253640/15126601/904116a6-15e7-11e6-80a7-9d70cbb47a0b.png)

**Comment by wah22** [comment]
I noticed that when I choose an Exarch for the dark reaper squad, and when I then click on it, it won't let me select any options.

**Comment by wah22** [comment]
Oh I am using the android app

**Comment by wah22** [comment]
Thanks for the help by the way.

**Comment by wah22** [comment]
It won't let me select options for the dire avenger exarch either.

**Comment by wah22** [comment]
I can select power blades for a warp spider exarch but not his specific upgrade to a better monofilament weapon.

**Comment by efalsken** [comment]
All of those models have options that do work. you probably need to tap onto the Exarch after you added it to descend into that level. I do know that it works. On the iPhone,  I have to tap the box to select the Exarch, then on the Exarch's name itself to go into the Exarch and see his options.

**Comment by wah22** [comment]
Okay. Maybe it is an issue with battle scribe then.
