### ISSUE TITLE
Eldar Units Points Costs not showing

### ISSUE THREAD

**Issue by SentryTheDefiant** [BSData/wh40k-7th-edition#215]
There are a handful of units that have their primary models nested in an unnecessary group between the unit and models, so the base points cost for the squad doesn't show on the main army list menu.
This means the only way to see how many points they are is to add them to your list. 

e.g.  Guardian Defenders -> Guardians -> Guardian x10 @9pts ea  
should be: Guardian Defenders ->  Guardian x10 @9pts ea

Units are:

Harlequin Troupe
Howling Banshees
Striking Scorpions
Wraithblades
Wraithguard

Dire Avengers
Guardian Defenders
Storm Guardians
Windrider Jetbike Squadron
Wraithblades (Troops)
Wraithguard (Troops)

Shadow Spectres
Shining Spears
Swooping Hawks
Warp Spiders

Dark Reapers

**Comment by Kangodo** [comment]
You are correct. I tried to 'hotfix' this by using a Default Selection, but that doesn't solve it for most units.

The problem is that both the unit AND the Exarch-upgrade are options in the Entry Group.
It looks like this, with the min/max behind it.
Main Entry

> Entry Group: 0/infinite
> 
> > Models of 20 points: 5/10
> > Upgrade of 10 points: 0/1

The Main Entry asks the Entry Group what the minimum is, and the Entry Group says it's 0.
So the Main Entry tells you that the minimum amount of points is 0.

An 'easy fix' would be to set the Entry Group at a min/max of 5 to 11 with a Default of the Models.
Min = 5 because you need at least 5 models.
Max = 11 because you can have a max of 10 models and the upgrade.
That would mean the Entry Group now replies with "I need at least 5 selections and my Default are the models, so that's 100 points." and the Main Entry would reflect this.

Someone that knows the Codex could probably do that in 15 minutes.
If I were to do it, it would take hours because I had to look everything up in a PDF ;) Just to make sure I didn't make any mistakes.

**Comment by amis92** [comment]
While I'm here, I'll put forth an academic discussion.

(mind you it's not directed at anybody; rather a proposition)
I'm decidedly against such Grouping. I imagine a Group being a choice of similarly-weighted Entries. What I cannot stand are such Groups as mentioned above, where in single Group we buy both _models_ and _upgrades_ to them.

I'd see it two ways: _either_ knock Exarch upgrade out of the group _or_ turn upgrade Entry into Exarch entry, which would have the cost of model and upgrade, and represent an actual Exarch.

I prefer making such choices as they seem to look like: make a Group of _models_ available in unit and set limits appropriately. Exarch is a model, not an upgrade in this scenario.

All this applies to units where leaders are optional upgrades.

Actually I think it should make it's way into catalogue-development. (EDIT see [#3](https://github.com/BSData/catalogue-development/issues/3).)

**Comment by Kangodo** [comment]
I fully agree, which is why I called my idea an 'easy fix' because you wouldn't have to basically redo everything.
Those models and the upgrade are on a different level and that should be reflected when we create the datafile.
The way this is created "works" because it can create a correct outcome, even though the path to that outcome is incorrect and may be confusing. Especially if someone, like me, wants to fix things later on.

**Comment by Kangodo** [comment]
#183 seems to have fixed this.
We can thank amis92 for that!
