### ISSUE TITLE
Typhus + Chaos Space Marine Codex

### ISSUE THREAD

**Issue by Shadowed0ne** [BSData/wh40k-7th-edition#2157]
At the moment, as long as Typhus is in the army, he can upgrade any Chaos Cultists into Plague Zombies. This includes Chaos Cultists taken in formations, i.e. Helcult and Cult of Slaughter.

Can you change the cultists to be changed as an option? Or give the formations an option to swap them if Typhus is in the army?

**Comment by OftKilted** [comment]
Isnt cult of slaighter a Crimson Slaughter formation?  If so, typhus cannot be taken as part of a crimson slaighter army as they can't have any units other than plague marines and Berzerkers with veterans of the long war.

**Comment by cartag** [comment]
The only reason I'm setting this as vague is because of the CSM restrictions and terminology differences between 6E and 7E. For the Helcult it is an obvious inclusion that needs to be made. Given that supplements and the wide berth of options available to us wasn't there in the first codex of 6E, it leaves some interpretation. Typhus isn't legal to bring in a Crimson Slaughter force though, hence my hesitation. Ongoing discussion.

**Comment by Drachnyen** [comment]
One could take a CAD (vanilla) with typhus in it.  And then use a cult of slaughter formation from Crimson fist.  Then use the first paragraph of page 87 of the Crimson slaughter book rule to "make" the first detachment a crimson fist one.

**Comment by Drachnyen** [comment]
@cartag where do you see that Typhus is not allowed in a crimson slaughter force?  I could not find any reference to it. Thanks.

**Comment by thejughead** [comment]
Forces of the Crimson Slaughter page:

RENEGADES OF THE DARK MILLENNIUM No units in a Crimson Slaughter Detachment or Formation can have the Veterans of the Long War special rule except Khorne Berzerkers, Plague Marines and Noise Marines.

**Comment by cartag** [comment]
As @thejughead stated, the only models that can have VotLW are those three choices. This includes HQ choices and Thousands Sons.

**Comment by Shadowed0ne** [comment]
Like @Drachnyen said, Typhus would be part of the CAD while Cult of Slaughter would be it's own Crimson Slaughter Formation.

Typhus Plague Zombies special rule says "Any Chaos Cultist units in the same army as Typhus can be nominated as Plague Zombies." Typhus wouldn't be in the Crimson Slaughter formation, but it his own CAD, but still affecting other formation/detachments in the army. Unless I'm missing something.

**Comment by cartag** [comment]
Logically speaking though he should have the ability to affect cultists he controls, if they're part of a different force they wouldn't be. It's been asked on the 40k Facebook page also. 

This shouldn't be allowed for KDK cultists, for example as they are different from CSM cultists.

**Comment by cartag** [comment]
Don't forget, the codex comes from a time when we didn't have formations, everything had a FOC, and there were no supplements. "Army" as mentioned then had an entirely different context than it does today.

**Comment by Drachnyen** [comment]
I agree with Cartag that it was probably not intended to be used in the suggested fashion.  

Fluff wise: Why would Crimson slautgher bring zombies to a fight?  They don't use zombies.

**Comment by thejughead** [comment]
RAW, yes to zombies; RAI, no codex is too old and before detachments.  What is the usual protocol for this RAW or RAI?

**Comment by Drachnyen** [comment]
Don't know about protocol, I'll let Cartag answer. 

It's a great question for the upcoming CSM FAQ, I'll send it their way.

**Comment by cartag** [comment]
I think the consensus we came to when discussing it is as follows. 
1. Setting any formation able to be taken by CSM vanilla or Black Legion to swap out for Plague Zombies, including Apocalypse formations.
2. Question has been submitted to GW on if it would affect Crimson Slaughter formations (since Typhus can't be part of a Crimson Slaughter detachment), and how to interpret rule in the age of Detachments and Formations being par for the course.
3. This won't affect KDK in the slightest, given that the rule specifies a page number for the Cultist unit. Plus the unit size is different, different special rules, etc.

If you can come up with a compelling counterargument it's up for discussion.

**Comment by cartag** [comment]
For the time being, this may be as official as we can get. 

![image](https://cloud.githubusercontent.com/assets/4388344/15217794/6346436c-181a-11e6-9092-c2a1c522a7b9.png)

**Comment by hisop** [comment]
Are we waiting for an official faq, or are we taking this for now and closing the issue?
