### ISSUE TITLE
Dark Angels Wargear

### ISSUE THREAD

**Issue by SentryTheDefiant** [BSData/wh40k-7th-edition#223]
A majority of characters have their weapons options nested under "left hand"  "right hand" when they should be simple "ranged weapons" and "melee weapons". At times there are items that are available to the character twice and in the wrong category. 

e.g. tactical marine Sargeant can take a Boltgun under right hand and left hand.

The options should directly reflect the way wargear is selected from sections if the armory.

**Comment by amis92** [comment]
So how would you create the groups?

**Comment by amis92** [comment]
Also, the discussion already took place in #128.

**Comment by axisofentropy** [comment]
## Yes I changed many characters but not all. Remains to be done. I'm on vacation this week but I can get it next week.

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by amis92** [comment]
I would play with it, but am still not sure which combinations are allowed. Quoting my post from that issue:

> So, what I can read is, we either:
> - take default boltgun and bolt pistol OR
> - take boltgun and CHANGE bolt pistol for one of Melee Weapons OR
> - change boltgun for Melee Weapon AND change bolt pistol for Ranged Weapon
> 
> Am I correct?

**Comment by SentryTheDefiant** [comment]
Sorry if it's already been covered. I went back a little bit and didn't see anything. Must not have gone far enough. 
If you prefer, I can move back to 128, but I'll just add some feedback here for now. 

For the sake of discussion, let's focus on the tactical squad.

Since the entire squad already gets boltgun and bolt pistol by default, I'd put the link to both profiles under the character. 

The entry in the codex States that the Sargeant may take additional weapons, not replace his defaults, so technically he could be allowed to have a bolter, then buy any number of ranged weapons and or melee weapons. (though most players only buy one or the other or one of each) 

Since it's not actually "must choose one option",  you don't have to make any weapon a default, and although boltgun is actually on the list of ranged weapons for free, it's safe to leave off because the character already has it and never has to replace it to get other weapons.

**Comment by axisofentropy** [comment]
The Melee Weapons and Ranged Weapons Wargear section of the codex says "replace", so a Tactical Sergeant will only ever have two weapons (plus grenades).

amis92, your interpretation looks correct for most sergeants.  The scope of this issue is all the other characters who begin with other default wargear, like crozius, chainsword, et al, which makes it more complicated.  Any model with access to these wargear lists may:
- Replace either weapon with a Melee Weapon
- Replace their bolt pistol or CCW with a Ranged Weapon
- both of the above

I might have an idea on how to implement this in Battlescribe: hide the default wargear IF a selection is made on one of those wargear lists (now I know better how modifiers work).  I'll keep thinking about this and look at it this weekend maybe.  It may be easier if I don't allow for combinations that don't have value, like two boltguns.

**Comment by SentryTheDefiant** [comment]
My mistake, I'm so used to seeing codeces putting the replacement clause under the entry. 

One solution that would make it more accurately reflect the codex, but not really save the user any clicks, is to list the boltgun and bolt pistol under squad (collective?) and then just give the Sargeant a "replace bolter"  and "replace bolt pistol"  options. Each one would have an option to look at both lists, similarly to how armor section has two armor types and a selection of weapons under that.

This makes it clear to the user that the weapons have been

**Comment by SentryTheDefiant** [comment]
Oops

Replaced, and also keeps the user in the mindset if selecting from a wargear section that is actually in the book. 

You could probably un-nest these options as well as special wargear so they don't have to click the Sargeant, character options, replace bolter.

**Comment by amis92** [comment]
I've now thought about it for an hour, and have no aesthetic solution. If anyone has any, please share. :)

**Comment by SentryTheDefiant** [comment]
I haven't figured github out yet, but is there a way I could make the edit and put it somewhere for people to try without actually publishing it?

**Comment by amis92** [comment]
Yes there is. Create a new branch (and make sure you're on it), name it shortly, do the changes, commit them (on that branch!). Now publish it (there is a button instead of Sync) and let us know about it somewhere. We can then change up the branch on our local repos and test the changes. That's quite a bit of work admittedly, but it's really not that hard after first time. :)

**Comment by axisofentropy** [comment]
Here's what I'm attempting:

![screenshot from 2014-08-19 22 21 16](https://cloud.githubusercontent.com/assets/66315/3976112/43710b46-2819-11e4-8a23-d60594716f5d.png)

But this does not provide a good interface:

![screenshot from 2014-08-19 22 25 19](https://cloud.githubusercontent.com/assets/66315/3976124/ad536478-2819-11e4-8325-69c2a2c78515.png)

What I really want is for the Boltgun and Bolt pistol to appear in the output roster (until replaced and hidden) but not in the right-hand interface (and not in the errors at the bottom).

Is there a way to drop an entry when another upgrade is chosen?  If not, I'll just use the existing stuff implemented in #128 for the other Sergeants and HQ.

also ping @Jonskichov 

P.S. The DA codex looks like a sergeant cannot take both a combi-weapon and a bolt pistol, which is disappointing.

**Comment by SentryTheDefiant** [comment]
This seems to be headed in the right direction. I believe what you want to do is possible. I was playing around with this the other day and it looks like you can hide it if it's not a link to an entry. I know for cleaner data, links should be used whenever you can, but in this case I think it's necessary. I'll look further into it later. 

Also, why do you say you can't take bolt pistol and combi weapon?

**Comment by axisofentropy** [comment]
> Also, why do you say you can't take bolt pistol and combi weapon?

Most Sergeants start with a bolt pistol and boltgun.  The Dark Angels
Ranged Weapon page says you may replace the bolt pistol with a
combi-weapon, leaving him with the boltgun.  I suspect a lot of players
aren't getting that right, or maybe I'm missing something?

A dakka thread argued that they could replace the boltgun with a
chainsword, then replace the chainsword because it's a "close combat
weapon", but I don't think they're the same thing in 7th.
http://www.dakkadakka.com/dakkaforum/posts/list/604969.page#7021184

**Comment by axisofentropy** [comment]
On 08/20/2014 10:23 AM, Justin wrote:

> I was playing around with this the other day and it looks like you can
> hide it if it's not a link to an entry.

Not using links is fine if it works, but I couldn't get that working
either.  Can you make screenshots of what worked for you?

**Comment by SentryTheDefiant** [comment]
I'm not at the pc i was working on till later tonight, and I'm not even sure if I saved it, but I'll try to get a screen. 

7th rules state that models not listed with any weapons of the melee type are treated as being armed with a single close combat weapon. So there's that... 

Since the model has a pistol and the big rule book says all pistols have the same profile in close combat, strength: user, AP dash, type: Melee, that would be counted as the close combat weapon. They probably listed it as "boltgun or close combat weapon" to cover their bases with all squads including assault Marines?

**Comment by SentryTheDefiant** [comment]
Nevermind. I was thinking about that backwards. It still doesn't seem right, but you appear to be correct.

**Comment by axisofentropy** [comment]
> Nevermind. I was thinking about that backwards. It still doesn't seem
> right, but you appear to be correct.

Yes, it's probably not intended, and needs a FAQ, but that's what it says.

I don't have the Space Marine book, what does it say?

**Comment by SentryTheDefiant** [comment]
Believe it or not, it says "replace bolt pistol or Melee weapon"  under both categories. However, it states in the tac squad unit entry that they may replace either weapon with a chainsword for free. I'm not sure if the order of the options matters, but it lists this above the ranged/melee allowance. 

In which case, taking a chainsword, then replacing it seems like a valid option.

**Comment by senpai514** [comment]
That is correct you can trade the bolter for a chainsword and then use the chainsword to swap for a ranged or melee weapon

**Comment by Thairne** [comment]
Well uhm.. I'm not sure where y'all are going with this, but this is the current implementation:

![untitled](https://cloud.githubusercontent.com/assets/8590840/4522597/6a7fff62-4d2b-11e4-8eea-7af23bd8c435.jpg)

If I understood this thread right (read it 3 times, and still not sure :P)
this is kind of what you wanted?
Also, this
https://github.com/BSData/wh40k/issues/388
might be relevant to the discussion.

**Comment by leedstilidie** [comment]
Hi. Just wondered if this issue will be resolved and left and right hand will be changed to melee and ranged for dark angel characters. I can't use my list otherwise. Thanks

**Comment by leedstilidie** [comment]
Also. There's no option to chose a deathwing sergeant and his weapons in the deathwing squad section. I have the iOS versions for iPad and iPhone.

**Comment by leedstilidie** [comment]
What I mean is I have a converted company master model using the space marine commander kit. I have a lightening claw on the left hand and s storm bolter on the right which is foe smitter. Now when the option just said melee and ranged there was no problem selecting foe smitter, lightening claw. After it changed to left and right hands s have to select the lightening claw for the right hand when it's on the left and a ranged weapon for the left when it's on the right with no option for none. When I then select foe smitter it errors saying I have too many options for right hand??!! They needs to be melee and ranged and within this menus an option for none so a relic weapon can be selected.

**Comment by Thairne** [comment]
Well honestly, I don't really consider it a problem when your "right hand" weapon is modelled in your left hand and vice versa. Usually all SM are depicted with the melee weapon in the right hand and the ranged weapon in the left - some guy might want to put the lightning claw on his helmet for headbutting action, am I supposed to take that into account too? ;) Ofc I can change the labels into "melee" and "ranged", but that wouldn't change any functionality.
On a more serious note, you can with zero errors equip your company master as you said, LC and Foesmiter is possible, since there IS a "none" option for either hand to allow just for this.

Concerning the DW Sarge - the FAQ screwed him over. He does not have a Power Fist to swap so he is stuck.

**Comment by leedstilidie** [comment]
Hi pal. Thanks for reply. There is no none option on my data. It's for iOS on the apple app. Don't know how to alter this. Thanks

**Comment by leedstilidie** [comment]
Meant to add it has these options for sergeants and librarians etc. just not company master so getting error messages. Ta

**Comment by Thairne** [comment]
Weird. I don't have an Apple device, only the Desktop app, and it shows there.
I took a look at the company master again and there IS a none option.
Now, if this issue persists I'd ask you to open a new issue as not to clutter this one with somewhat off topic comments.
I will rename the labels just for clarity some time in the future - when I also figured out how to deal with the topic this issue deals with.

**Comment by leedstilidie** [comment]
Hi. Ok will do. It's actually all the independent characters when I checked including the librarian. I'll make do with the error messages until it's sorted. Don't have the desktop version only the pro Apple app. Thanks for your help.

**Comment by senpai514** [comment]
Is this still ongoing or has all the work @Thairne done resolved this issue?

**Comment by leedstilidie** [comment]
Hi. Yes it's resolved thank you. Great job!!!.
