### ISSUE TITLE
Bug report: Space Marines - Codex (2015) 

### ISSUE THREAD

**Issue by arathas3d** [BSData/wh40k-7th-edition#2260]
Techmarines should not take a hq slot if you have a hq selected that is not a Techmarine or a servitor.

**Comment by arathas3d** [comment]
Also I cannot choose a Master of the forge as a hq Choice,  thus I cannot choose dreadnoughts as heavy

**Comment by francoisbeaulieu** [comment]
Do you have a source for this? I know that's the case for Grey Knights, and perhaps one or two other specific factions, but it's not the case for basic space marines codex chapters as far as I can tell.

**Comment by arathas3d** [comment]
Space Marines codex page166

**Comment by francoisbeaulieu** [comment]
Hmm, my page 166 has nothing on that subject, but I may not be using the same format as you. What's the title of the section you're referencing?

Also, make sure it's 7th edition, since the BattleScribe data files always reference the most recent version available.

## 

François Beaulieu (iPhone)
(514) 667-0691 x2061

**Comment by DrTobogganMD** [comment]
@Arathas, that is a rule for GK - not Space Marines.  Master of the Forge is a model that is available in the 6th edition Space Marines codex, not the 7th.  The data team for 40k does not include older codex catalogs if there are newer versions available.

**Comment by arathas3d** [comment]
Ok I didn't know that they remade the codex again. I will need to get ir
