### ISSUE TITLE
Space Wolves - CotGW Detachment TH/SS Terminators

### ISSUE THREAD

**Issue by SuperPranx** [BSData/wh40k-7th-edition#2264]
When you add a TH/SS terminator in the middle column (on PC) you see only terminator armor listed. The TH and SS are there when you view the roster, but they're not showing in the list while you're editing your roster.

**Comment by DrTobogganMD** [comment]
It is behaving correctly - Adding a SS/TH terminator costs 15 points more, which is accurate.  Since they cannot take any other options individually there is no need to edit their loadouts.  XML wise, they are linked to the weapon profiles, not entries, in order to save lines of code.  We _could_ add an entry for each and link to the profile, but that just adds more lines for no additional functionality.
