### ISSUE TITLE
[Anon] Space Wolves - Relic limit

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#230]
There's a false limitation of one Relic per Wolf Lord, Wolf Guard Battle Leader, Rune/Wolf Priest.

The proper limitation is one copy of each relic per army.

Currently I'm trying to use the Armour of Russ with the Fangsword of the Ice Wolf, but I can't do it because of this error.

Storm Shields are listed as 25pts for non terminator Wolf Guard Battle Leaders.

**Comment by Kangodo** [comment]
The limitation is correct, maybe the author wants to remove it anyway?

**Comment by Araziel369** [comment]
Quote from the SW codex:

These artefacts are items of incredible rarity, ancient heirlooms that are carefully maintained and stored within the impregnable armouries of the Fang. Only one of each of the following relics may be chosen per army.

The limitation is Incorrect. It is one per army, not per HQ.

**Comment by Kangodo** [comment]
And they may replace ONE weapon for ONE Relic, not multiple weapons for multiple Relics.
Discussion can be held here: http://www.dakkadakka.com/dakkaforum/posts/list/609767.page

**Comment by Araziel369** [comment]
That only pertains to replacing one of the models weapons specifically, in the case of a wolf lord it is either the bolt pistol or chain sword that can be replaced with:

The Bite of Fenris
Black Death
Fangsword of the Ice Wolf

The following relics do not replace weapons and can be taken as well:

Helm of Durfast 6 (wargear)
Armour of Russ 6 (Replaces Power Armour)
The Wulfen Stone 6 (wargear)

6 Does not replace one of the character’s weapons.

I am in agreement that you may only swap ONE weapon, for ONE weapon type relic, because it clearly states such in the codex. 

Quote: "Only one of each Relic of the Fang may be taken per army. A model can replace one weapon with one of the following"

However this does not pertain with those that have the '6' tag, simply because they are not weapon relics that replace weapons.

**Comment by coruptcopy** [comment]
That thread is pretty crazy. Haha!
The actual wording is this:
"Only one of each Relic of the Fang may be taken per army. A model can
replace one weapon with one of the following"
I see the arguments for both ways, but seeing as you do get the option to
use two Relics without swapping weapons out, this makes me think the intent
was to allow a single model to take multiple, though the actually wording
of the rules isn't exactly clear.
I have to agree with Arazel here.

The problem has more to do with the use of the English language and how
easy it is to have multiple interpretations of a single sentence. As an
English Professor, I can understand both semantic explanations. However, I
believe it could be made more clear by using the word "only" again in the
second sentence. Since the rules writers (who are consistent with this
wording in "Relics" in CSM, Dark Angels, and Space Wolves plus likely more
codecies) uses the phrase "Only one of each Relic" in the first line,
making it clear that you may "only" have one, the lack of the word "only"
in the second line would lead me to conclude that you may select multiple
Relics per character as long as you meet the following criteria:
You have a weapon to swap out (if required)
and you do not include multiple selections of the same Relic in the same
army.
However, if the wording were like this: " A model can replace only one
weapon with one of the following" I would say then yes a single model can
only have one Relic. Does that make sense?
And again, this is just my opinion and in no way definitive. But I have
been playing with multiple Relics on a single character from CSM and DA for
months now. Haha! So if I'm wrong, it must just be that no one has called
me on it yet or the rules are so confusing no one is quite certain. :-p

**Comment by Araziel369** [comment]
If having an English professor agree with me doesn't count as a win, I dunno what will.

I just want this fixed in the SW data for Battle Scribe. Armour of Russ and Fangsword of the Ice Wolf is going to be an epic combination.

I have just had an influx of new models and I really need this to help build my list and get a solid feel for what my army will have in it.

**Comment by Xianator** [comment]
I'm a fan of Helm of Durfast + The Wulfen Stone pairing.

**Comment by coruptcopy** [comment]
Sounds good to me. Too bad I don't play with Space Puppies. :-p Dark Angels
for life! Haha

**Comment by ghost** [comment]
The non terminator Wolf Guard Battle Leaders can take Melee weapons, which includes the Storm Shield at 15pts. I believe the 25pts option refers to the Terminator WGBL - arguably, it could be both, but then they would've put a footnote on the shield in the Melee weapons list, in the same way that the Jump Pack has a note excluding the Iron Priest.

GW's use of English is terrible, not that I'm any expert. For example: "...replace his bolt pistol and/or Melee weapon with one...Storm bolter". That means the model can give up both weapons & receive a single Storm bolter, but no-one ever does this, because we all accept that's not what they mean. The Armour of Russ does not have a footnote telling us that it replaces the model's armour, but we all accept that this is what happens. We can rule out taking two weapons, because the Relics list does not say "may replace _any_ weapon with _any_ of the following", it says "one". It is this repeated emphasis on "one" that leads me to believe a model can only have a single Relic. They could certainly have worded it better but, without wishing to cause offence, trying to take two sounds very much like a lawyerly exploitation.

The Spanish codex states simply: "A miniature can choose one of the following".

**Comment by coruptcopy** [comment]
Yes, but didn't the French version of the codex have a huge change in
wording too? I'm more concerned with the native tongue this was written in:
English (granted poor, as you've pointed out, and British English :-p haha).
You make a great point about the other quote: "A model can replace his bolt
pistol and / or close combat weapon with one of the following" however,
your interpretation is only one of several. We could read that line as you
have: you can swap out both the pistol and the ccw for a single item. Like
you stated, no one does this. The "or" implies that you have the option of
just choosing to swap one out. So perhaps on one model I'd rather keep the
pistol, so I'll swap the ccw, or vice versa.
Yet there is a third option here. Since, as you said, it would be silly to
swap out both for one single weapon, we can interpret that "and" quite
differently (and likely as intended) to mean that I may swap both my bolt
pistol "and" my ccw for a single weapon a piece. There is no part of the
text which states that you can only perform this swap one. And if, as so
many are arguing, that is intended to be the case due to GW's use of the
word "one" as in both of these examples (Relics and Ranged weapons) then
you could argue that you may only do this once per army since it uses the
word "one" in the wording. If I let my Wolf Lord swap out a weapon in
Ranged Weapons list, does that therefore prevent anyone else from swapping
for a different Ranged weapon as well? Obviously this answer is no. That
wouldn't make much sense after all, but we could use this use of the word
"one" argument to make that true; therefore, I would recommend the more
likely intention of the rules play out here. Once more, "a model can
replace one weapon with one of the following [Relics]" to me doesn't state
that this replacement may only occur once per model. There are ways to make
it read that way much more clearly (insert the word "Only" or replace "one
weapon" with "a single weapon may be replaced" or simply inserting "per
model" at the end). Therefore, I still think you can take multiple Relics
per model as long as you meet the other requirements.

**Comment by ghost** [comment]
Yeah, translation errors can come into it. According to Bing, the Spanish codex actually says: "A thumbnail can choose one of the following"... 

Still, I reckon their intention is for a model to have one relic, and the footnote means 'since the relic isn't a weapon, the model gets to keep the weapons it already has'. It doesn't limit you to only having a relic on one model, because the list says "_A_ model can replace one...", not "_One_ model can replace one...". Although it means the same in literal terms, we accept the difference. As with the "and/or" situation and the Armour situation, we are all tacitly acknowledging RAI. In contrast to that, putting two Relics on a model requires a very deliberate reading of the description.

**Comment by coruptcopy** [comment]
Perhaps. Not my reading, but just as dakkadakka didn't reach a definitive
answer, it's unlikely we will either. Would you read the Tyranid
Bio-artefacts in the same way then. Here's the wording: "A model may
replace any pair of scything talons with one of the following." Most Nids
that can take their Relics (Bio-artefacts) have two pairs of talons. I'm
just wondering if it's that first "one" that makes you read it as you are.
In this case it's not "one," but "any." Bottom line: GW should clear up
their rules. :-p But since we are writing the catalogs for BattleScribe,
guess it's up to us to decide the rulings unless this is covered in a FAQ
somewhere. Cheers! :-D

**Comment by coruptcopy** [comment]
P. S. Wish my thumbnail could take a Relic from the Space Wolves codex.
Haha!

**Comment by coruptcopy** [comment]
Sent GW a FAQ question about this. We'll see if / when we get an answer.
:-p Until then, I've said my piece about it, but I'm new. What do I know?
:-D Peace.

**Comment by Kangodo** [comment]
I propose this solution:
Entry group says 'pick one' and then we allow people to pick two :D
Should make everyone happy, right?

**Comment by coruptcopy** [comment]
Haha! Brilliant, Tim! :-p You should be a rules writer, sir. Haha!

**Comment by ghost** [comment]
I would guess with the 'nids that if you replace both pairs of talons, they both have to get the same option...?
Muddying the waters; if you replace a chainsword with the Armour of Russ, but the model gets to keep the chainsword, that could mean you can't then give it a TH & SS, because the chainsword has been nominally swapped already... lol.

If there's no answer to that email, I could set the file up so people can play it either way - stand aloof, as it were, and leave it to the end user to argue about. I guess it's up to the playerbase & GW to make a ruling, rather than us.

**Comment by coruptcopy** [comment]
That sounds like a good idea to me. You can discuss it with your opponent.
If we get an FAQ from GW, then we deal with it then. Haha! Yeah, the more
we discuss this one, the more screwed up it becomes. Haha!

**Comment by amis92** [comment]
Yes indeed. I'm with "one relic for one model" side, however I think if the legal combination is available, and not-known-to-be-legal-for-sure can be added at no real cost, add it.

**Comment by Kangodo** [comment]
I think that solves it!
Maybe we should remember this for future codices, because I doubt GW will learn from it.
So the maximum can be set to -1, because the discussion will be endless.

**Comment by ghost** [comment]
Changing it over will just be a case of deleting the modifiers - it's the thought of putting them all back in later that makes me sick!
I'll do it when I add the Champions of Fenris.

**Comment by Araziel369** [comment]
Okay just so I understand it, is it basically the way I read it, that one weapon can be swapped out for one relic weapon, then combined with non-weapon wargear type relics?

I reckon the battlescribe data shouldn't be hard coded to any particular ruling, that way it can be left up to individual house rules to determine relic limitation.

**Comment by amis92** [comment]
@khambatta I feel you. If you make a single commit for just these changes, there is later an option of commit reverting. Basically turns back the change introduced in the commit. Of course the more the catalogue is changed in the meantime, the more possible is that reverting will destroy XML markup.

**Comment by ghost** [comment]
I'll see if I can isolate and save those bits - then it'd just be a case of pasting back in.

@Araziel369 - In short, the argument is either that a model can have just one relic, or that a model can have one weapon-relic _and_ an infinite number of non-weapon-relics. If it was intended to be the latter, the list would state "A model may take up to one of each of the following", in the same way as the Special Issue Wargear, with a footnote like number 4 on the weapons. But as you say, I'll leave it to the individual.

**Comment by Araziel369** [comment]
@khambatta: I noticed some weird stuff going on with the grey hunter squads with close combat weapons when I was making them, you have no option to replace a chain sword with a special close combat weapon, only bolters and bolt pistols can be replaced in the program.

I tried to make a squad of 9 Grey hunters + 1 Wolf Guard pack leader (10 models) equiped with:

Grey Hunters:
8 Bolt Pistols
1 Plasma Pistol
7 Bolt Guns
2 Melta-Guns
8 Chain Swords
1 Power Sword

Wolf Guard Pack Leader:
Power Fist
Plasma Pistol

You have the special weapon options under Chainsword set to: Flamer, Melta and Plasma gun, instead of the close combat options.

If I drop a chain sword, and try to use one of the special melee weapon options under bolt pistol or Bolter, it says I have too many options taken for both, because I have bought special weapons for them already.

**Comment by coruptcopy** [comment]
We could always leave it as is too. I mean, just because BS is telling me
my army list isn't correct, doesn't mean I can't play it that way, as long
as the option to select multiple Relics is present, it could be kept as is.
Hate to cause trouble.

**Comment by Araziel369** [comment]
My complaint is that it's not present with the combination I wish to make, If I select Armour of Russ, then I click the armour to select the melee weapons, the relic weapons are not listed.

For now that's the only thing I'd ask to be fixed.

I just want to equip my wolf lord with the Armour of Russ and the Fangsword of the Ice Wolf.

**Comment by ghost** [comment]
For Grey Hunters, there is no option to replace a chain sword with a special close combat weapon: those can only be taken in exchange for the bolter or bolt pistol. You can make up your list by taking 1 Grey Hunter with bolt pistol and melta, then taking 8 Grey Hunter w/ Chainsword and giving them the other upgrades. But jings, it's a maze, isn't it... I'll see if I can re-arrange them to make it easier to figure out.

Looking at the book, can the Wolf Guard also buy an extra Chainsword?

**Comment by Araziel369** [comment]
I wouldn't think so...also My bad on the close combat weapon options.

Now that I know how it works it's a lot easier to navigate.

Could you please make the Armour of Russ have Relic Weapon options? that would be great.

**Comment by evilmerlin** [comment]
The entry for Grey Hunters (and Grey Hunters only) specifically states that ANY model may take a close combat weapon. I don't see why a Wolf Guard in the unit would not be able to do so.

**Comment by ghost** [comment]
Grey Hunters have been greatly simplified. I've left out the option to upgrade the chainsword to a special weapon because I can't imagine who would do that (same goes with the Wolf Guard - we'd end up with someone trying to justify 3 Wolf Claws!).

I've switched over the Relics - characters can now take one weapon plus multiple non-weapons. You will still receive a warning in many cases...

I think I got all the affected units.

**Comment by Araziel369** [comment]
Thank you very much mate :)

**Comment by amis92** [comment]
Closed I think?

**Comment by Araziel369** [comment]
The wolf lord entry no longer screams at me for taking more than one relic, WGBL still does though but that's only a minor annoyance, great job cleaning up the grey hunters ^_^

**Comment by ghost** [comment]
That's the Champignons de Fenris added. The warnings on the relics have been removed.

**Comment by WJTyler** [comment]
Nice work on these! I was stuck on the formations, but just figured it out!

Thanks!
