### ISSUE TITLE
Selecting Warlord

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#235]
The ability to make an HQ selection the Warlord does not appear to be available in this roster.

**Comment by peterlyberth** [comment]
Unable to reproduce on the latest desktop version.

**Comment by peterlyberth** [comment]
AH!
Now I get it. You want an hq selection to have a "Select as warlord" option?

Has that been the case previously?

**Comment by Kangodo** [comment]
Some codices have this, but you would have to add it to each Character.  I personally don't see the benefits at this moment.

----- Reply message -----

**Comment by amis92** [comment]
Actually I think it's a worthy topic. There are ever more things triggered by choosing something as a Warlord. This edition it can be any character. That complicates things to a whole new level.

Do we want to handle it? I think, eventually, we'll need it. That might be viable and not _that_ hard to implement when we get hands on that tasty new BattleScribe Jon cooks for us here, making Warlord a min-max in roster = 1 shared entry.

I think that is good idea for future. What are your other ideas?

**Comment by Kangodo** [comment]
True, I was talking about my own Codices ;) They are still in 5th edition.
I think there are a lot of possibilities with this entry, I'm greatly inspired by how the Space Wolves handle it: The Warlord-entry has a lot of variation, depending on the Force-selection that you've used.

Having it available to any character would be quite easy since we can just link to it on every single character.

Personally I would prefer a Shared Warlord Entry with an Entry Group that has you select: Codex, Supplement or Apocalypse.
Under each of those you could have the rules that go with this group.

**Comment by amis92** [comment]
@Kangodo What differences do you have in mind between Codex/Supplement and Apoc?

**Comment by Kangodo** [comment]
My current implementation is as follows:

Warlord
-Detachment Source (min/max of 1/1)
--Codex
---Entry with Codex: Warlord Traits and perhaps some Codex: rules.
--Supplement
---Entry with Supplement: Warlord Traits and some Supplement-rules.
-Apocalypse (min/max of 0/1)
--Finest Hour, Divine Intervention-rules.

I could put those Traits and rules as a separate entry with a gazillion modifiers depending on the Force-selection! But this makes things easier and works better if you select Formations as Force-selection.
It also allows players to quickly peek at the special rules they would get if they'd pick a Detachment from another source.

You can open the Blood Angels-cat, I've already added it and will just fill in the blanks when our Codex hits. I'm already preparing it for the release, so I can edit it as quickly as possible.
I could use anything to spare me some time as I need to update both BA and Necrons in the upcoming months.

**Comment by ghost** [comment]
Are there missions where you don't disclose your Warlord to your opponent? That's why I've been leaving it at 0-1.

The setup for the Orks was a massive pain in the neck. I need to fix their Gifts/Gubbinz - when I do that, I was planning on changing their Warlord option to work the same as it does for Space Wolves. Like what you've done with the BA, though...

**Comment by amis92** [comment]
No way you don't disclose who's Warlord, "half" of special rules depend on it. ;)

@Kangodo I hope you're referring to the rumour BA and Necrons get new codexes, not that you'll update the existing ones? :)

**Comment by Kangodo** [comment]
Both ;)
At the moment my Warlord-entry has a 0/1 for Apocalypse, because those rules already exist.
It also has a selection that is now defaulted on Codex: Blood Angels, which means you use the BRB-traits.
The framework is in place, but players won't notice the difference until the Codex is released and I fill in the blanks.

I've also removed the Primary Detachment-entry from the cat and linked Relic of the Armoury to the Warlord-selection, seeing as the Warlord automatically makes it your Primary Detachment.
Testing it now and it seems to work perfectly!

**Comment by Xianator** [comment]
Some tournaments allow players to select their Warlord trait.  Having this built in to a roster could be a useful option.

**Comment by Kangodo** [comment]
I was personally planning to make 12 "Warlord Trait: XXX" profiles and then two Warlord-trait entries with the six profiles linked to it.
If you go to such a tournament, I think it'd be better to just check the chosen Trait on your print-out.

**Comment by amis92** [comment]
I'm thinking about making it as simple and useful as we can.

New idea (so that I don't forget):
An entry group in game system, can be overriden in catalogues.

> - Warlord type: (entry group min/max in force = 1/2)
>   - Warlord (entry)
>     - Roll for trait (rule)
>   - Apocalypse Warlord (entry)
>     - Roll for Heroic Sacrifice (rule)

So that in catalogues we'd override this group and it's entries, adding codex/faction specific traits, and for unique characters with their own traits we'd create modifiers telling to show a specific-trait-rule on condition that character was chosen.

**Comment by Kangodo** [comment]
But would that be possible?
I think we'd have to wait for the implementation in BS to see what we can and cannot do.

**Comment by amis92** [comment]
True that.

**Comment by Kangodo** [comment]
Small update!
For Blood Angels it now has a entry-group with either none, Codex, Archangels, Flesh Tearers or Imperial Knight.
The three BA-factions are hidden unless you also have the correct Detachment or Formation.
Imperial Knight is there for the 1 in 1000 scenario's where a Knight can be your Warlord (Unbound with only non-characters).
It then still has the Apocalypse-entry.

I've been thinking and I don't know if a override would be that helpful or work/filesize-saving.
But I guess we can close this issue for the time being, I doubt anything special or new will come out in the near future.
