### ISSUE TITLE
Space Wolves - if you take the required units in your formations you gain Wolf Claw Strike Force special rules

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#2372]
If in your formations you have 1 wolf Lord, 1 blood/sky/swift claw unit, 3 units of grey hunter/land speeders and 1 unit of long fangs you're then qualified to gain the extra rules for a Wolf Claw Strike Force. It doesn't matter which formations the units are in, just as long as they're present.

The secondary criteria is that out of the formations you need at least 1 core and 1 auxiliary.

Special rules are: counter-charge and the howl of wolves

**Comment by SuperPranx** [comment]
Go back to the rulebooks. That's not how WH40K army building works.

**Comment by cartag** [comment]
You don't have a grasp on how Decurion detachments work. Those units would all need to be part of the Greatpack formation, a Core choice, OR, you could take a Legendary Greatpack. If you take two of either, then you get the Howl of the Wolves benefit. 

Dammit, SuperPranx beat me to it.

**Comment by ghost** [comment]
That's not how it reads but okay.

How would you get the howls of wolves rule to show up on your list though?

**Comment by SuperPranx** [comment]
You wait for Batlescribe 2.0, wich should be able to handle similar situations, and until then you note on the side that you mustn't forget to tell your opponent about it. Make a note either way, so that you don't forget it yourself.

BTW, the rule stating that units are members of their respective formations as well as the Wolf Claw Strikeforce can only be applied if you take the necessary formations to fill the Wolf Claw Strikeforce requirements and, even then, only within those formations, separately for each. It doesn't mean that you can take 2 rune priests in a CotGW detachment and call them Wyrdstorm brotherhood.

Think of it this way. The army (Wolf Claw Strikeforce) is composed of battalions. Each soldier is a part of it's own battalion but is also a part of the army. He will get the benefits from being a member of his battalion and the benefits from being in the specified army, but he can't get be part of two separate battalions at any time. In this case you can also have battalions that aren't considered part of the main army force. Kinda like calling your banner-men to help whren battling the enemy. They're not part of your main army, but instead have their own battalion that they're a part of.

Example scenario:
The Blackmanes are going out on a mission and they take their Stormwolf, which is part of Fangs of the Tempest. Together those are two battalions that are required to form the Wolf Claw strikeforce. However, they know that they will drop their pods at different strategic locations and consider that some additional forces will be required to keep the enemy occupied. They request a CotGW detachment (the one from the supplement) from Grimnar to fight together with them, knowing that the warriors there have excellent CC skills (+WS from CotGW) and have access to some excellent relics that they can't take.

Now, The Blackmanes and Stormwolf get the benefits of the Wolf Claw Strikeforce, but the CotGW warriors don't as they're not part of that 'decurion style' detachment. Hope this clears up the confusion a bit. (and hope I didn't mess up the explanation:) )

**Comment by cartag** [comment]
Also, you will want to bring it not as separate formations, select the Force Type of SW Wolf Claw Strike Force.

![image](https://cloud.githubusercontent.com/assets/4388344/17277717/09b46852-5707-11e6-816a-f7304a4dc9f9.png)

Then it shows up under Roster Rules
![image](https://cloud.githubusercontent.com/assets/4388344/17277721/321c4b20-5707-11e6-80b8-cc26fdbe502e.png)
