### ISSUE TITLE
Codex: Chaos Space Marines (and supplements) corrections

### ISSUE THREAD

**Issue by FatalRev** [BSData/wh40k-7th-edition#2417]
1) Black Legion and Crimson Slaughter supplements are listed twice - as separate catalogues and also listed under force options within the CSM catalogue. Force options within CSM seem to be the most up to date.

2) BL and CS formations do not appear when selecting BL/CS catalogues and "Formation Detachment". Have to select CSM catalogue, formation detachment and choose force options for BL/CS to get them.

3) BL detachments missing discounts - i.e. Hounds of Abaddon do not receive free Mark of Khorne discount.

4) Chaos Space Marines are missing frag grenades.

5) Aspiring Champions default should have Boltgun + Bolt Pistol + CCW according to rulebook.

6) Chaos Lord default should have Bolt Pistol + CCW

7) Inconsistent listing of Power Armour in wargear - some units such as Chaos Lord have it specifically named, while others such as marines don't.

I know some of the last ones are little things that are the way they are to make it easier to customize loadout for characters, but I feel a more uniform layout of options would be better, and default options for all units should be as they are in the rulebook pre-customizing

Thanks for the great work you guys do making these files.

**Comment by cartag** [comment]
1) The older supplements are deprecated files. Clear your local data files and resync, they will no longer be there.

2) See 1.

3) Special rule in BS for Hounds of Abaddon says the discount will not be implemented until BS 2.0. The reason for this is having to make special versions of each unit in it with current version. Major headache. Already fixed in prep work for BS 2.0.

4) Will get this corrected. Already set properly in prep work for BS 2.0.

5-6) Short version: BS limitations.
Long version: In order to keep file size down, we can organize weapons into Entry Groups. In this case, we have an entry group for Melee and Ranged weapons. These entry groups can be referenced by all units. Chaos Lord, Bikers, Zerkers, CSM, Plague/Noise Marines, Havocs, etc. Right now, BS doesn't properly reference the default selection for each group with how it's nested. So basically we can either have a concise way of listing things, or have a separate copy of the entire weapon list in each and every unit in the file. The former is how it is now, the latter a logistical nightmare with keeping everything current in case of a codex update.

7) The only units that have it specifically named are the ones that can take different forms of armour. It's stated on Chaos Lords because they can take either Power Armour, Terminator Armour, or relic armour in some cases. The only real difference their armour makes is what their save is. On all other CSM infantry or biker units (save Cultists, Terminators, Mutilators, and Obliterators) have power armour, and a 3+ save by default.
