### ISSUE TITLE
Codex: Grey Knights

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#244]
Good evening everyone!
In a few days the Codex: Grey Knights will be officially released and it seems like 'a friend' got early access.
When are we/you planning to update the Codex?

We could start working on it and release it next Saturday, any earlier would probably upset GW too much.

Thoughts?

**Comment by amis92** [comment]
Create a local branch and publish it when you think GW won't kill you. :) You can publish it even now, let us know and maybe others will help. Still it won't be included in releases, because release is made from master.

Personally I started to feel guilty. I read somewhere that ArmyBuilder developers give GW a 1 month grace period (they don't share a new catalogue until one month after release). We could discuss something like that. However I'm just mumbling, don't worry.

Keep on!

**Comment by Kangodo** [comment]
Oh, God! Working on this Codex is soooo damn lovely.
No longer impossible combinations of weapons that make me cry, just simply: Replace X with one of the following.
It makes it so easy to make Shared Entry that you can apply everywhere.

Let's hope they keep this up with future Codices!

**Comment by Kangodo** [comment]
*Brother-Captain and Stern are done.
*Brotherhood Champion done.
*Relics, Traits and Wargear-list done and I added tons of Shared Rules and Profiles.
Now I need sleep and I will continue on this on Thursday.

I do have one question:
Some models need a NFW with a min/max of 1/1
While I also need it as a 0/1 in the Melee Weapons-entry.
I've tried to give it to a character and used a modifier to set the min at 1, but that results in the character not having it as standard.
Any idea how to solve this? Otherwise I will just make separate entries for each character and link to the profile instead of linking to the entry.

My plan is to have this done by Friday, so you can all test it out and make changes before releasing it. I'm sure that will be needed, as it's my first "new Codex" and it's not even a Codex I play myself!
Seeing as I don't type out the General rules, this might actually boost their sales :P

**Comment by peterlyberth** [comment]
Hmmm. This "Friend" of yours...
Could he be my "friend" too?

I could give you a helping hand with the dex:-)

**Comment by Kangodo** [comment]
No need :D It seems like I am done!
What would be the easiest way to share it? And by easiest I mean for people who are not that good with Github. 
We could have a release today and then add the file to our repo, and just not release till this weekend.
By doing that you can point out mistakes and edit stuff.
@amis92 and @khambatta ; Don't you think that would be the best idea?

So what did I do:
-All units with a \* before it, need to remove it before release.
-Lots of Shared rules, entries, entry-groups and profiles.
-Land Raiders
-Removed Inquisitorial stuff.
-I've left Mordrak and Draigo's Paladins in because I am not 100% sure.
-I haven't touched any FW-models and Apocalypse-stuff.
-I haven't made the Detachment/Formations.
-There are probably some Shared Entries and groups that aren't needed now, but I haven't found them yet.

**Comment by ghost** [comment]
The easiest way to share it just now is to make yourself a new repo - I don't really have a handle on how branches work.

**Comment by amis92** [comment]
With GitHub for Windows branches are easy.
1. First sync your repo. Without the new file.
2. Click on "master" right over the History column.
3. Enter name of new branch. Click "Create <name-of-branch>"

Now you have a new branch on your PC. It's kinda like a "new repo" but with history from the wh40k.

Then add the file you created, commit it (this file is now part of wh40k/branch-name). Now instead of Sync button there is Publish. Click it to upload the branch here to GitHub. Tada!

We can then change to this branch on our local repos and see what to fix, commit things etc. When the Saturday comes, we merge this branch into the "master" and do the release.

It really isn't that hard :D

If you don't have any not commited changes, changing branch is kind of like changing folder. So it's best to do it like that - change branch only if you have commited any changes or haven't made any.

Changing branch with uncommited changes may be problematic.

**Comment by Kangodo** [comment]
Thank you! That was quite easy to do.
It's named GK2014 and the above information applies to it.
Can you find any mistakes?

**Comment by amis92** [comment]
What's with that "Every model carries a Storm Bolter" ? :) Sounds weird on Draigo for example.

Also choosing which Weapon is MasterCrafted will need to be done.

Entry called "Upgrade one model to Apothecary" look really weird on Roster. It seems you haven't looked at it from Roster Editor's perspective ;D

**Comment by Kangodo** [comment]
First I had a Shared Entry called Storm Bolter.
Then it looked weird on all the Squads, so I changed it to 'Each model carries a Storm Bolter'.
I thought I changed all Characters, will double-check it again.
Checked it: Also forgot Brotherhood Champion. Fixed.

Master-crafted: Correct, but I cannot think of a 'nice way to do it'.
Perhaps two options: MC ranged weapon and MC melee weapon? That should make it clear.. Right?
And for Banner-Paladins and Apothecaries I could make a modifier that hides the Selection they cannot take.

I did look at it, but couldn't find a good solution.
Made some changes, what do you think of it now?

I'll take a look at your answer tomorrow, it's 3 at night and I need sleep.
Thank you for the tips!

**Comment by Kangodo** [comment]
The hide-modifier doesn't seem to work.
It also hides the selection on non-Apothecaries which is weird because I am 99% sure it worked yesterday.

I've also added an entry called 'Terminator Armour' because Deep Striking and Relentless is quite important and I don't want people to mix it up with all the Artificer/Iron Halo's in this army.

**Comment by Kangodo** [comment]
Update: Everything seems to be done from the Codex.
I will now take a look at the Warzone-supplements and update those entries.
After that I will do a pull request.
