### ISSUE TITLE
Bug report: Skitarii - Codex.catz

### ISSUE THREAD

**Issue by OtterlyOlive** [BSData/wh40k-7th-edition#2468]
**File:** Skitarii - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Desktop

**Dropbox:** Yes

**Description:**
Combined Arms Detachment requires 1 selection of HQ (Minimum) but no HQ are available for Skitarii.

**Comment by GenWilhelm** [comment]
Skitarii have no HQ choices in their codex, and therefore cannot take a Combined Arms Detachment. This is intentional on GWs part. Instead they have an exclusive detachment called a 'Skitarii Maniple' (AdM Skitarii Maniple in BattleScribe) that has different requirements and benefits compared to a CAD.

**Comment by OtterlyOlive** [comment]
Okay! That makes sense thanks!

Is it possible in Battlescribe to warn the user of this in someway, besides the validation error?

**Comment by GenWilhelm** [comment]
Unfortunately no such checks exist in the current version of BattleScribe.
