### ISSUE TITLE
Make use of new Report Bug feature in BattleScribe

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#251]
How do you see it? What URLs do we include and where?

**Comment by Kangodo** [comment]
That report-thing only seems to work for BS-related bugs and not our files.
But it does show the links and the name of the creators of the file.
So if we put this link ( http://battlescribedata.appspot.com/#/repo/wh40k ) in every Codex, it would direct people to the correct place to raise their issue.

http://s21.postimg.org/6hknw6mpj/Battlescribe.jpg
That's how it looks like!

I've changed it in my Codex and it looks quite instructive:
http://s3.postimg.org/6fusdc4lv/battlescribe2.jpg

That should make sure Jon gets less complaints over our files :)

**Comment by amis92** [comment]
There is another option, to first link to the README file here (link https://github.com/BSData/wh40k#warhammer-40000).

I could edit it (actually edited now) to describe difference between reporting here and anonymously through Appspot website. Also it would link as a contact more directly to us.

What do you think?

**Comment by Kangodo** [comment]
Honestly? I think many users won't read it and get lost trying to report an issue.
I personally prefer more and vague feedback over a little but precise feedback since most of the time I can figure out what people are talking about.
I wouldn't want to miss an error because the user has to do "a lot of work" to give me his feedback.

**Comment by amis92** [comment]
More and vague probably indeed _is_ better. However I think allowing them users to get some more info (the README really is quite short, isn't it?) and showing choices and results/options bound to them - is it so bad of an idea?

Maybe link to README be put in GameSystem contact details, and that quicker way of your's (directly to appspot) written into catalogues?

In all honesty, appspot may or may not be on the long run, or we may change the address. I suppose moving repository won't happen, tough. So linking to a place more stable seems like a better idea.

**Comment by Kangodo** [comment]
We could always change the links when we decide to use another place.
My favourite way would be to have a link that automatically opens a format that users can fill in. That might be too difficult to set-up though.

But I do like the new Readme, it's very informative!
All I would add is something like:

> Platform: iOS/MAC/Windows/Android
> Game-system version: 
> Codex:
> Codex-version:
> Describe the issue:
> And perhaps a line that asks people if they have tried turning it off and on again (clear folder, redownload all files).

I personally opened a thread on BolterandChainsword where people can leave feedback for Blood Angels. It has almost 2000 views, so I expect a lot of people started using Battlescribe because of it.
So that are more people using my files and probably more people paying Jon some money ;)
In my opinion the feedback on such a forum is of a much higher quality than the stuff we usually receive. Such a thing only works if you have people 'dedicated' on specific Factions.

**Comment by amis92** [comment]
It's true that such dedicated people are better reporters. It also is a good communication channel, because the anon reports are one-way. They report and most of the time won't ever check again, and additionally don't have means of easy answering.

On forums, they may be notified on answers, probably will check themselves, and have easy way to follow and communicate.

**Comment by Kangodo** [comment]
I am pretty happy with how feedback is going now, it seems to be much clearer and we seem to get less reports for user-errors.

One thing I do miss is still some good constructive feedback and a chance to communicate changes to users.
So I'm thinking of making a feedback-thread on dakkadakka (probably the biggest website) for some better communication.
I can do that on my own, so I don't really need help.

**Comment by amis92** [comment]
@Kangodo Oh yeah, good thinking. Link to it so we can see too ;)

**Comment by Kangodo** [comment]
http://www.dakkadakka.com/dakkaforum/posts/list/617215.page

**Comment by Kangodo** [comment]
Awesome, it's going well!
In the last hour I could fix quite a few errors.
I should have done this way earlier :)

**Comment by senpai514** [comment]
@Kangodo your nights in the codex's as LOW can't be valid selections for
warlords as they aren't characters. When IK are taken as your primary
detachment then you have the ability to make one a warlord as it is
specified.

**Comment by Kangodo** [comment]
From the FAQ: Alternatively, if your army contains at least one Imperial Knight and includes no characters, you can nominate an Imperial Knight to be your Warlord.

**Comment by senpai514** [comment]
I saw that but when will you ever have no characters in an army?

**Comment by Kangodo** [comment]
In Unbound-armies ;)
I do have to say that the dakka-thread has given some valuable stuff, but I should learn to copy-paste more things to here if I don't understand the issue itself.
