### ISSUE TITLE
Missing Roster Statistics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2559]
**File:** Deathwatch - Codex.catz

**BattleScribe version:** 2.00.01

**Platform:** Android

**Dropbox:** No

**Description:** I'm using the paid version and I can't view the stats and rules for my roster for Deathwatch. I can view my roster for Dust 1947 so I guess the problem is with the data for 40k or dw to be more specific. Please fix. Thanks

**Comment by flakpanda** [comment]
Seeing the rules where? Can you give a more apt description.

**Comment by GenWilhelm** [comment]
I assume Anon is talking about the statistics under the rules section when you view the roster. On desktop, it also appears to be missing in other game systems, so it may be a bug with BattleScribe rather than the data files.

![bs bug](https://cloud.githubusercontent.com/assets/22036809/19860565/16e9e714-9f81-11e6-9fce-3ee0972e5807.png)

**Comment by FarseerVeraenthis** [comment]
@Jonskichov Is this fixed yet?

**Comment by FarseerVeraenthis** [comment]
Closed, this is not a data bug.
