### ISSUE TITLE
BS 2.0 update timeline?

### ISSUE THREAD

**Issue by Glaidr** [BSData/wh40k-7th-edition#2575]
Soo... Battle Scribe 2.0 is out. Have updated on phone and windows 10 pc.

Obviously people will be working to update for new client. Just wondering about time line?

**Comment by cartag** [comment]
The data authors have had access for months at this point. Some of us have been trying to get things updated, but others haven't been able to help out yet due to real life. Beyond that, I can only speak to the files I've been working on personally, the Chaos files. They are ready.

_edit - sounded way too snarky, wasn't intended that way_

**Comment by DrTobogganMD** [comment]
@Glaidr The best way to help us speed this up is to report issues you find. Chaos varieties, Necrons, Harleys, and Space Marines have all been updated. The rest of the files saw no work during the alpha so are now playing catch up.

If you have any experience in modifying cat files with the data editor, feel free to apply for membership to help us convert the files as needed to the 2.0 format.
