### ISSUE TITLE
Grey Knights: Codex (2014) Enhancements

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#261]
When adding special weapons these replace the melee weapon and storm bolter (which is identified in the roster).  The melee weapons still appear in the unit entry when the special weapons are added.

**Comment by Kangodo** [comment]
That is correct.
You take 4 Purgators with Force Swords and Storm Bolter and 4x Psycannon from the 'Replace Storm Bolter and Melee weapon'. It's like that for every squad.

I could make everything on a 'per model' basis, like the Paladins. But I personally think that will be quite annoying in making lists and I try to put everything on the same level as much as possible.
That would be especially 'inconvenient' on mobile devices because you'd have to go four times to a sub-entry to assign the weaponry.

**Comment by Xianator** [comment]
The thing is, when you add say, 4 psycannons to the 5-man squad the roster still is showing 4 nemesis force swords
.
EG:
4x Nemesis Force Swords (80pts)
4x Psycannon (60pts) 

There is no way to remove the Force Swords from the unit as they are integral to the starting model and its points cost.

---

It also lists that "Each model carries a Storm Bolter" which as a base weapon is true, but when upgraded this is a bit misleading.  A minor thing, which looks to be common to all units.  This could be changed to read something like:  

"Each model carries a Storm Bolter as standard equipment" or
"Each model carries a Storm Bolter unless upgraded"

**Comment by Kangodo** [comment]
Correct!
That's because the Heavy Weapons are completely separate from the models itself, there is only one way to fix it and that is to make them work like Paladins where you have to open each individual model and assign it's weapons. I would advice you to take a look at the Paladins and see how you like them.
Personally I find that very confusing if you have to create every squad like this.

The 'Each model carries a Storm Bolter' is a shared entry and I could easily change that for each unit.
I tried to keep that line as short as possible, it used to be only 'Storm Bolter'.
A fix could be: "Each model carries a Storm Bolter unless it has Power Armour and is upgraded with a Special Weapon", but that would be too long.
I need a short line that tells me exactly weapon he has and that he replaces it with a Special Weapon.
That's why the Special Weapon-group starts with "Replace Storm Bolter and melee Weapon with: "

My goal was to keep things as clear and minimalistic as possible so you can quickly create a list.
Space Wolves did it better with 'Long Fangs', but I personally don't like the look of it. Especially in the View Roster-section.

**Comment by Xianator** [comment]
Clear and minimalistic is something to be applauded - but they still need to be accurate.  :)

Having a purgator with a special weapon costing 20 points plus whatever weapon they select and then requiring one less nemesis force sword model entry could do the trick.

Instead of the current text:  "Replace Storm Bolter and Melee Weapon with:" 
It could read:  "Add Purgator with <special weapon>:"

Not sure if this is feasible, but I'm just trying to help out.

**Comment by Kangodo** [comment]
@Xianator Do you have access to the unreleased files?
Because I changed the Purgation Squad and it is now more correct.
It works, it's correct and it's still easy to make a list.
One thing I would like to change is 'Storm Bolter and Nemesis Force Sword', because too much text makes my eyes hurt :)

But if you, and other people, like how Purgation works in v1 then I can change this for all PAGK.

**Comment by Xianator** [comment]
As for the Storm Bolter standard equipment line, keep in mind that the terminators can also replace them for a special weapon, and paladins too, along with the narthecium upgrade.

**Comment by Xianator** [comment]
@Kangodo Sorry, I don't think I have access to the unreleased files.  Thanks for taking the time to look into this.  Again, it's not a big problem, it is just that if left as it was it could cause confusion for players and tournament organizers.

**Comment by Kangodo** [comment]
I understand, but for Terminators it's near impossible to fix.
For PAGK I can make 8 entries: Hammer, Falchion, Halberd, Sword, Stave, Incinerator, Psilencer and Psycannon.
For Terminators I would have to make 20 entries (Sword/Bolter, Sword/Incinerator, Sword/Psilencer, Sword/Psycannon, etc etc).

I know it's not a big problem and I understand how this could be an issue.
But, and this is my own opinion, people should also read their book and create correct models.
One would have to incorrectly model his units, not read the book and not read my line with 'replace Storm Bolter and Melee weapon' before this could become an issue.

Thank you for the feedback!
I will let my change stay on the Purgation-squad and you can tell me how you like it when that is released, shouldn't take too long.

**Comment by Xianator** [comment]
Thanks again for looking into this - and thanks for having a workable roster available so soon after the codex release!

**Comment by Viper666-Qc** [comment]
I think that what he means is that for example, in a purgation squad, you can add 9X purgator with nemesis Warding Stave (225) and then replace 4 of them with psycannon (60) and the squad will still be valid with the justicar (30) at 315 pts (225 + 60 + 30).

The listing is showing 9X nemesis Warding stave and 4X psycannon (like it would be a 15 man squad). 
And you are paying for the 4 psycannons as well as 4 extra warding staves that should have been replaced....

**Comment by Viper666-Qc** [comment]
For PAGK, the way entries are handled seems fine to me except the entries could be listing Falchions/ stormbolter, sword/stormbolter, ...

For terminators/paladins , I think it's perfectly clear as it is.

**Comment by Kangodo** [comment]
You can take a Nemesis Stave and then replace it with a Psycannon, not sure why you'd want to do that though since you lose the Stave.
The only issue is that the Roster View doesn't show that you lost the Stave, even though the Roster-builder clearly says you replace your Storm Bolter and Melee weapon.

I've already applied that suggestion to Purgation-squad. You can take a look at it if you have access to the unreleased files. If I am happy with the way it looks, I could do that for all PAGK-squads.

**Comment by Viper666-Qc** [comment]
I know you can.....but in some way, it's like we made an error on the roster but it showed it was perfectly fine so you paid an extra 40pts for nothing.....maybe it could be handled by adding an entry on the top of the list named : Number of purgators (5 to 9) and the total of CC weapons + heavy weapons shouldn't be more than that number

**Comment by katfude** [comment]
The old file handled this pretty well, and yes, the strikes/purgators/interceptors/purifiers had separate entries for special weapons and knights with specific weapons, but the end result was the correct number of melee weapons listed.

As a friendly suggestion, you may want to take a peek at how the old file did it, it was pretty straightforward.

The way you've implemented paladins and terminators in your file is solid though, kudos.

**Comment by amis92** [comment]
I'm off to touch up. I'm on grey-knight-enhancements branch.

Currently rechecked profiles, made them shared and added page refs.
I want to remove Apoc formations since Grey Knights aren't Space Marines.
I'll fiddle with weapon configurations, and make units shared too, to allow possible future formations without copy-pasting.

Has anyone any objections?

**Comment by Kangodo** [comment]
Not at all! Change whatever you want if it's an improvement.
@amis92 , could you also look at the Paladin-points for the special weapons? I fixed that, but didn't commit it. It's a small change, every special weapon needs 55 more points.

**Comment by Gary-B2** [comment]
The main Apocalypse rulebook states that any Space Marine codex that has the constituent parts of an Apoc Formation can use it, like the Librarian one. The Grey Knights count as a Space Marine codex for this purpose.

If it has a landspeeder in the formation it can go.

**Comment by amis92** [comment]
@Gary-B2 Can you please give me page ref? I cannot find it.@Kangodo sure thing, I'll take care of it.

**Comment by Gary-B2** [comment]
Sure. i have a tablet version not sure how page numbers will line up.

P.44 Space Marine Strategic Assets lists what armies count for taking them.
P.133 Just before Baneblade datasheet.

Forging a Narrative box outlining how Chapters can take formations if they have all the same units. Example used is Grey Knight and Librarius.

**Comment by Kangodo** [comment]
Gary-B2 is correct, I'm looking at it now on page 78.
If the units from the Formation can be found in your Codex, you can take the Formation.

**Comment by amis92** [comment]
Good catch, thank you all very much.

**Comment by amis92** [comment]
@Kangodo could you take a look at Strike Squad on my branch? (anyone else is welcome too)

What do you think? Does it look better in roster view / roster editor?

**Comment by amis92** [comment]
I'm also thinking: Maybe change Brotherhood of psykers/Psyker entries to contain rules/rule links - this way on printed roster we see immediately which powers are available (rules in entry are written in parentheses). What do you think?

**Comment by Kangodo** [comment]
## Strike Squad-feedback!

-I think the (4-9) can be taken away.
-"Grey Knight with Nemesis Daemon hammer and Storm Bolter" could be shortened to "Storm Bolter and Nemesis Deamon hammer"
-Same applies to the Special Weapons.

Reason: Even my HTC M8 isn't big enough to show all that text.
I understand that Roster View might look better if it's all "Grey Knight with.." but it looks terrible in the Roster Editor itself.

## Terminators:

-Have you tried giving one a Storm Bolter and making it a collective-upgrade? That should work.
-They've lost their default selection, same for paladins, purifiers, Purgation and Interceptor.

Dreadnoughts, including FW, are Elites and not Heavy Support!

---

How do you mean with Brotherhood/Psykers?
I've already put all Psychic Powers in the Shared Entries. You could put a Wargear-profile on there if you want. If you call them "Sanctic: Hammerhand", etc, they will all group next to each other in Roster View.

**Comment by amis92** [comment]
Thanks! (Altough till this post I have touched only HQs and Strike Squad)

## Strike Squads/Purifiers etc.

As for the lenghty choice: That's exactly what I want to achieve. I don't like the roster when I see I've chosen some weapons. I want models in roster.

So, it's all great in roster editor as you've set up. But in the output view, the roster itself, groups aren't visible, and instead of Grey Knights I have a squad of Nemesis falchions.

I do understand what I've made is too inconvenient on mobiles. So maybe we can work out a common solution.
- For strike squad alone we could abbreviate to _GK w/ Nemesis Daemon hammer/storm bolter_, but Purifiers/Interceptors/Purgators - those don't abbreviate at all.
- Other solution is to have their weapons nested like so:
  
  > - Grey Knight (hammer)
  >   - Nemesis Daemon hammer
  >   - Storm bolter
  
  Negatives:
  - double number of lines in roster;
  - repeated word (hammer. falchions, sword etc).
  
  Positives:
  - models are bolded;
  - in roster editor it's clear enough and short.

---

## Brotherhood of Psykers

What I mean is an enhancement for the roster view. Currently _Brotherhood of Psykers_ is a parent entry of power entries. That results in Brotherhood being bold and having additional line for powers.

I propose another formats:
- Entry with rules:
  
  > - Brotherhood of Psykers [ML 1] {entry}
  >   - Hammerhand {rule}
  >   - Banishment {rule}
  
  Looks like that (in roster view):
  - Brotherhood of Psykers [ML 1] _(Hammerhand, Banishment)_
  
  Positives:
  - One-liner
  - quick-peek of roster and you know what powers they know
  
  Negatives:
  - powers aren't seen on mobile in editor
  - needs a mouse hangover on desktop
- Entry written full-out, powers as Wargear profiles:
  
  > - Brotherhood of Psykers [ML 1, Hammerhand, Banishment] {entry}
  >   - Hammerhand {profile}
  >   - Banishment {profile}
  
  Positives:
  - still one liner;
  - still quick-peekable;
  - now visible in mobile.
  
  Negatives:
  - very long (mobile!)

**Psykers with no assigned powers**

Here too is a room for enhancement. I'd do it similarly, except for specific powers to list/write disciplines they can choose from.

**Comment by Kangodo** [comment]
I fully understand, the roster view shows weapons instead of models.
Nested weapons could be a solution.
Another solution might be to have an additional entry for the models.
Then give weapons entry-group a +1 min/max for each model.
Con: You don't have the weapons per model, but per squad. But that shouldn't be a problem from SS/Purifiers since they don't have combinations.
Pro: No lengthy entries, no abbreviations.

(Brotherhood of) Psyker could have rules instead of entries.
The current issue is that rules don't give a pop-up when you mouseover, but I've already given feedback on that on uservoice.
I think your first idea would be the best.

**Comment by amis92** [comment]
Oh yes, SS/Purifiers etc are great. I don't really know how to make Terminators/Paladins better. It's such a mess with it :/

On another note: I'm not convinced by the _Type_ choices in Brother-Captain and Dreadnought entries.

I see it either as:
- Dreadnought has 0/1 entry _Venerable Dreadnought upgrade_ or
- two separate entries: Dreadnought and Venerable Dreadnought

Similarly with Brother-Captain.

It just looks kinda funny when I take Dreadnought which has Dreadnought as it's piece.

**Comment by chromecypher** [comment]
I hope you guys don't mind me adding in a little bit more feedback about the Paladin Squad in here.
Currently the minimum squad size is set to 1 Paladin, however under the new codex the minimum squad size is 3.

**Comment by Kangodo** [comment]
Yes, because you can have 1 Paladin, 1 Apothecary and 1 "Paladin with a Banner".
So the 'unit-minimum is 3' and the 'Paladin-minimum is 1'.
Selecting less that three models in that unit should give you an error.

@amis92 
I understand. But with type-entry group it's very easy/clear to put specific profiles under it.
When I make Grand Master a 0/1-Entry, it would still show the Brother-Captain profile unless we put a hide-modifier on it.

**Comment by amis92** [comment]
@Kangodo I understand too :) That's why I ask if there would be a problem with me splitting these entries, or changing to single Upgrade (and with upgrade adding hide modifiers as you suggested).

I don't want it to look like I want to change absolutely everything. I'm very glad you put a working revision up in such a short time. Just, you know, working on details. I sure as hell overdo a lot of it, but I have GKs since some time and I want my rosters beautiful ;D

**Comment by chromecypher** [comment]
Ah yep, my bad it does indeed give the error.
Thanks again for the great work you've done getting the roster up so quickly :)

**Comment by amis92** [comment]
Ok, so only Paladins/Terminators left. How do you feel about those Psychics now?

**Comment by Kangodo** [comment]
It doesn't really matter.
I made the codex because I happen to have the early scans and because I wanted to practice for when BA came out, you can change anything you like. Especially as you play them and I don't.

I am quite happy with the Strike Squad, they look good on phone/pc ánd they are clear on the Roster-View.
The powers look much better now!

**Comment by amis92** [comment]
Ok I cannot find any more errors (I know there must be some of course). I'll close this thread.

I have full consciousness that **Techmarine has no limits**, however I tried to place it and I failed, because there still are bugs in BattleScribe :)

**Comment by amis92** [comment]
Merged #282, closing this.
