### ISSUE TITLE
Codex Space wolf 2014, Missing 2 hq slot allowance 

### ISSUE THREAD

**Issue by arathas3d** [BSData/wh40k-7th-edition#268]
As per space wolf codex page 10 2,  à space wolf detachment is allowed 6 hq,  6 troop,  3 elite,  3 fast attack,  3 heavy support, 1 Lord of war, 1 fortification and if you play with imperial Knight you are allowed 1 to 3 Knight with out the allied rule in place. So if we could fix the hq choice by adding the 2 missing slot I will be a happy ocd junk.  

Thanks guy for fixing the black template issue I reported.

**Comment by Kangodo** [comment]
Did you take a Combined Arms Detachment as Force-type?
Because I selected the Wolves Unleashed Detachment and I can take 6 HQ's without errors.
Imperial Knights are another Detachment, so you would have to add an additional Imperial Knight-Detachment.

When making a new roster, don't just look at the Codex. Also look at the Force Type!

**Comment by arathas3d** [comment]
I did not see that specific one,  I tried combine arms and basic space wolf
detachment

**Comment by Kangodo** [comment]
Try again ;) As you can see in that image, it's perfectly legal. It doesn't give me any errors.
http://s17.postimg.org/pqugvxfxb/Space_Wolves.jpg

A Combined Arms Detachment has a maximum of 2 HQ's, even with Space Wolves.
Wolves Unleashed has a max of 6 HQ's.
Champions of Fenris has a max of 4 HQ's.

All seems to work fine on my pc, so I will close this issue.
