### ISSUE TITLE
BS2.0 revision realignment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2698]
@amis92 in [closing comment](https://github.com/BSData/wh40k/issues/2698#issuecomment-259205257):
>Using my godly admin powers, I've single-handedly reset these revisions. Hopefully I've not hurt any feelings, if so, please accept my apologies.
>Case is closed. For future reference, please make any new catalogues start with revision 2000, and the same when any catalogue is upgraded to 2.0 format.
----
**OP**

I notice that the revision number for the 40k gst has reverted back to 1 (well, 4 now but who's counting?)

Have you also changed the ID?

Remember that BattleScribe uses the revision no. to determine whether it needs to download an updated file.

If you've reverted the revision number back, then users who have the old version 60 file will not get the new one when they update (since revision 1 is less than revision 60). BattleScribe thinks they already have a newer one.

Needless to say this could cause problems...

You'll need to change the revision number to something higher than what the old file was. This applies to catalogue files too.

**Comment by Jonskichov** [comment]
Damnit I was signed in with the wrong account...

**Comment by Thairne** [comment]
Well yep. A few guys decided that, since there is no minor/major revisioning within BS, that resetting to v1 was the way to go to mark the BS 2.0 milestone.
Philosophical approach.
On hindsight increasing the v to 2xx would have been the better option (and could imo still be done).
I might just do that with my files the next time and go up to v200.

**Comment by cartag** [comment]
Going to 2XX wouldn't have been possible for some files, CSM was already on 207. The reason it was done was so those on 1.15 who didn't upgrade wouldn't lose functionality and could stay using it, without updates, if they accidentally selected to upgrade data, rather than render their install of 1.15 useless until they can get the other version installed.

**Comment by Thairne** [comment]
That's a bit backwards imo.
To support the minority of users, cause a none-miniscule inconvenience and source of reports for the majority?
What was done is done anyway.

**Comment by cartag** [comment]
Duly noted. Thanks for chipping in trying to get things ready and joining in on the discussion then. Truly appreciated.

**Comment by amis92** [comment]
@Jonskichov are you still suggesting to change that back to increase revisions to say 2xxx, or is that a rather rhetorical question of historical notion?

**Comment by Jonskichov** [comment]
So I understand the philosophical side of things: we all like nice clean version numbers and whatnot :)

It's up to you want you want to do, but here's some clarification.

BattleScribe identifies unique data files (regardless of filename) based on their unique ID.

When updating data files, BattleScribe uses the unique ID of the file to be downloaded to check to see if it has an existing file with that ID. If not, we're all good, just download it.

If there _is_ an existing file, the revision number is used to check whether the file to be downloaded is newer than the existing one - i.e. it will download the file **only if** the revision number of the new file is higher than that of the existing file.

This is done on a file-by-file basis, so the revision of one file has no bearing on the revision of any other files. The revision of a gst has no bearing on whether or not a cat is downloaded or not. It's all the revision number.

So now we have a case where people who have the old 40k gst (rev 60 or so) will not get the new one upon data update because the unique ID is the same but it's revision number is lower. Remember that many people will already have downloaded the "old" files using BS2, so that data is in the wild - it can't be taken back!.

If you want to let people continue to use the existing repo URL and transparently update their data to new 2.0 format, you will need to continue the file revision numbers from where you left off.

This will of course cut off 1.15 people, at least if they use the current 40k repo URL.

The only real way to offer two different sets of data (2.0 and 1.x) would be to have two repos, with their own URLs, which contain gst files with different IDs.

**Comment by alphalas** [comment]
I think the main strike against that last option was that the consensus was it is horribly impractical to have 2 concurrent repos running
- Jon[K]

**Comment by amis92** [comment]
@Jonskichov could you give us some numbers to work with, ie. what percentage of people have upgraded to 2.0 already? Is it still worth the effort tu increase these revisions.

We don't aim to support 1.15. Those who want may download the .bsr as linked from Notice in README. Although it wouldn't hurt to have the README be more exposed.

The real solution, in long-term meaning, is to add semantic versioning to datafile revisions. Major is the edition/BS new version, minor is game system version, two latter are for catalogues, or something similar.

**Comment by Jonskichov** [comment]
@amis92 

1) Not _too_ much effort ;) Also (for example) on Android we're over 15,000 soo...
2) "We don't aim to support 1.15" - might be best to just bite the bullet and ignore the 1.15 people then
3) Perhaps I need to add a "human readable" version field in addition to the revision number?

**Comment by amis92** [comment]
1) It's over 40 catalogues, so it's a bit. I have no idea how much/how not much is 15k :)

2) Well, ignoring is too harsh, especially now that BS2.0 still has _some_ unpolished surface ;)

3) God forbid xD That'll only increase Chaos. _Or is that what you want `<looks at armies you play on tabletop/>`_

**Comment by DrTobogganMD** [comment]
Major/Minor versioning is preferred. It's the standard way of doing things.

If we want to move files to a standard version number to start them off for 2.0 - perhaps v200 is the way to go, for everything. Chaos will simply need to start at v210 - but regardless, v2xx can be our BS 2.0 starting point. 

If we ever get word of Jon working on BS 3.0 and we don't have major/minor versioning at that point. We'll deal with it then.

**Comment by Jonskichov** [comment]
1) In terms of absolute numbers, 15k is a lot of people! And a lot of potential erroneous big reports for all of us...

2) Yeah this could have gone better... But I guess it was never going to be easy. If you did fork and have a second repo for the old data, there's no obligation for you guys to support it. You could basically leave it to rot... The tools are there if others wanted to take up the slack. 

I doubt many will find the bsr you linked on GitHub, even if it's more prominent. Not many will get to GitHub at all I'd imagine.

3) At the end of the day, the revision number serves a particular purpose, and subverting that purpose for the sake of pretty version numbers leads to trouble.

An easy option would be just to put a human-readable version no. in the data file name.

I can add an (optional) version field if you guys want it

**Comment by amis92** [comment]
https://github.com/BSData/wh40k/releases/tag/v5.0.11

This release will help people who upgrade BS to v2.0, so that their data will automatically get updated. At first we reset the revisions to "mark a moment", but it backfired in a huge amount of complaints, so there it goes.

All the people staying (for now) with 1.15 - please use the .bsr we prepared as described in [Notice](https://github.com/BSData/wh40k#important).

---

Using my godly admin powers, I've single-handedly reset these revisions. Hopefully I've not hurt any feelings, if so, please accept my apologies.

Case is closed. For future reference, please make any new catalogues start with revision 2000, and the same when any catalogue is upgraded to 2.0 format.

**Comment by Jonskichov** [comment]
All hail the great @amis92!
