### ISSUE TITLE
Space Marines Codex (2016) Missing artificer armour-option for captain.

### ISSUE THREAD

**Issue by SuperMegaScience** [BSData/wh40k-7th-edition#2887]
The Space Marine Captain is missing the option to add artificier armour for 20p, there's only the option to upgrade from power-armour to Terminator-armour.

**Comment by FarseerVeraenthis** [comment]
Artificer Armour is there, it is just in a slightly different place from where you've looked...
I'm on Android; Open "Captain", tap the section where it says "Name: Captain", then tap where it says "Armour: Power Armour" (**Note**: Not the Radio button, the words), and Artificer Armour is the first on the list.
This is because Artificer Armour is a Power Armour Upgrade, whereas Terminator Armour REPLACES Power Armour.
File Version 2008.
