### ISSUE TITLE
Space Wolves codex - various issues

### ISSUE THREAD

**Issue by Bparks1983** [BSData/wh40k-7th-edition#2971]
Ulrik the Slayer currently has the option to take a plasma pistol for 15 points, it should automatically be included in his profile at no cost (145 points total for the model). 

When adding or removing Storm Shields to a model of Thunderwolf Cavalry, all models in the unit (except the pack leader) are having their weapons changed together, each model should be allowed to have independent war gear. 

Kingsguard as a formation benefit (+1 WS to all Wolf Guard/Terminators and Thunderwolf Cavalry) is not being applied to the unit profile, despite the rule summary saying it is.

**Comment by FarseerVeraenthis** [comment]
This CAT has been worked on a lot recently, please state your file version. 
Otherwise, have a task list to keep track of things;

- [x] Ulrik the Slayer should have Plasma Pistol included in points cost

- [x] Thunderwolf Cavalry should be able to select wargear individually

- [x] Kingsguard formation buff not reflected in unit profiles
