### ISSUE TITLE
Grey Knights: weapons point costs not added in pick-lists

### ISSUE THREAD

**Issue by Xianator** [BSData/wh40k-7th-edition#299]
When upgrading weapons the points costs are not displayed correctly in the roster pick-lists.

This is happening for melee and special weapons in Terminator Squad, Strike Squad, Purifier Squad, Interceptor squad, and Purgation Squad.  

Points appear to be added correctly within the roster itself, so roster integrity appears to be okay - but best to recheck the numbers when unit testing.

**Comment by amis92** [comment]
Well it seems BattleScribe doesn't count costs of nested entries. See, for example Interceptor with warding stave costs 24 + 5 for stave. It's made like so:

> Interceptor (cost: 24)
> 
> > Storm bolter (cost: 0)
> > Nemesis warding stave (cost: 5)

So I have two options:
1. I leave it as is, which means:
- Points in options panel are incorrectly shown
- however in any other view it's correctly shown (upgraded stave has it's own cost of 5 pts)
  1. Change it so that models costs the sum already, then:
- points in options panel are correct
- in any other view upgraded weapon has no cost.

I honestly don't know which is better. No problem changing to second option for me.

**Comment by Xianator** [comment]
When building an army list, the points in the pick lists should accurately reflect the point cost of the unit.  It seems integral to how one would select units and upgrades for their force.   I'm not quite sure how the pick lists with incorrect points would be helpful to anyone putting an army together.  :/

**Comment by Kangodo** [comment]
Option 2 would be the best.
Because at the moment it's impossible to see how much each upgrade is, you would need to pick it and then you see it.
I understand the idea, but at the moment it's really weird to build a list.

**Comment by amis92** [comment]
Hm, yes that is true. I'll change it tomorrow morning.

**Comment by amis92** [comment]
Actually I changed my mind. I reported it as a bug to BattleScribe (upvote if you please): http://battlescribe.uservoice.com/forums/55066-general/suggestions/6379039-bug-point-cost-not-added-for-nested-entries

I'll wait for Jon's reply and if it's negative I'll change as discussed earlier.

**Comment by amis92** [comment]
Jon said it'll be done in upcoming v1.14.07, so I'll close it now.
