### ISSUE TITLE
Eldar Apocalypse formations

### ISSUE THREAD

**Issue by Amdraz** [BSData/wh40k-7th-edition#3015]
Hi there, love the data otherwise but the Eldar Apocalypse formations seem to have disappeared in the most recent update?

**Comment by FarseerVeraenthis** [comment]
I think I know what has happen, they might have been erroneously moved (not by me or anything like that...) when I was working on the file previously...

Please could you let me know which book there formations you're looking for is from so that I can find them and put them back in the right place... :smile:

**Comment by Owlsbane** [comment]
I'm on version 2010 and I can see the Apocalypse Formations under Formation Detachments.
Things like Crystal Sons of Asuryan from Valedor and Sunstorm Squadron from Warhammer 40k Apocalypse, right?
Windows 10, BS v2.00.05

**Comment by Amdraz** [comment]
Hi guys,

Yea it seems they are all available under Formation Detachments. Those are the right books too but they aren't available in the apocalypse battle formations tab anymore?

**Comment by FarseerVeraenthis** [comment]
Righto, this actually sounds like something has been missed in the upgrade to BS V2.0... I'll still have a look but I've not had time so far... Cheers for the updates so far though :smile:
