### ISSUE TITLE
Chaos Space Marines - Data Error Message

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3103]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.16

**Platform:** Android

**Dropbox:** No

**Description:** When opening a viable list, a screen pops up saying something is wrong with the data and some options aren't available, though when I continue nothing looks to be wrong.

**Comment by cartag** [comment]
If the roster existed before BS2 you'll get that message. Are you able to create a new list, exit, then view it again?

**Comment by FarseerVeraenthis** [comment]
I think this error pops up when you have a selection that has changed since you last opened the list. 
For example, if you select a Lord and then equip him with a power sword and "big-fat-gun-1", save the list, and then the options are moved or changed in the CAT, when you next open the list you might find the Lord no longer has a power sword and "big-fat-gun-1" - so you need to re-select them, and this error is letting you know. 
Have a thorough look through and I imagine you'll find some options/choices either missing or moved.
