### ISSUE TITLE
Chaos Daemons 40k request

### ISSUE THREAD

**Issue by Glyss** [BSData/wh40k-7th-edition#313]
Could I please request the addition of the Blight Drone - Fast Attack unit to the Daemons repository? 

Current details are in 2013 Imperial Armour - Apocalypse. 

Also, is there any chance of having the Chaos Daemons Gargantuan Monstrous Creatures from the same 2013 IA-A added as Lords of War?

Thanks kindly in advance.

**Comment by Glyss** [comment]
I'm happy provide the statlines and the details of special rules for each daemon if that would be of any help.

**Comment by senpai514** [comment]
I have a pdf of the book and it will prob be me that does the update unless someone else wants it. Maybe over the weekend if time permits

**Comment by Glyss** [comment]
Hey you amazing folks, 

When I  update my repository the additions of the Blight Drones and the various LoW are not showing up in the roster.

Just wondering if I was missing anything. 

Thanks again.

**Comment by amis92** [comment]
@Glyss if you're not using github for your repositiry (which you most probably don't), then the changes we make here are available to "public" only after a new _release_ is done. Well, it seems noone done it in last few days.

**Comment by Glyss** [comment]
Hey Amis, cheers for the reply.

Im using the repository as hosted on appspot. I thought that would have been the github repository as I made a Dark Eldar enhancement request (Uriens effect on Grots) a couple of weeks ago which I believe was actually actioned by you. Immediately after completion and updating my source data, the changes were present in BaatleScribe. Hence my confusion that the changes dont reflect this time.

Can you point me to a faq to ensure I am using the proper Github repository please?

Cheers again for your time.

**Comment by Glyss** [comment]
Disregard, changes have taken effect. Yesterday I was stuck on Daemons v22, it's allowing the update to v23 now.

**Comment by amis92** [comment]
@Glyss To make it clear:

Here on GitHub we communicate, we have the _main_ revision of files, their history and an issue system. We work here. The fruits of our work are then _released_ and a web application hosted by us on AppSpot downloads this new _revision_. Then, all the other people (not maintainers) can download them, and the update system is triggered in BattleScribe.

So the appspot page and service is a frontend for our backend here on GitHub.

Yesterday when I saw your post I checked and indeed, last release was made 10 days ago, so I created new one - and that's why you your BattleScribe downloaded the update.

I hope you now understand better :) Cheers!
