### ISSUE TITLE
Problem with downloading data

### ISSUE THREAD

**Issue by shadoestar** [BSData/wh40k-7th-edition#314]
Hello..Im new to this site and such..was told to be asked to be added so I can obtain data files for Battlescribe

Shadeostar

**Comment by Kangodo** [comment]
You don't need to!

http://battlescribedata.appspot.com/repos/wh40k/index.bsi
Copy this link into the data from Battlescribe, which you downloaded from battlescribe.net
Anyone can do this, you don't have to be a member.

**Comment by shadoestar** [comment]
I tried to put that into bs but it wouldnt download any data..what am i doing wrong? I used the manage data button to do it..

Sent from Yahoo Mail on Android

**Comment by amis92** [comment]
I know this may be dumb question, but did you use the button named `Refresh` or `Check for updates` (forgot how it's called)?

**Comment by shadoestar** [comment]
yep..will try again 

On Tuesday, September 2, 2014 9:58 AM, Amadeusz Sadowski notifications@github.com wrote:

I know this may be dumb question, but did you use the button named Refresh or Check for updates (forgot how it's called)?

**Comment by Sigmaril** [comment]
Hi
Please remove me from the list again (wh40k). You guys spam WAY too much.
regards,Claus

**Comment by amis92** [comment]
@Sigmaril : We can't remove you from notifications, please do it yourself. It's easy:
1. On webpage, click the cog symbol in upper right. You're in settings now.
2. In left menu choose `Notification center`.
3. There uncheck `Email` in second row (**Watching**). Better leave check on **Participating**, because that's the way we "call" someone to attention directly.

From now on you won't receive emails about _any_ updates except when someone directly `@mentions` you. :) Cheers!
