### ISSUE TITLE
Tyranids - Genestealer Brood is unwieldy.

### ISSUE THREAD

**Issue by samwcoulter** [BSData/wh40k-7th-edition#3164]
When adding a genestealer brood you have to add individual genestealers, and then select adrenal glands/rending claws/toxin sacs for each genestealer individually.

It would be much nicer if there was a simple counter for number of genestealers, and number of the above upgrades.

**Comment by Randobar** [comment]
its a general bug that there is a individuall selection for glands and sacs, just the talons can be added one by one

**Comment by Randobar** [comment]
The data seems fine.
Same settings for Genstealer as they are for rippers/gargoyles and other. 

Just the BattleScribe display varries, maybe because of the additional Broodlord.

**Comment by GenWilhelm** [comment]
BattleScribe breaks Genestealers up into individual selections because they have a non-collective entry (Scything Talons), whereas Rippers and Gargoyles only have collective entries.

If you move the Scything Talons from the model level to the squad level (and perhaps rename it so it's clear what it is) then the Genestealers collect into a single selection, the same as Rippers and Gargoyles.

Of course, it's up to the catalogue's keeper whether or not this change is worth the disruption.

**Comment by Randobar** [comment]
Thanks for feedback. @GenWilhelm 
Moved the Talons . Will look a lot better this way.
