### ISSUE TITLE
CSM - Tzaangor Cost

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k-7th-edition#3188]
Android
Version 2017. CSM v2011

In a CAD Tzaangors cost double their actual points cost. I.e.

**Comment by radionausea** [comment]
I.e to increase a unit from 10 to 11 tzaangors costs 14 points rather than 7.

**Comment by GenWilhelm** [comment]
It appears that Tzaangor units are behaving collectively. This means if you change the number of Tzaangors in one unit, all other units receive the same change. It therefore costs 7 pts per unit to add another Tzaangor, since you are adding one to each unit.

I am not familiar with Tzaangors, so I have no idea if this behaviour is intended, I will check when I have some free time later tonight.

**Comment by cartag** [comment]
I'll get to it tonight.
