### ISSUE TITLE
Adepta Sororitas - C:IA being difficult?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3222]
**File:** Adepta Sororitas.catz

**BattleScribe version:** 2.00.22

**Platform:** Android

**Dropbox:** No

**Description:** It won't let me use the Adepta Sororitas codex only the Imperial agents, it says in conjunction with, not take over. And the command squad can't have a dedicated transport with it being included as a part of the unit.

**Comment by alphalas** [comment]
For the second half of your issue update data - for the first part, could you elaborate?

**Comment by Gnofry** [comment]
I believe the issue that the person is talking about is that Imperial Agents is intended to be used in addition to, not instead of Codex: Adeptus Sororitas. So options from both sources should be available. This is based on the statements within the book itself, and that within Gathering Storm the Castellans of the Imperium detachment lists the Sisters of Battle units as being able to be drawn from both Imperial Agents and Codex: Adeptus Sororitas.

![image](https://cloud.githubusercontent.com/assets/17345182/21999730/82515dce-dc09-11e6-9bc3-71adb6cc7361.png)

**Comment by alphalas** [comment]
They are all available- I don't understand what's the issue
