### ISSUE TITLE
Deathwatch Vanguard Heavy Thunder Hammer

### ISSUE THREAD

**Issue by tekk45** [BSData/wh40k-7th-edition#3223]
When selecting the heavy thunder hammer on a Vanguard Veteran, the validation still says you must choose two from the list. If you add anything from the list it says you have too many selections.
![2017-01-12 07_35_58-roster editor v2 00 10 - deathwatch - full black spear strike force warhammer](https://cloud.githubusercontent.com/assets/25079656/21890065/e95aeeea-d899-11e6-86f2-f0876e6e0e39.png)
![2017-01-12 07_37_19-roster editor v2 00 10 - deathwatch - full black spear strike force warhammer](https://cloud.githubusercontent.com/assets/25079656/21890091/09e57f72-d89a-11e6-8906-ab4aaa00e25c.png)

**Comment by tekk45** [comment]
This is on BS v2.00.10 and data Jan 10, 2017

**Comment by FarseerVeraenthis** [comment]
You're right, although this has been fixed in the version of the data that I literally just pushed a release for...
Please be aware that this will take a few hours to update through Appspot, and it is a big change to the structure of the CAT, so you will likely need to rebuild your army list from scratch once the data updates.
Having said that, building Deathwatch army lists will be much easier with the new CAT so it's not all bad :smile:
