### ISSUE TITLE
Space Marines - Performance Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3228]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** No

**Description:** When adding a Space Marine: Codex (2015) v2014 Combined arms detachment and Space Marine: Codex (2015) v2014 formation detachment to the same roster, the program freezes when pressing OK. Have to end the process to terminate the program.

**Comment by FarseerVeraenthis** [comment]
Did you add them individually, loading the roster in between, or did you try to add them both at the same time...??
I have noticed that this CAT is starting to get slow to load, so it is possible that it needs a prune... It is huge, and there are a lot of options, especially due to the combination of Chapter Tactics, Angels of Death Relics, and the vast amount of Forgeworld stuff available for Space Marines - the resulting show/hide conditions are epic!!
Please try again; Add them separately, load the roster once you've added the first one, and report back if that fixes the problem or not...

**Comment by Moelholm81** [comment]
I have now tried:

1: New roster, add Space Marine: Codex (2015) v2014 Combined arms detachment, press ok - it loads fine.

2: Edit forces, add Space Marine: Codex (2015) v2014 formation detachment - nothing happens, but it does not freeze, but takes some time to process. After a few secs I can press OK and the formation detachtment does not appear in the Available entries on the left and I cannot add entries in the CAD. When pressing Edit forces again, the both detachtments appear.
Same thing happens when adding the formation detachtment first and then the CAD.

**Comment by FarseerVeraenthis** [comment]
Thanks for the update :+1:
There might be an error somewhere in the data that is causing it to load slowly, or it could be due to the size of the file...
Neither is good news.
If they work individually I suggest building the lists separately for the time being, I'll have a look but I don't know when I'll have time to really do anything to fix it...

**Comment by Moelholm81** [comment]
No worries :)

Building seperately is my current workaround, just wanted to let you guys know of the bug :)

**Comment by Gnofry** [comment]
I am also experiencing the same issue, usually when attempting to add a third force to the roster.

**Comment by alphalas** [comment]
Purge and re download data - might be a local memory issue.

**Comment by Moelholm81** [comment]
@alphalas - tried, did not work. Removed data from program and stored folder and re-added.

**Comment by alphalas** [comment]
Maybe uninstall and reinstall BattleScribe- I couldn't replicate your issues on pc or iOS. If that doesn't solve it it might be a memory issue with your device, not BS

**Comment by Moelholm81** [comment]
Tried that, no luck. Also updated java to version 8 update 121 (build 1.8.0_121-b13).

I have replicated the problem on three seperate Windows 10 PCs now, one of which have never had battlescribe installed before.

I could, however, not reproduce the problem on a clean Battlescribe install on an Android device - no problem there.

**Comment by alphalas** [comment]
That tells me that it's probably not an issue with the data – submit a bug report for BattleScribe itself

**Comment by Moelholm81** [comment]
Ok, will do
