### ISSUE TITLE
FW Inquisitors need updating

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#323]
Hi there
Noticed Cypher was fixed. Thanks 
The next item I've noticed is on the Hector Rex Retinue
Retinue: As an Inquisitor, Hector Rex allows you to include a unit of 3-12 Henchmen in your army as an Elites choice that does not take up a force allocation slot, chosen from the options shown in the Grey Knights Codex  (see page 90). 

https://docs.google.com/viewer?url=http://www.forgeworld.co.uk/Downloads/Product/PDF/c/Characters.pdf

If I read this correctly that means he should have the same elite choices option as a warband with out being an elite choice but unlike Lok the points are not included in his own.

**Comment by senpai514** [comment]
The way he reads he is now in need of a new update as his datasheet is now out of date and part invalid

Technically he cant even be used in a Codex: Inquisition army as his datasheet only designates him as an HQ for Grey Knights. The same applies to Solomon Lok.

Both characters are in desperate need of updates in order to use them again. I suggest hiding them in catalogue until they are fixed and legal for use in a Inquisition Army

**Comment by senpai514** [comment]
I am hiding these 2 characters until FW releases their 7th edition updates which in an email from them received today will be seen in approx 2 weeks they are hoping

**Comment by Viper666-Qc** [comment]
I got a pic of the updated Solomon Lok rules with major Durra (IA4V2, 7th ed). I can't see a way to send it in a Private Message and I don't want to post the link for Copyright Violations so I would need an email address (or you can simply try 1406307332451.jpg in google images I guest)

**Comment by Kangodo** [comment]
I'll add him today or tomorrow

**Comment by Viper666-Qc** [comment]
Then again, the new Solomon Lok will probably FAQ'ed again in the future to be an exclusive HQ choice for codex:inquisition (in IA4V2, released before the new Grey Knights codex, he was available as an HQ choice for both codice since the inquisiton was still part of GK). Maybe it would be better not to add him to the New Grey Knights....what you think?

**Comment by Kangodo** [comment]
Was unable to decently add them, because that picture doesn't give me all the rules :(
I am on the look-out 24/7.

**Comment by Viper666-Qc** [comment]
http://www.dakkadakka.com/dakkaforum/posts/list/30/574064.page?userfilterid=9675

(left page is the good one, right one is from older book)
Seems complete to me....

**Comment by Kangodo** [comment]
Geno-surgical enhancement and Greater Chainsword?
I don't really know what they do, so I can't really finish the unit.

**Comment by althornin** [comment]
Geno-surgical enhancement is a stat bonus already included in the unit profile and cost. So there isn't anything needed there. And it's a heavy chainsword. S+2,AP 5,  two handed

**Comment by Kangodo** [comment]
These were added a long time ago :+1:
