### ISSUE TITLE
Chaos Space Marines - Force Selection Improvement Suggestion

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3237]
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The death guard plague colony and the emperors children exclusive formations don't appear when you choose each legions respective massive formation

**Comment by z258** [comment]
Never mind, I found the solution from an earlier closed ticket.

Never the less I suggest that changes should be made so that you don't have to go to force options in the uncategorised section and pick the legion, aka death guard for this instance when you are picking the death guard vectorium. Plague colony should be underneath core choice automatically when the death guard vectorium is chosen. Apart from emperors children, the rest of 7 legions have their unique core choices like the world eaters with the maelstrom of gore as an automatic core choice for the butcherhorde detachment without having going to uncategorised section and needing to pick world eaters under force options

**Comment by amis92** [comment]
@alphalas when closing something please give any explanation why it's closed. Expected implementation too complicated? Better idea? No reason? :) I guess it might've been discussed on Gitter, but there is no reference left here.
