### ISSUE TITLE
Orks rules errors: Boyz Nob cost

### ISSUE THREAD

**Issue by bitofall** [BSData/wh40k-7th-edition#333]
The current Orkz codex lists the Nob upgrade as 16pts when it costs 10, also the warboss can only take one gift of gork and mork but the limit only seems to be on one of any item per army.

**Comment by ghost** [comment]
An Ork Boy is 6pts, the upgrade is 10pts, so a Boss Nob would be 16pts - I'm guessing you're talking about the Boyz mob, but the principle is the same for whichever unit.

I've got the ebook, so I can't give you the page number, but if you look at the Orks Wargear List that comes before the individual unit description, it tells you a model can only have one Gift. It caught me out at first, too, since they don't repeat that in the appendix.

**Comment by bitofall** [comment]
the way you say works but is counter intuitive, you don't choose the amount of boys you want, take one off then add a nob when writing a list, you take the amount of boys you want and take the 10pt upgrade on one of them, so it makes a 30 boy squad cost 10pts too many when done the current way.
you are definitely right about the Gift though =)
Date: Tue, 9 Sep 2014 14:17:16 -0700

**Comment by ghost** [comment]
Eh? You take a boss nob and the boyz you want, eg 9+1, simples. That way it looks the same on the roster as squads that have a compulsory sgt/nob/exarch, instead of being hidden away like a random bit of equipment.
