### ISSUE TITLE
Space Marines - Issue with multiple forces

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3332]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** No

**Description:** The Roster will not allow me to add multiple forces to my army, for example I am trying to add a combined arms detachment and a formation detachment, however when I go to press "OK" nothing happens.

**Comment by pretzalcohuatl** [comment]
I'm not sure it is a battlescribe bug per se; you can have multiple detachments from a single catalogue (e.g., Astra Militarum - Codex.catz doesn't have that issue)

Space Marines is a bit bloated tho

**Comment by FarseerVeraenthis** [comment]
@whiskeyjuvenile if you'd like to discuss the SM CAT, feel free to join us on Gitter: https://gitter.im/BSData/wh40k

**Comment by DrTobogganMD** [comment]
That is how BattleScribe Behaves with formations, we cannot change that. 

Calling sm bloated is the understatement of the year. I've condensed it as much as Possible given the current implementation of BattleScribe unfortunately.

**Comment by pretzalcohuatl** [comment]
well I had the battle demi-company in one entry with free transports once upon a time that got lost with the transition to 2.0 I guess

besides I don't think "this is how battlescribe behaves with formations" is correct: it works with other catalogues, just not Space Marines, which leads me to suspect the issue is with the catalogue specifically, even if it's a battlescribe bug, and we've fixed those in the past

**Comment by pretzalcohuatl** [comment]
flipping through and wonder if it's the modifier Ancestor Instance Of Formation having a shared filter?

**Comment by FarseerVeraenthis** [comment]
@whiskeyjuvenile I really appreciate your help, but if you're not going to join the conversation with the rest of the data authors on Gitter, please branch the Repo and work on that. 
Working directly on the master can cause conflicts, for example, if you decide to pick up an issue when someone else is working on the same file...

To stay on topic regarding the "Shared" checkbox, please refer to #2880 . 

Otherwise, the SM CAT is undeniably large, but unless you fancy a complete re-write (NOT on the master branch!!) there is not much that can be done. Only a very few people seem to have trouble with it, and re-writing it will be a massive job, not least because you'd have to familiarise yourself with all the IA books, along with the SM Codex and all the supplements... If you really want to give it a whirl, speak to @Kohato for advice since he performed the last major update.
