### ISSUE TITLE
Cult Mech Servitors

### ISSUE THREAD

**Issue by ChthonicKnight** [BSData/wh40k-7th-edition#3353]
-The servitors from C:IA are not showing up in War Convo. as elite choices. Narrowed it down and found that the link Selection Entries>Link to: Servitors (Entry) has Elites selected as the category, but there are 2 Elite options to pick from (Looks like the wrong one is selected).
-Also I see that it had a parent limit of 1. Not 100% sure what this affects but you should be able to take 4 units in a Battle Congregation per the rules.
-Also while your in there may have to make an amendment for the wargear options to be free in War Convo for Servitors.

**Comment by Thairne** [comment]
Looks simple, but is not uncomplicated.
Servitors needs 2 entries, one for the "regular" elites and one for the Enginseer Congregation. Otherwise you could select Cult Mech Elites in the Enginseer Congregation which you cannot do.

That is also the cause why only 1 set is allowed in one and not the other. That is however an older version, your file is not up to date.

The Servitors are in the War Convo, so... out of date data?

![grafik](https://cloud.githubusercontent.com/assets/8590840/22528392/5c723750-e8d3-11e6-83c6-093a206e52ba.png)

True about the wargear options though.

**Comment by Thairne** [comment]
Forgot the "closes". Ah well.
