### ISSUE TITLE
Tau Empire : bonding knife conditions and scalability. 

### ISSUE THREAD

**Issue by Captain-Joystick** [BSData/wh40k-7th-edition#3412]
A couple of quality of life issues when building Tau armies, wondering how feasible they are to address. Encountered these on mobile. 

-When adding or removing models from a unit with bonding knife ritual the price of bonding knife ritual (1ppm) does not update unless the user deselect bonding knife ritual and reselects it. 

-Farsight Enclaves require BKR on all units that can take it, is it possible to enable it by default on units added to an Enclaves detachment?

**Comment by DrTobogganMD** [comment]
1) That is a quirk of BS, if you increment price based on number of entries, the cost will increase on the selector, but won't take effect until you remove/re-add as you've already added it for the initial cost.

2) No it is not, the most that can be done is to set the min to 1 when a farsight detachment (which is what is done) but that won't select it automatically.

In short - both are no's due to how BS works.  In theory both are possible, in practice, not so much :(
