### ISSUE TITLE
Land Raider Achilles and Land Raider Ares

### ISSUE THREAD

**Issue by lhavoc1** [BSData/wh40k-7th-edition#3458]
Can we include Land Raider Achilles (Forge World) and the Land Raider Ares (White Dwarf) in the Warhammer 40,000 catz?

**Comment by DrTobogganMD** [comment]
Why? They are a part of the individual cat files they are allowed in.

**Comment by lhavoc1** [comment]
No they are not. When you check Forge World options in Space Marines the Land Raider Achilles does not show up at all. And the Land Raider Ares is a White Dwarf option for a Dark Angels army.

**Comment by DrTobogganMD** [comment]
![image](https://cloud.githubusercontent.com/assets/16939161/23242751/506d9f30-f940-11e6-883d-98a5d18fda96.png)

Achilles is indeed in the SM cat file.

What White Dwarf issue is Ares in, the only one I can find mentioning Ares is from 10 years ago.

**Comment by lhavoc1** [comment]
That’s the one! It is still a viable option for a Dark Angels and Space Marine Army

**Comment by DrTobogganMD** [comment]
You mean the one from the now defunct Apoc book from 2007? The one that has no Hull points?

**Comment by lhavoc1** [comment]
The Hull Points would be the same as any Land Raider.

**Comment by DrTobogganMD** [comment]
Source on that?

**Comment by lhavoc1** [comment]
Look at the stats for the Land Raider LRC and LRR.

**Comment by DrTobogganMD** [comment]
What does the stats on two other models have to do with the Land Raider Ares?

**Comment by lhavoc1** [comment]
Because there is no notation of an Armour upgrade. It is just a weaponry change.

**Comment by alphalas** [comment]
It's more then that - it looses its transcap and other features of a regular LR. It's not a updated entry and is out of date

**Comment by DrTobogganMD** [comment]
They are separate model datasheets that have been updated for the current edition of Warhammer 40k.

The Land Raider Ares has not been updated in the 10 years that the datasheet has been available and has a stat block that is incompatible with the game as it is currently played.  If you want to discuss this further with the authors - please join us on Gitter: https://gitter.im/BSData/wh40k

**Comment by lhavoc1** [comment]
Does not mean it is not relevant. White Dwarf is canon as it is a product produced and endorsed by GW.

**Comment by FarseerVeraenthis** [comment]
Now, let's just take a moment to consider this situation.
If you're saying that you can use the content of any White Dwarf as "current", where do you stop...? 
You can go back as far as you like and find the most crazy rules from White Dwarf magazine from decades ago and still use them?? Madness.

10 years ago, 40k was 4th Ed (5th came out in mid-2008), there is not a single rules set (codex, supplements etc.) that has not been updated since then, but obviously White Dwarf doesn't get updated. Unless you can find CURRENT rules for the CURRENT edition of WH40K, the Ares will not be included in the CAT.
