### ISSUE TITLE
Codex: Space Wolves Wolf Lord Krom constraint issue.

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k-7th-edition#3529]
**File/Catalogue:** Space Wolves: Codex (2014) v2030

**BattleScribe version:** 2.00.14

**Platform:** Windows

**Dropbox:** Yes

**Description:** When adding "Wolf Lord Krom, The Fierce Eye" to a list, it returns the error "1 too many selections of Wolf Lord Krom, The Fierce-Eye (maximum 0). These lists do not include the "Krom Dragongaze" entry. I assume that there is an error with the conditional checks between the max in roster constraints between the two entries, where it is triggering max in roster to 0 incorrectly.

**Comment by GenWilhelm** [comment]
You're correct, there was a condition modifying the constraint, but there's no reason it should be firing since the logic is identical to the same modifier on Krom Dragongaze, which currently works as intended.

I'll remove the faulty modifier for now, as the Dragongaze modifier should throw up an error if you try to include both Kroms in the same roster.
