### ISSUE TITLE
Files over-written

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#354]
Looks like a whole bunch of files got over-written yesterday / earlier today. The knight I added to them on the 13th had gotten deleted.

I've replaced the files that I had been dealing with, but I can't tell how far back the changes go or what else is affected, so you'd all better check your work.

After checking through the closed issues, it looks like the #321 update to the Eldar is missing, so it's probably safe to assume anything newer than that is also at risk.

**Comment by Kangodo** [comment]
That is really weird, what catalogue had the Knight removed?
According to my Github nothing was removed (in the three catalogues I checked) since your update from three days ago.

**Comment by NebSeele** [comment]
I can confirm the updates to the csm catalogues have reverted, as well as the Exalted flamers on the daemons file. Time will tell if the recent furies fix will revert back. I'll fix them up in the next 24 hours when I get the chance to.

**Comment by hobodabobo** [comment]
Yeah, I just checked the furies, and they are still having the same issue, so they are affected.

**Comment by ghost** [comment]
I can't tell where it happened. I was editing the SAV file, then I started the github desktop app & it said there were files to sync from the server to my local folder (all one way as expected), so I did that. According to the app, it looked like the changes were all to things like DA or BA, but when I opened my github folder, it said the newest things were SW, the AM files and some other stuff as well. Sure enough, when I checked here at BSData/wh40k, _that_ said the AM file was last updated 2 months ago... even though I had added the Castigator on Saturday and made a release.

@senpai514 had added the Castigator to the Sisters, IK, GK, DA and SM as well, but it looks like those've gone, too.

**Comment by Thairne** [comment]
This is some really weird behavior. I'm not overly familiar with Git, but this smells like a huge bug.
As usual, tracking changes in XML files is a nightmare.
I took a look at DA. Nothing that could cause such behavior... However I noticed that with one of my commits following senpai's something weird happened.
He incremented the version number from 45 to 46.
I then incremented the version number from 45 to 47. That shouldn't have happened.
No revision did remove the Castigator, so a wrongly resolved conflict isn't the cause either.
Definately something fishy with Github.

**Comment by senpai514** [comment]
Yeah I had to redo some of my space marine fixes too. Ill go back and redo the knights I did the first time around and hopefully they will stay this time.

**Comment by Kangodo** [comment]
Grr, just found out it also affected Blood Angels.
So I re-added him too and I backed-up all my changes from today.

**Comment by OptimusMetallus** [comment]
I'd downloaded it the other day specifically for the Knight-Castigator, and had to redownload only to find the Knight-Castigator gone. How do I re-add the Castigator? Every time I go to the Data Files page and download it's the same old file which is still missing the Knight-Castigator (Which I recently spent $280 and received two days ago, so I'm particularly motivated in having an army builder which allows me to select it). Thanks.

**Comment by amis92** [comment]
Hi guys. I was hiking some mountains last 4 days (beautiful weather here in Polish Beskid mountains! :D )

Ah, leave you unguarded and look what happened!

So from my three-minute investigation it seems @Thairne made a commit which caused this hell. I don't blame you, Thairne! We all make mistakes and this one was beautifully easy to fix. Until some more changes were made, unfortunately. :)

So now quick summary what happened (most probably):
![zrzut ekranu 2014-09-18 15 23 10](https://cloud.githubusercontent.com/assets/2671396/4320404/21fb8182-3f37-11e4-9d1f-f5ab1bacb07f.png)

Dots are commits. Last black dot before blue branch is Thairne's "Removed limit for GUE" (however I think it should be GUO :) ). Then the blue branch is the actual master branch on which more commits were uploaded. And then the problem begins. It seems Thairne hadn't made pull before he started working on Spartan commit, or he worked really long (6 days?). Because on that un-synced branch he had, he made a commit (the black dot parallel to last blue one). And then he has done two things in an unknown order: he reverted the Spartan commit and synced changes, which merged them (blue branch goes into black one). For some reason Git merge tool left changes on original master and that state (with all the commits from 6 days reverted) was uploaded (pushed) as new master branch.

So for you it looked as though the changes disappeared. Thay haven't and in fact, they still are on server. They were just hidden behind one unfortunate commit. I could have fix it but you've just re-done the commits and it works anyway.

Just remember in future: in git, it's really hard to delete something from history. In most cases some work can easily make you return to some point in history.

Cheers!

**Comment by Thairne** [comment]
Ow...it was me?! Damnit. I'm sorry to have caused such a hazzle :(
I remember updating the Spartan, syncing it and getting a conflict. Not being used to the Git Console, I reverted the change (thinking it wasn't pushed to Master), synced and redit the Spartan.
It's a bit different on how it works with SVN and Tortoise.. There you have your local copy, commit it and it tells you about the conflicts and usually aborts the commit. You then can resolve the conflict locally and commit again and are done.
Here in git it seems you can commit, even with a conflict, which is why I tried reverting the conflict to keep the branch "clean", sync and then commit with my changes in the updated local file. Guess I better do some reading about Git so stuff like this doesn't happen again and I don't automatically assume to know what I'm doing ;)

**Comment by amis92** [comment]
I think all is now fixed, I'll close the issue.
