### ISSUE TITLE
Space Marines - Relics of the Armoury Validation is broken

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3548]
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.15

**Platform:** Mac

**Dropbox:** Yes

**Description:** Relic of the Armoury conditions appear broken:

RotA units have individual (max 1) limits, but multiple (different) RotA units can be taken without the required techmarine. Similarly, adding a techmarine doesn't appear to raise the (max 1) limitation.

Observed so far on (FW) Relic Sicaran, (FW) Relic Whirlwind Scorpius, (FW) Fire Raptor Gunship, (FW) Deredeo Pattern Dreadnought and (FW) Deimos Relic Pattern Predator.

**Comment by DrTobogganMD** [comment]
Yea, that's probably true. FW is a giant pain the ass.

I'll take a look.

**Comment by DrTobogganMD** [comment]
So, technically no RotA are allowed in a SM detachment. There is no Master of the Forge. FW hasn't published errata yet either (don't link the forum posts, i've seen them, they're not what we use as "legit").  Since we have nothing to validate 1 per "Master of the Forge" against, I'll leave it as is for now and let users police themselves.
