### ISSUE TITLE
Chaplain in Terminator armor unable to choose Weapons

### ISSUE THREAD

**Issue by electricm0nk** [BSData/wh40k-7th-edition#356]
Selections are permitted from Ranged Weapons.  Weapons list allows for 0 selections.

My chaplain must be allowed his Crozius!

**Comment by senpai514** [comment]
Since the terminator chaplain has a different wargear load out when selecting terminator armour a crozius is automatically included therefore you must deselect the weapon options for the power armour arms(I labeled them a little clearer) since the terminator version doesn't have all the different weapon lists that he could exchange items for like the power armour variant could. scroll down you will find terminator ranged weapons which does have choices available.

**Comment by electricm0nk** [comment]
Bolt Pistol arm still has a minimum of 1 and a maximum of 0 selections.

Same wit the Crozius arm

**Comment by senpai514** [comment]
The changes are still only our master copy at the moment. You will need to wait for the next update release to be pushed out before you will be able to download the change and see any corrections on the public side.
