### ISSUE TITLE
Renegades & Heretics - IA13 Data Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3595]
**File:** Renegades & Heretics.catz

**BattleScribe version:** 2.00.31

**Platform:** Android

**Dropbox:** Yes

**Description:** Yes ,hi, I'm just wondering what the hell happened to all the Info in the new version of battlescribe concerning the IA13: Renegades and Heretics list files ,from old battlescribe to this new version,seeing as you have to have the new version to even build a list anymore. My concern is that the data files for 7th edition IA13: Renegades and Heretics for this new battle scribe seems to only be for this Shitty  Siege of Vraks ,considering old battlescribes data files was just the base Renegades and Heretics and you had an option to either stick with the base builder or specifically select it as SOV,whereas here in this new version everyone is ONLY able to build a SHITTY  SOV list , just wanting to report that bug ,if it is one and possibly receive clarification  ,thanks for all your guys work

**Comment by GenWilhelm** [comment]
Renegades & Heretics: IA13 / IA:SoV covers both books since there is considerable overlap between the two. When you add any R&H detachment it should tell you that it needs 1 selection of "Imperial Armour Variant", which then tells you it needs 1 selection of "Volume".

On Desktop it looks something like this:
![r h](https://cloud.githubusercontent.com/assets/22036809/24400822/ba3fe250-13a9-11e7-87e1-dc7f87f70e0d.png)

Once you select one of the options the rest of the catalogue will be configured to use the available options from that volume of Imperial Armour.
