### ISSUE TITLE
Craftworld Eldar - Iyanden Supplement

### ISSUE THREAD

**Issue by Aetherion** [BSData/wh40k-7th-edition#3659]
**File/Catalogue**:  Eldar Craftworlds: Codex (2015) v2021

**BattleScribe version**: 2.00.19

**Platform**: iOS

**Dropbox**: No

**Description**: Cannot enable Iyanden Supplement for Craftworld Warhost, allied or formation detachments due to Iyanden supplement being available only under "Primary Detachments"

Also

- [x] Cost of Wraithforge Stone is 30 pts instead of No cost
- [x] Celestial Lance lacks a melee profile
- [x] Spear of Teuthlas lacks a melee profile

Thanks very much.

**Comment by FarseerVeraenthis** [comment]
Righto, I'll have a look and see what I can do...

**Comment by FarseerVeraenthis** [comment]
The Iyanden supplement gives you the following extra options;

- [x] Wraithlord or Wraithknight can be selected as your warlord. 
Neither is an HQ choice, so you still need e.g. one for a valid CAD.
This option does not effect Battlescribe.
- [x] Option to take a unit of up to 5 spiritseers rather than just one. Still takes up a single HQ choice.
This option is only applicable to CAD and Allied detachments. The Wraith Host in the Craftworld Warhost specifically references 1 Spiritseer.
- [x] Gifts of Asuryan are available for anyone who can normally select Remnants of Glory.
Applicable to all Force options.
- [x] ~~New Primaris Power for Spiritseers that use Runes of Battle.
Applicable to all Force options.~~ Psychic Powers are not included in the CAT files.
- [x] ~~Iyanden Warlord Traits
Applicable to all Force options.~~ Warlord Traits are not included in the CAT files.
- [x] Taking a Spiritseer allows Wraithguard and Wraithblade to be selected as Troops.
This option is only applicable to CAD and Allied detachments.

This is a checklist of what should be implemented, I did the initial implementation a little too quickly so I'll go for a review and include everything above :smile:

**Comment by Electrobix** [comment]
Where does it say "Taking a Spiritseer allows Wraithguard and Wraithblade to be selected as Troops.
This option is only applicable to CAD and Allied detachments"? This was an old codex rule not an Iyanden rule.

**Comment by FarseerVeraenthis** [comment]
I paraphrased the supplement, but the second sentence I added as a reference to the impact of the first sentence on the world of battlescribe. For example, you do not select troop or elite choices in a Craftworld Warhost, so this rule has no effect... And the rule is in the Iyanden supplement :smile:

**Comment by Electrobix** [comment]
No the rule is not in the Iyanden supplment.

**Comment by Electrobix** [comment]
As I said before the rule came from including a spirit seer and was from the pervious craftworld codex. The supplement as powers, relics and warlord traits only. I have the book in my hand so you need to check your facts.

**Comment by GenWilhelm** [comment]
Page 48, third paragraph under "Speaking to the Dead":

![iya](https://cloud.githubusercontent.com/assets/22036809/25044491/d7ba32e0-211e-11e7-9033-4beafb4f656f.png)

**Comment by Aetherion** [comment]
So how does one select gifts of asuryan for, say a spiritseer in a wraith host formation within the craftworld warhost detachment? It still appears to be unavailable

**Comment by FarseerVeraenthis** [comment]
It will be unavailable until Appspot picks up the release that I just pushed...
So, please wait a few hours then update your data and try again :smile:

**Comment by Aetherion** [comment]
Ahh be still my impatient heart, many thanks for your quick and able work 👏👏👏

**Comment by FarseerVeraenthis** [comment]
No worries, thanks for the props :smile: I just tried it and it seems to work on Android :smile:
