### ISSUE TITLE
IK allowing Guilliman as option.

### ISSUE THREAD

**Issue by flakpanda** [BSData/wh40k-7th-edition#3686]
Imperial Knights formations allow you to take Guilliman as a LoW option. You cannot due to faction restriction of the formations.

**Comment by francoisbeaulieu** [comment]
I'm not seeing him in the formations, only the IK detachments. It's probably not what was intended but, RAW, Guiliman would be allowed in the detachments. I assume @Kohato is waiting for an official FAQ on that?

**Comment by flakpanda** [comment]
Did not have material in front of me, but I believe all the formations also
restrict faction to IK like the detachments.

**Comment by francoisbeaulieu** [comment]
The formations specifically say "X number of Imperial Knights", or "These specific Knights", so Guilliman could not be used there. (And I can't add him to those formations via BS, so that seems to be correct.)

The IK detachments say X amount of Lords of War from faction IK. But Guillliman's specific rule would override that:
“Grand Master Voldus and Roboute Guilliman are new Army List Entries that can be included in any Armies of the Imperium Detachment, regardless of their Faction.” 
With that wording, if you don't allow Guilliman, you also could not allow for the FW knights as they are not, strictly speaking, in the IK faction either.

**Comment by DrTobogganMD** [comment]
Supplement rules do not overwrite Codex rules, only BRB.  The two rules conflict, therefor they cancel each other out per general FAQ.  He should not be allowed in an IK detachment.  I just haven't gotten around to opening it up to fix.

**Comment by Thairne** [comment]
I'm still here, ya know :P
