### ISSUE TITLE
[Anon] Grey Knights Techmarine not in HQ Slot

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#370]
**File:** Grey Knights - Codex (2014).catz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** Yes

**Description:** The Techmarine is only available in the "No Force Org Slot", but he is a HQ choice as well.

**Comment by amis92** [comment]
He is, but there is no way to increase HQ limit in a given detachment type. That's why we use No Force Org Slot - he doesn't take up a Slot. His membership in HQ is noted in a rule. That's the most convenient way unfortunately - the other is giving Techmarine upgrade for each other HQ Army List Entry. :/

**Comment by ghost** [comment]
If you read the codex it states while he is an hq choice he does not count against the amount of hq choices you can take just like a command squad.
