### ISSUE TITLE
Codex: Space Marines and Forgeworld

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#376]
Hello authors,

I am "re-opening" the issue from #155 now that we have some awesome work done on the C:SM.
My thanks for this, because it's really, really great!

Let me copy the text I am referring to:

> Another question is about FW.
> How do people feel about using the Hidden-option to hide/show FW-units with Space Marines?
> My BA-file has 6 units already and there are tons to add.
> Many players do not use FW-models/rules and this might make the lists less confusing.
> I'm really thinking of adding this to my catalogue
> Necrons are fine, because they hardly have any units.. But Space Marines can go up to 20 or so entries.
> Greetings,
> Kangodo

It seems my prediction of 20 entries was a bit low.
22 HQ, 6 Elites, 3 Fast Attack and 14 Heavy Support.
So that makes it a total of 45 entries from FW.

In Codex: Blood Angels I've created an entry that allows people to hide/show units from Forgeworld.
It might be better if we had the option to hide stuff depending on the Chapter Trait, but I think that would be too much work for C:SM.
How do others feel about something to hide stuff? And especially @senpai514 since he did most of the work.
And the second question: If yes, do you think these 45 additional entries should be shown or hidden by default?

The goal of this is to make it less cluttered for people who don't have the books, models or aren't interested in adding those to their Force.
I am certainly willing to do all the work on this, I've created this issue because I've heard some complaints from friends and when I opened the Codex on my phone I could understand the confusion.

**Comment by ghost** [comment]
I would love for them to all be under one codex I use forge world models on a regular basis and the way I use bs right now I have to create a separate list for forge world units

**Comment by senpai514** [comment]
There are a couple of hidden FW models as well too that are dedicated transports the Lucius pattern drop pod and the infernum pattern razorback.

I do like the idea of linking HQ's to the chapter tactic selection as there are over 40 choices there codex and FW

**Comment by Kangodo** [comment]
Pohok, don't get me wrong! It would all be in the same Codex, but there'd be an option to hide them.
Thommy, that might be a good idea too: Just have it on the HQ's.
They could be hidden by default, and it's quite easy to make a modifier that 'shows' it if the correct Chapter Tactic is chosen. (That might also work for stuff like Chronus and Tellion).
Maybe we could even have a modifier that "hides if Chapter Tactic is not <Ultramarines>", although that would require some testing because I'm not sure if it works.
The idea would be to hide all non-UM units when you select UM as chapter.

The 14 Heavy Supports are 'doable' at the moment, they are only 14.

**Comment by senpai514** [comment]
I just had another thought that while a little more work could help tailor the selection availability.
Entry group
Show FW Models
-HQ
-elite
-fast
-heavy

And link each hide/show to the appropriate selection since I know most folks have maybe one or two  models from a certain force type (I have 15 FW models and 3 of them LOW).

**Comment by ghost** [comment]
Either would be fine as long as they don't require a diff formation to be taken to have all sm and fw on one

**Comment by senpai514** [comment]
I'm starting on the Chapter Tactic modifiers for HQ's and Tyrannic War Vets. Works nice so far will then add additional for the FW after.

**Comment by amis92** [comment]
I suggested something a bit more foregoing on UserVoice. Please check it out and vote if you like. That enhancement would solve our problem in a great and elegant way. Link: http://battlescribe.uservoice.com/forums/55066-general/suggestions/6312936-enhance-the-role-of-book-field

**Comment by Thairne** [comment]
Sounds great. Auto-hiding FW models is something I will do to DA's.
However, please consider the old rule of implementation:
If it ain't broken, don't fix it ;)
In this case I'd say: add the option to HIDE them, but keep em shown as-is. This way the status quo stays with an additional option for those who don't want them to be shown.

I'm a bit confused on the actual implementation though:
You're adding a new category/entry that you can take into your rooster, based on which you show/hide the appropriate units, yes?
so

Hide Forgeworld
- HQ

if you add the HQ to your rooster, all HQ entries get hidden?

**Comment by NebSeele** [comment]
The idea of using the hiding function is something that I'm probably also gonna use on the CSM file.

with the UserVoice idea; If it's that certain shared profiles get written once and then are shared, then I could see it being woefully underused for the Xeno armies. Then again, I'm not entirely sure how it's meant to work based on how it's worded.

**Comment by Kangodo** [comment]
Auto-hiding is something I only like if really necessary, like a file that has around 45 FW-entries.
For stuff like BA and such I prefer showing them as default with an option to hide, because they have 18 FW-entries.
For races like Necrons I don't think something like that is needed since they only have a few.

@Thairne, the best way to explain what I did would be to open the BA-file.
It has a (No Category)-entry called "Forgeworld Models".
This has an entry-group with 'Show' and 'Hide'.
Each FW entry has a modifier that says "Hide => if roster contains entry of 'Hide'.

Senpai is auto-hiding a lot of stuff and has a modifier with: "Show => if roster contains 'show' and if roster contains '<insert chapter tactic'>"

The suggestion on Uservoice is great, but that could take a while.

And one semi-related question: Why do we actually have an entry called 'Alied Detachment Chapter Tactic'?

**Comment by Thairne** [comment]
Neat, I'll steal your idea ;)

**Comment by senpai514** [comment]
with what I have done so far it looks far less cluttered which is nice being able to turn models on and in in each category. FW HQ need the appropriate Chapter Tactic selected to be visible as well; with this done I can clean up their name and remove the chapter tactic label since it will no longer be needed. Codex HQ only need chapter tactic selection to be visible

Now that you ask that I can see the redundancy of it. whether you have a CAD or allied detachment all you need is just one chapter tactic selection. Ill fix that up and look and see if it has any deeper connections.

**Comment by senpai514** [comment]
When Chapter Tactics were implemented they were set at Roster level restrictions which would explain the separate entry.  I'm going to shift all them over to Force level and that should isolate all the modifiers down to each detachment/force that is in the one roster.

**Comment by senpai514** [comment]
@Thairne I think you may have gone a little overboard with your force type options; you have more choices than I put in and I have more extra stuff. You have boxes for ones that don't even have FW models in a particular type (troops & HQ).  I came up with this method because of the sheer overall size of options and such I am hiding by default then allowing them to become visible by selections. I also just left the LOW alone myself seeing as how they are in their own category and separated.  Since you are showing by default you could prob get away with hiding all at once like blood angels does since your catalogue doesn't get quite as cluttered as mine does with FW and it leaves things a bit simpler for the end user.  

Just my opinion for you to help you out.

**Comment by Thairne** [comment]
Hm yes, but as I see it, I added options and changed nothing for those that don't care.
Granted, I added even Entrys for stuff that isnt there (yet), but I can't see those hurting. Also I kinda wanted an option to hide all models... After all it says hide FW and there are still FW models in there.
Maybe it's my job as a Software Dev that makes me do such things and shrouds my vision ;) Always try to make upgrading in the future as smooth as possible and implement new features...

I also added an "hide all" option as the first one so I can emulate the "Blood Angels Way" for a one click solution. I went with this approach because I myself use only a very few select models - like the Mortis Dread due to lack of DA AA. So I only want the Elite section to "clutter up" in that rooster and not e.g. the Heavy Support.
What I especially like about this method is the sorting. It removes the FW models and then puts them back basically sorted.

Thanks for your oppinion!

**Comment by Kangodo** [comment]
That is understandable, and your Codex has quite a few more FW-entries than BA.
To both of you: Now that we have a modifier to hide things I guess we don't need the \* after each entry any more?

PS. That sorting is awesome, never noticed that before.

**Comment by Thairne** [comment]
Hm... The question is - what do we gain by removing the \* ?
We loose the ability to see on a quick glance if its a FW model or not.
We gain a more unified look in the selection screen.

I'd say... leave it in, doesn't hurt and provides additional benefit.

**Comment by senpai514** [comment]
I started putting the asterisk after model names as a quick glance
reference identifying FW from codex which can be handy in both catalogue
and roster editor. I suppose we could do without it

**Comment by ghost** [comment]
Missing typhoon missile launcher weapon profile for space marines when you take the storm talon. Allies you to select and has proper points but doesn't print the profile for it

**Comment by senpai514** [comment]
@Pohok creating a new issue for an item like that would be better than adding it into an unrelated existing thread where it could be potentially lost. Makes for better tracking that way too.

**Comment by ghost** [comment]
Sorry I was on the mid of a game and on my phone so I couldn't report right

**Comment by Thairne** [comment]
So we're going to remove the asterix for FW models now?
Anyone worth his salt will be able to tell em apart anyway honstely.

**Comment by senpai514** [comment]
Hidden models aren't hidden on mobile app.

**Comment by ghost** [comment]
Doesn't it take a few days for the updated files to show up for the mobile app?

**Comment by senpai514** [comment]
Not when my app is linked to my Dropbox which uses the frontline files that we edit

**Comment by Kangodo** [comment]
Thank you for the great changes!
When there is more news or if there are questions we can always re-open this.
