### ISSUE TITLE
Post Chaos validation issues in 8th here

### ISSUE THREAD

**Issue by cartag** [BSData/wh40k-7th-edition#3766]
Please post all validation issues with Chaos Daemons, CSM, Death Guard, Questor Traitoris, and/or Thousand Sons here.

**Comment by T6Ted** [comment]
1. Magnus the Red is missing
2. When switching to Legion Death Guard Rubric Marines and Bezerkers are still an option in the Elite choice. 
3. Havocs has no wargear options and when removing them from the list it removes a single model at a time, not the whole unit.

**Comment by cartag** [comment]
Death Guard and Thousand Sons are now in their own file

**Comment by cartag** [comment]
1) To elaborate further, Magnus and Ahriman are now in the Thousand Sons file, and Typhus is in Death Guard. 
2) I'm still working on that part
3) Noted, I'll get on it.

**Comment by cartag** [comment]
From @SeraphAP:

Daemon Prince with Wings throws error when choosing second set of Maleific talons;
No Belakor at all?
Can't seem to find any reference to the God-specific rules (Quicksilver Swiftness for Slaanesh daemons etc).

Should the Daemons be merged with the CSM? They can both be taken in the same detachment since they're faction keywords., right?...

Response:
Fixed
Be'lakor was hidden, uploading again. 
I assure you, they are there. 

No, for much the same reason that Space Marines and Astra Militarum won't be in the same file since they're both Imperium. Try adding a second detachment immediately following addign the first. You can add a second faction in, using the same detachment type, and it will validate against both.

**Comment by GrimReaper711** [comment]
There's an entry for World Eaters within the new index which states that Beserkers can be taken as troop choices (Other than that most other options are the same).

Currently no option to take them as troops in the current file. Wondering if a new file will be created for World eaters or a simple option to take Zerkers as troops with a note that it only applies to world eaters?

Edit: Never mind - I can see there is a way to do this by adding the "World Eaters" legion.

**Comment by T6Ted** [comment]
@cartag Any unit with the same faction keyword can be taken in a detachment. So demons, death guard, 1k sons can all be mixed together cause they have the "CHAOS" keyword. Same for Imperium units cause of the "IMPERIUM" keyword.

**Comment by cartag** [comment]
@GrimReaper711 It will be implemented, I'm still getting everything CSM entered. World Eaters will not have their own separate one right now as there is not enough different about the legion (EC as well) to justify their own file. Death Guard and Thousand Sons have major restrictions on what can be brought, enough to where trying to show/hide that number of things would be a major slowdown. Moving them into their own files makes sense. 

@T6Ted you say this as if you don't think I'm already aware. I know how it's set up, and right now you can take the forces in the same detachment, it just has to be finessed a little. We also have to work within the restrictions of BS itself. 

![image](https://user-images.githubusercontent.com/4388344/26876833-263779aa-4b45-11e7-8936-aa55a6636069.png)

This lets you add multiple index files to the same detachment, and validation will work. One troop, one HQ for a Patrol detachment:

![image](https://user-images.githubusercontent.com/4388344/26876899-57aac852-4b45-11e7-9e86-52ca378b2ce3.png)

**Comment by ninchistudios** [comment]
Revalidated Questor Traitoris, no issues.

**Comment by T6Ted** [comment]
@cartag I see. Makes sense to me now. Just trying to help. Thank you for your help.

**Comment by cartag** [comment]
@T6Ted I get that, and sorry if I came across cranky. It's 6:08 AM here and I didn't sleep well last night. Getting show/hide based on WE/EC set up for cult troops now

**Comment by ninchistudios** [comment]
ping me if you want anything else validated @cartag

**Comment by McChew** [comment]
Chaos Space Marines: Adding elite units increase the PL value of Chosen and Rubic Marines.
Adding troops units increases PL of Chaos Space Marins troop units

**Comment by cartag** [comment]
@McChew, updated, just hasn't been uploaded yet, will be synced with larger entries.

**Comment by Nighttail** [comment]
Daemons:
**Bloodletters:** Having multiple Bloodletter units and adding more Bloodletters to one unit adds models to all Bloodletter units.
**Daemonettes:** Having multiple Daemonette units and adding more Daemonettes to one unit adds models to all Daemonette units.
**Horrors:** Each individual Horror model seems to count towards the allowed troops amount for a detachment.
**Plaguebearers:** Having multiple Plaguebearer units and adding more Plaguebearers to one unit adds models to all Plaguebearer units. Plaguebearers also don't stack (10x Plaguebearers), but instead shows each Plaguebearer model individually, causing very long lists.

Chaos Space Marines:
**Chaos Lord in Terminator Armour:** Gives an error if you choose more than 1 melee weapon. Also gives an error when selecting a Combi-weapon and a Melee weapon that isn't the Power sword under "Power sword options".
**Everything in Terminator Armour:** Combi-bolters are listed twice, the second time for no cost.
**Forgefiends** are missing from the Heavy Support section.

**Comment by cartag** [comment]
@Nighttail fixed Daemon issues, uploading soon. CSM in progress, will be uploaded later.

**Comment by raustin1980** [comment]
Can chaos forces no longer take contemptor dreadnoughts in 40k? Can't find them anywhere

**Comment by cartag** [comment]
Contemptor dreads are FW models, the index hasn't leaked yet

**Comment by raustin1980** [comment]
Are the current files on battlescribe for 8th then? As chaos contemptors where available in imperial armour 13 and angels of death supplements. I'm trying to add them to my list for a 7th edition game but can't find them anywhere

**Comment by cartag** [comment]
Oh, for 7th be sure to add "Show Forgeworld" to your roster, it's the first entry under Elites.

**Comment by raustin1980** [comment]
Yeah I've done that but they still don't show up. I'll give it another bash. 

Cheers for the help

**Comment by Nighttail** [comment]
Cheers for fixing the Daemon and CSM issues.
Another thing I found was Thousand Sons Rubric Marines, Scarab Occult Terminators and Tzaangors don't stack, so each individual Rubricae/Terminator/Tzaangor shows up in the list which causes the lists to become very long and cluttered. The Elite choice Rubricae for regular CSM stack just fine though.
As for Scarab Occult Terminators, they also have to individually select Inferno Combi-bolters even though that's the only weapon they can take. It'd probably be a bit easier to manage if they were changed to how they Rubricae weapons are done; so that the weapon upgrades are their points value minus 3 (for the Combi-bolter they're replacing). That way they can also stack together like the Rubricae.

As for Chaos Lords in Terminator Armour: if you take 2 Lightning Claws on them it's 9+13 points total, when the second Claw should only cost 4 points, for 13 points in total for both.

**Comment by alphalas** [comment]
That's a known BS thing regarding the occult- we try to have wargear be true to model, which means BS does that.

**Comment by Nighttail** [comment]
Good to know for the Occults. I'm not too good with the whole programming aspect of Battlescribe so I'm just going through the files trying to provide feedback on potential errors.

I noticed that the damage on Lightning Claws display as 31 instead of 1, and that the Icon of Flame says "[...] of the model carrying the Icon of **Fmale**." instead of Flame.
Havoc Launchers don't have point costs on vehicles (both CSM and Thousand Sons), Combi-bolters don't have point costs on vehicles (Thousand Sons).

**Comment by The-Spooky-Dude** [comment]
For Chaos Daemons:

- [x] Herald of Khorne on Blood Throne does not have any of their stats filled in, and movement is written in as 0. The correct stats are as follows: M:6 WS:2+ BS:2+ S:5 T:7 W:7 A;5 Ld:8 Sv:5+

- [x] Kairos Fateweaver has a stray (-) where his save is listed. It reads as "6+-" instead of "6+"

- [x] The Blue Scribes do not have a Movement (12) or Save characteristic listed (6+)

- [x] Horrors have the incorrect movement listed. It is listed as 3 when it is 6 and they do not have a save listed (6+)

- [x] Flamers have an incorrect and unnecessary second entry that needs to be deleted from their data sheet.

- [x] Hellflayer chariot has a typo, listing it's strength as 44 instead of 4.

- [x] Screamers don't have any stats. The correct stats are as follows: M:16 WS:4+ BS: - S:4 T:4 W:2 A:3 Ld:7 Sv:6+

Thank you so much for your guys' hard work and dedication! I hope I helped out!

**Comment by The-Spooky-Dude** [comment]
For CSM:

- [x] Dark Apostle does not have any stats listed. The stats are as follows: M:6 WS:2+ BS:3+ S:4 T:4 A:3 Ld:9 Sv:3+

- [x] Huron Blackheart does not have any stats listed. The stats are as follows: M:6 WS:2+ BS:2+ S:4 T:4 W:5 A:5 Ld:9 Sv: 3+ Also don't forget to list the Hamadrya's stats either, in the same data sheet as Huron. The stats are as follows: M:6 WS:6+ BS:- S:2 T:4 W:1 A:1 Ld:9 Sv:3+

- [x] Chaos Cultists are listed as a full squad of 9 cultists and a cultist champion as only 5 points. Chaos cultists are not 5 points a squad, but 5 points a model. Cultists are listed as no cost to add extras, this needs to be added to 5 points a model. The default cost of a normal 10 man squad of cultists needs to be changed from 5 points a squad to 50.

- [x] Chaos Landraider is listed as having no stats. The stats are as follows: M:* WS:6+ BS:* S:8 T:8 W:16 A:* Ld:9 Sv:2+
Damage Chart:
Remaining Wounds: 9-16+   5-8   1-4
M:                             10         5       3
BS:                             3+        4+     5+
A:                               6          D6     1

- [x] Chaos Predator is listed as having no stats: The stats are as follows: M:* WS:6+ BS:* S:6 T:7 W:11 A:* Ld:8 Sv:3+
Damage Chart:
Remaining Wounds: 7-11+   3-6   1-2
M:                             12         6      3
BS:                             3+        4+   5+
A:                               3          D3   1

- [x] Forgefiend is missing all sorts of stats and needs to be updated with it's damage chart as well. Here is all the stats, including the edited ones that were already there and the missing ones. The stats are as follows: M:* WS:4+ BS:* S:6 T:7 W:12 A:* Ld:8 Sv:3+
Damage Chart:
Remaining Wounds: 7-12+ 4-6 1-3
M: 8 6 4
BS: 4+ 5+ 6+
A: 4 3 2

- [x] Obliterators don't have any stats listed. The stats are as follows: M:4 WS:3+ BS:3+ S:5 T:4 W;3 A:3 Ld:8 Sv:2+

**Comment by Crowbar90** [comment]
- [x] Cypher is missing (probably just hidden, as far as I can tell)
- [x] Fallen are missing

**Comment by GenWilhelm** [comment]
Typos in Chaos Daemons:
- [x] Malefic talon: "wepaon"
- [x] The Changeling, Formless Horror: "untilt he"
- [x] Horrors, Split: "HOrrors"
- [x] Piercing claws: "rmake"
- [x] Daemonettes, Graceful Killers: "moel"
- [x] Daemonic Ritual (3rd paragraph): "th estart"

Death Guard:
- [x] Malefic talon: "wepaon"
- [x] Helbrute, Explodes: "teh"
- [x] Malignant Plaguecaster, Malignant Plaguecaster: "teh"

**Comment by cronsOP125** [comment]
There's a rather bizarre bug with Chaos Chosen. No validation issues while the squad is at min size, but when you add chosen models, the required number of loadouts increases out of proportion. Aspiring Champion+5 Chosen requires minimum 9 weapon loadouts. After that initial jump, it goes up by one each time.

**Comment by T6Ted** [comment]
Just noticed that Bezerkers do not have the option to replace their bolt pistol with a chain axe in the main CSM data.

**Comment by mdtm1g14** [comment]
For Daemons:

The Soulgrinder's stats are a bit wrong, the wounds and strength are out and the BS should be variable.

**Comment by MagnusPihlImplicit** [comment]
There's some cost issues with Thousand Sons:

- [ ] Tzaangors in BattleScribe are PL 7 for 10. In the index, they're PL 4 for 10, and then +3 for every 10 models added.
- [ ] Rubric Marines are PL 8 for the intial 5, then +6 PL for every 5 added models. In BattleScribe they are correctly PL 8 initially, but jump to PL 20 at **9 models**, rather than 10. Then jumps to PL 26 at **15 models**, rather than 16. Seems like they're always jumping in cost 1 model too soon.

**Comment by magnuspihl** [comment]
There's some cost issues with Thousand Sons:

- [x] Tzaangors in BattleScribe are PL 7 for 10. In the index, they're PL 4 for 10, and then +3 for every 10 models added.
- [x] Rubric Marines are PL 8 for the intial 5, then +6 PL for every 5 added models. In BattleScribe they are correctly PL 8 initially, but jump to PL 20 at **9 models**, rather than 10. Then jumps to PL 26 at **15 models**, rather than 16. Seems like they're always jumping in cost 1 model too soon.

**Comment by skonk** [comment]
- [x] Having multiple Berzerker units and adding Chainaxes to one of the unit is incrementing the same option in other units. As a quick test I opened the file in the data editor and unticked "collective?" for the "swap bolt pistol and chainsword for chainaxe" and that seems to stop the problem. But I have no idea if changing that would break everything else or not.

- [x]  Death Guard - Lord of Contagion isn't factoring in the cost of his Plaguereaper sword (should be a 45 point addition).
- [x] Death Guard - Plague Marines - up to 2 models can replace their boltgun for blightlaunchers OR anything from the special weapons list. Currently there is only the option to take the blightlauncher.
- [x] Death Guard - Noxious Blightbringer seems over priced. His base cost is 73 points + 7 for the Plasma Pistol and the Cursed Plague Bell is 0 points = 80; but he's coming up as 109 points in BS.
- [x] Death Guard - Foetid Bloat-drone is under costed. Base cost is 99 points + 2 x Plaguespitter at 17 points each and a Plague Probe at 25 points. Total = 158 points.

**Comment by Olsen370** [comment]
- [x] CSM - Chaos Bikers: they have a combi-bolter on each bike, which are not included (2 points each). Two of them may swap these combi-bolters with a Special weapon. Also they are listed with the "Blood for the Blood God" rule.

**Comment by Olsen370** [comment]
- [x] Many "vanilla" wargear options won´t vanish if you select a replacement. For example: if you try to switch the bolt pistol and the chainsword with a plasma pistol and a force sword for a Chaos Lord, they are still listed as weapons of the unit and create an error massage (too many selections for xyz).

**Comment by Olsen370** [comment]
- [x] If you select "Replace autogun with autopistol and brutal assault weapon" for a unit of Chaos Cultists, it will change this for every Cultists unit in your detachment.

**Comment by sassmcsass** [comment]
- [x] Troop Noise Marines: when you have multiple units, changing chainsword or Sonic blasters on one unit changes that setting for all units of noise Marines.Thank you for doing these!

**Comment by Izwor** [comment]
- [x]  Be'Lakor is overpriced. Be'Lakor should be 240p (its 350 in BS)

- [x] Legions for CSM army are missing (Thousand Sons, Death Guard).

- [x] I cannot create CSM/Daemon army, it should be possible to create 'chaos' keyword army.

**Comment by skonk** [comment]
@Izwor Thousand Sons and Death Guard have been separated out into their own catalogues; so you need to select them directly rather than CSM.

To create a Keyword based army you need to do this using a feature in battlescribe that allows you to add Detachments into (so nested) other detachments.

Example:
Create a new list and add a new force. Select Daemons and Select Patrol Detachment.
After adding this, make sure the detachment is selected in the list and then add a second force, but this time select Chaos Space Marines and Patrol Detachment.

The CSM detachment will be added as a child of the Daemons detachment and battlescribe, while displaying them like 2 different detachments, will actually validate them as if they were a single detachment.

So in the above example; adding a Daemon HQ and a CSM troop will show no errors, because it correctly validates the patrol detachment as having the minimum 1 HQ and 1 Troop.

@cartag posted and tutorial closer to the top of this thread that includes pictures :)

**Comment by cartag** [comment]
@Olsen370  for your bug report on Chaos Lords and default weapon selections, you'll want to uncheck the default weapon. The area is labeled as "Options"

![image](https://user-images.githubusercontent.com/4388344/27107707-c5abe1d6-5056-11e7-80bd-0b1383b56458.png)

**Comment by Bparks1983** [comment]
- [x] Chaos Daemon princes (from the Daemon codex) are showing their powers are generated from Dark Hereticus and it should be from their Chaos daemon alignment. 

- [x] Pink Horrors are missing their Ranged attack.

**Comment by Bparks1983** [comment]
- [x] Herald of Tzeentch on foot has Unstoppable Ferocity instead of Ephemeral Form. 
- [x] Daemonettes have Unstoppable Ferocity instead of Quicksilver Swiftness. 
- [x] Lord of Change is missing Ephemeral Form. 
- [x] Kairos Fateweaver no longer appears to have The Oracle of Eternity 4+ invulnerable save (or Ephemeral Form). 

Generally speaking the formatting for the Chaos God specific abilities is inconsistent. Some have the ability listed at the top of the page in a box, some with the rest of the abilities at the bottom, some have the ability listed with the rest of their abilities (i.e. Daemonic Ritual) and some don't. This is a minor issue, I just wanted to point it out.

Thanks so much for doing all this .

**Comment by magnuspihl** [comment]
Minor issue / inconsistency with Rubric Marines (in both Chaos - Chaos Space Marines and Chaos - Thousand Sons) and Tzaangors (in Chaos - Thousand Sons):

- [x] PL isn't increased when adding models until you hit the limit for the PL. For instance, 5 models in a Rubric Marine unit is 8 PL. When adding models, it doesn't increase to PL 14 until the unit contains 10 models. In all other units I've tested the PL increases immediately (at 6 models in the case of Rubric Marines), which is consistent with the "units don't have to be at full strength, but still cost their full PL" rule.

**Comment by T6Ted** [comment]
- [x] Lord of Contagion special rules references Typhus.

- [x] Also when added a legion under a CSM detachment it still allows the elite choice ie plague marines, berzerkers and rubric marines as troops. Not sure if there is a way in the program to limit this choice or not?

**Comment by GenWilhelm** [comment]
Thousand Sons Typos:
- [x] Ahriman on Disc of Tzeentch, Blades on Disc of Tzeentch: "proile"
- [x] Exalted Sorcerer on Disc of Tzeentch, Blades on Disc of Tzeentch: "proile"
- [x] Sorcerer on Disc of Tzeentch, Blades on Disc of Tzeentch: "proile"
- [x] Icon of Flame: "Fmale"
- [x] Tzaangors, Relic Hunters: "targetting"

**Comment by Nighttail** [comment]
- [x] Terminator Champion with 2 Lightning Claws gives error "Terminator Champion cannot have any selections of Lightning claw (hidden)".
- [x] Terminator Champion's Lightning Claws cost 9 points each when taking a pair, for 18 points total. Should be 9+4 for 13 points total.

**Comment by Olsen370** [comment]
- [x] Chosen: The Aspiring Champion has a chainsword right from the start. This is an option, not his vanilla wargear. He is armed with a boltgun and a bolt pistol, which can be switched with items from the Champions Equipment list.

**Comment by cartag** [comment]
All fixes listed have been implemented.
