### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Irongryphon** [BSData/wh40k-7th-edition#378]
Hey All,
I wanted to join up, so I can build armies for my favorite games, and offer some input for those repositories.  Thanks.

**Comment by amis92** [comment]
Invitation sent. Keep on reading the Getting Started. Welcome aboard!

**Comment by amis92** [comment]
@Irongryphon You have one week to accept the invitation, after that I'll delete the invitation and you'll have to re-apply.

I hope you understand - I'm doing organisation cleanup :)

**Comment by Irongryphon** [comment]
No worries amis92.  I am a full time student and that keeps me busy. Can you show me how Git-Hub works?  I'm not very technical minded.

**Comment by amis92** [comment]
As you see here, we are using Issues - that's a bugtracker and sometimes a discussion place. Repository works like manual Dropbox - you have to manually approve changes you've made, manually push them to servers, and manually pull changes of others. The Getting Started goes quite well with further assistance (however thanks to app updates visuals aren't quite correct). To accept the invitation and start fixing/enhancing or otherwise contributing, you'd need to accept the invitation we sent you.

I'm full-time student too, just on programming faculty :D

Also if you want to signal me directly, write `@amis92`. Or @ whoever you want.

Cheers
