### ISSUE TITLE
Tyranids Editing

### ISSUE THREAD

**Issue by Requiet** [BSData/wh40k-7th-edition#3780]
**File/Catalogue:** 

**BattleScribe version:** 2.00.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Just trying to do my part, when through the Tyranids Index and these are the issues I noticed.

Broodlord - Update leadership to 10
Hive Tyrant - Add to the wings entry that it also adds the keyword FLY to the model.

Tervigon - Remaining wounds need to be fixed. Missing 4-7
Tervigon - Text for "Spawn Termagaunts" correct the beginning of second sentence. "If it does -so-"

Tyranid Warriors - Need Synapse and Shadow in the Warp Rules.

Other Wargear - Seems weird that some have toxin sacs/adrenal glands on the second part of the list and some have it in the first (Where you select how many models) Yeah this switches back and forth in the other entries. Seems really weird.From what I can tell all adrenal glands/toxin sacs are taken as a unit upgrade and not on a model basis. All unit profiles should probably be updated to respect that (Such as Hive Guard and warriors being able to take them separately in battlescribe, though the index would not allow this.) This applies to flesh hooks as well being taken as a unit upgrade and not a model upgrade.

Deathleaper - "It's After Me!" Correct the sentence for "At the end of any of your Movements phases Deathleaper can pounce upon it[s]"

Sky-Slasher Swarm/Ripper Swarm - Spinemaws are a unit upgrade not a model upgrade.

Missing Sporocyst and fortifications tabs

Tyrannocyte - Remaining wounds chart, 1-3 should have 3 strength listed.

**Comment by GenWilhelm** [comment]
>Hive Tyrant - Add to the wings entry that it also adds the keyword FLY to the model.

There's currently no way to modify keywords dynamically. The wings are marked as FLY, but I'm unable to test how this affects the output.

>Other Wargear - Seems weird that some have toxin sacs/adrenal glands on the second part of the list and some have it in the first[...]

The index states that the models are taking the upgrade ("All *models* in the unit may have..."), so I've tried to reflect that by having the upgrade on the model level so it appears with the other wargear on the model. The only place where this isn't the case is with Termagants, due to the way that you select models in that unit.

>Sky-Slasher Swarm/Ripper Swarm - Spinemaws are a unit upgrade not a model upgrade.

See above.

>Missing Sporocyst and fortifications tabs

Fortifications are now taken as a separate Detachment to other units - the Fortification Network.

Anything not mentioned above has been fixed.
