### ISSUE TITLE
Harlequins cat pass after 3757 fixes

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#3783]
Harlequins.cat
BattleScribe version: 2.01.00
Platform: Windows 10
Dropbox: No

Checked text for typos, checked statlines and checked pointcost, found the following issues:

Shadowseer should have a 7+ save, not 6+
Troupe Master is missing his/her Prismatic Grenades
Death Jester has some typos in the Deadly Hunter and Death is not Enough descriptions
Solitaire has a single typo ('ti' instead of 'to')  in the Blitz description
Skyweavers has T3 W1 A4, should be T4 W3 A3
Skyweaver should have a save of 4+, not 6+
A Skyweaver is 35 points per model, not 15
Skyweaver Haywire cannon description misses a space after the first '4+'
Starweaver, check the description from Open-topped, it has one typo and the latter part is copied from the Tidewall Gunrig description :p

As an aside, why is the selection method for more Voidweavers in a unit different from more Skyweavers in a unit?

**Comment by USSX-Hares** [comment]
Done:
~~Shadowseer should have a 7+ save, not 6+~~
~~Troupe Master is missing his/her Prismatic Grenades~~
~~Death Jester has some typos in the Deadly Hunter and Death is not Enough descriptions~~
~~Solitaire has a single typo ('ti' instead of 'to') in the Blitz description~~
~~Skyweavers has T3 W1 A4, should be T4 W3 A3~~ (completely wrong profile - even name)
~~Skyweaver should have a save of 4+, not 6+~~
~~A Skyweaver is 35 points per model, not 15~~
~~Skyweaver Haywire cannon description misses a space after the first '4+'~~
~~Starweaver, check the description from Open-topped, it has one typo and the latter part is copied from the Tidewall Gunrig description :p~~

> As an aside, why is the selection method for more Voidweavers in a unit different from more Skyweavers in a unit?

Changed for Skyweavers to match Voidweavers.

**Comment by USSX-Hares** [comment]
@Owlsbane, please, verify

**Comment by Owlsbane** [comment]
Troupe Master has Prismatic Grenades implemented weirdly. Should be standard gear, not a counter that allows from 0 to infinity ;)
Description Death is not Enough for Death Jester still misses the word 'that' between 'model' and 'flees'

Apart from that, looking good.

**Comment by USSX-Hares** [comment]
Ok, I'll fix this evening, along with migration of rules into profiles->abilities

**Comment by USSX-Hares** [comment]
@Owlsbane  All fixed.
