### ISSUE TITLE
8th Ed Space Marines **SUBMIT ALL BUGS HERE**

### ISSUE THREAD

**Issue by flakpanda** [BSData/wh40k-7th-edition#3797]
Please submit **ALL** issue with 8th edition Space Marine catalog.
**Final v1 progress upload done**
Deleting all current comments as of 6/15/17.

**Comment by ilaunchbury** [comment]
Captain/Captain on Bike Weapon validation is not working correctly. It should not be possible to have a master crafted boltgun and a pistol.

**Comment by flakpanda** [comment]
@ilaunchbury this has been fixed and been uploaded in commit https://github.com/BSData/wh40k/commit/b2477f606cc84d65d946c8189b124ad35d02cd97

**Comment by CrusherJoe** [comment]
Scout Squad: Adding a Sniper Rifle doesn't change the points cost (the cost of the Scout remains at 15 points). Same with adding Camo Cloaks.

**Comment by flakpanda** [comment]
Cannot reproduce issue @CrusherJoe.
Please make sure you have the most current version of Battlescribe/Data. If so, try reinstalling BS.
![screen shot 2017-06-10 at 11 27 35 am](https://user-images.githubusercontent.com/19719565/27004539-4d8168da-4dd0-11e7-863e-5465e608c874.jpg)

**Comment by dennywright** [comment]
As of 79fdc71e, Scout Squad: Adding Camo cloak, Astartes shotgun, combat knife or boltgun to one model adds it to all models. Sniper rifle and Heavy Weapons only add to current model. Thanks for the work.

**Comment by flakpanda** [comment]
@dennywright i do not manage BA, please post an issue for BA scouts.

**Comment by athelred** [comment]
Captain on Bike is costed incorrectly.  Base cost should be 98 not 74.

Thunderfire cannon is missing model costs for thunderfire cannon.  This one is a little strange.  To field a thunderfire cannon you must pay for the following

Techmarine gunner 36
--Servo-Harness
----Flamer 9
----Plasma Cutter 7
----2x Servo Arm 24

Thunderfire Cannon (model) 28
--Thunderfire Cannon (gun) 30

I can't think of a reason for them to have listed the model cost and gun costs separately for the cannon if you were not to pay both.

Captain in Gravis Armor is missing cost for Master Crafted Power sword

**Comment by tekton** [comment]
Roboute seems to be missing his primary category flagging of Lord of War.

**Comment by flakpanda** [comment]
@athelred all should be fixed in commit https://github.com/BSData/wh40k/commit/668f5d2c6da2c4f88fcd99651ea4b734954f22dc

**Comment by flakpanda** [comment]
@tekton Guilliman is working fine for me.
<img width="411" alt="screen shot 2017-06-11 at 2 28 42 am" src="https://user-images.githubusercontent.com/19719565/27009193-c0995bfc-4e4d-11e7-865f-1bdc2557c232.png">

**Comment by CrusherJoe** [comment]
I double-checked and indeed, it's all correct now. I'm not sure how I got that wrong but I guess I did.

**Comment by francoisbeaulieu** [comment]
* Assault squads don't correctly calculate the cost and PL of the jump packs if they are selected first and additional space marines are added afterwards. Works correctly if you deselect and reselect it after adding marines.

* No validation error on tactical squads if you select both special and heavy marines but don't have  a total of 10 marines.

* Inconsistencies: Marneus Calgar has the Antilocus armour option as a radio button, but librarians with terminator armour are a separate unit. Chief Librarian Tigurius is missing the psychic power selections that the standard libbies have.

**Comment by flakpanda** [comment]
@francoisbeaulieu 

- The points no updating for jump packs is a BS bug. I cannot control that. 
- Fixed
- Marneus is that way because he is a unique model.
- Added powers list to Tigurius

**Comment by francoisbeaulieu** [comment]
@flakpanda, is Jon aware that the bug is still present in the latest alpha for Battlescribe Desktop 2.01.01.88?

**Comment by alphalas** [comment]
Yup - It's been in the last 5 builds and we keep telling him about it

**Comment by alphalas** [comment]
See also https://github.com/BSData/horus-heresy/issues/989

**Comment by Jasqes** [comment]
The predator autocannon profile is wrong. Now Predator autocannon has it's own profile, it's Heavy 2d3, Damage 3 (instead of Heavy 2 Damage 2)

**Comment by GitArdnutz** [comment]
[Space Marines.cat.txt](https://github.com/BSData/wh40k/files/1067967/Space.Marines.cat.txt)

Here's a version of the SM file with the following changes (@Flakpanda, I hope you find it useful):

- Assault Squad - Jump Pack now amends Move value on profiles
- Crusader Squad - added along with profiles for Initiate, Neophyte and Sword Brother
- Astartes Shotgun (collective) - added for Crusader Squad Neophytes, so they could be grouped conveniently
- Lightning Claws (pair) (13pts) - option added to all models who had the ability to select 2 LC via Melee Weapons or Sgt Equipment lists but were being forced to pay 9pts for each - along with validation for the selections
- Small number of typos fixed (Jump Pack _Assult_ rule, _Verteran Sergreant_ in a couple of units)

**Comment by Jasqes** [comment]
A small but important typo - Stormtalon gunship - add 1 to hit rolls when shooting at units that CANNOT fly (instead of CAN fly)
Sergeant Telion - typo in Infiltrator rule - deploymen**Y** zone

**Comment by wismeril** [comment]
Whirlwind damage description description not completed 
Row1, Characteristic 1 ....

**Comment by Randobar** [comment]
Company Veterans: Selecting 2 Bolt Pistols for one Veteran sets it to 2 for all of them.

Honor Guard, impossible to add more to the 2 default.

**Comment by Randobar** [comment]
Scouts with heavy weapons should still carry a Bolt Pistol

**Comment by flakpanda** [comment]
@Randobar Company Vets and Scouts fixed.
But what do you mean about Honor Guard?

**Comment by Randobar** [comment]
Nevermind. Honor Guard are in fact limited to 2 per Squad now.
Guess i need another one to field them all if i have to split of the Champion.

**Comment by ghost** [comment]
Had a quick look at Black Templars-specific units. Didn't add up all the points costs however unless specifically mentioned below.

# Wargear
## Chainsword
- [useability] really need a [collective] version in the GST

## Rosarius
- [useability] would be nice if the Rosarius modified the parent's profile to add "/4++" to the Save field

## Iron Halo
- [useability] would be nice if the Iron Halo modified the parent's profile to add "/4++" to the Save field

## Combi-weapons
- [useability] would be nice if the weapon profiles somehow reflected the rule "When attacking with this weapon, choose one or both of the profiles... If you choose both, subtract 1 from all hit rolls for this weapon."

## Armour of Faith
- [useability] would be nice if the Armour of Faith modified The Emperor's Champion's profile to add "/4++" to the Save field

## Crux Terminatus
- [useability] would be nice if the Crux Terminatus modified the parent's profile to add "/5++" to the Save field

# Chaplain Grimaldus
- [points error] as a named character, his Plasma Pistol is included in his cost of 120pts - in the CAT he costs 127
- [typo] Litanies of Hate rule - "CH**PA**TER"
- [typo] Unmatched Zeal rule - "imme**r**diately"
- [missing rule] Spiritual Leader - as for other Chaplains

# Company Veterans
- [typo] "Ve**r**teran Se**r**greant"

# Company Veterans on Bikes
- [typo] "Ve**r**teran Se**r**greant"

# Crusader Squad
- [missing option] "any Initiate may replace his boltgun with a chainsword" - can't select this in the CAT - ideally should be able to select number of "Initiates w/ Boltgun" (default) and "Initiates w/ Chainsword" via spinners
- [useability] Crusader Squad - Initiate w/ Heavy Weapon - should only be able to select 1 power weapon (validates correctly but it would be better to have checkboxes for the power weapons instead of a spinner that allows >1 to be taken)
- [useability] Neophytes - since Neophytes only have 1 variable with only 3 options, it would be nice if Neophytes could be added via a spinner for each option rather than added and amended individually (not sure if this complies with the 40k style guidelines though)

# Emperor's Champion
- [typo] unit name is "**The** Emperor's Champion"
- [typo] Sigismund's Honour rule - "Attack**s**", "...of an**d** enemy..."


Very elegant solution on the paired Lightning Claws. I scratched my head for ages trying to get that approach to work and never managed it, but I suppose I was looking exclusively within the CAT...

**Comment by ghost** [comment]
# Wargear

## Plasma pistol (supercharge)
- [typo] "the bea**t**er is slain"

**Comment by francoisbeaulieu** [comment]
Librarius psychic powers descriptions:

Veil of time: Missing "Librarius" power category.
Veil of time typos: "Advance" capitalized while "charge" is not. "whse" rather than whose.
Might of heroes typos: "ass" rather than add. "TOughness"
Null zone typos: "halv" rather than halve.

**Comment by francoisbeaulieu** [comment]
Has any thought been given as to how to select a unit's chapter, and how to display it in the faction keywords in the roster for those units which have a specific chapter? This has impacts on certain rules and is expected to have impacts on command points when the codexes come out.

**Comment by flakpanda** [comment]
All non-usability issues have been taken care of and uploaded. Closing this thread per @amis92's request.
