### ISSUE TITLE
8th Edition Space Wolves corrections

### ISSUE THREAD

**Issue by CrusherJoe** [BSData/wh40k-7th-edition#3811]
**File/Catalogue:** Space Wolves v6 (8th edition)

**BattleScribe version:** 2.01

**Platform:** Mac

**Dropbox:** Not active? I don't see it, but I really don't use it on my Mac

**Description:** Just tried making a test list, here are the issues I found:
Storm Shields are listed as 5 points for Thunderwolf Cavalry, they are 15 points (page 217 Index Imperium 1)
Tempest Hammer for Iron Priest on Thunderwolf is listed as (No cost), they are 30 points (page 217 Index Imperium 1)
Wolf Guard Pack Leader for Blood Claws, the D stat given for a Lightning Claw is 31, it's just 1 (page 209 Index Imperium 1)

If I find more I will report them.

**Comment by Gnofry** [comment]
Grey Hunters aren't triggering properly, specifically the special weapons. The "set hidden if 1 selection" simply throws an error whenever you try to select 1 special weapon. 

I suggest that the weapons all be made collective and have a simple max restriction based on size. The 7th edition datafile will show how to do this.

I would also suggest some cleaning of the submenus for end user QOL. For instance, the Lone Wolf can replace his Chainsword with a melee weapon, and within the Melee weapon list is another Chainsword. Simply copy and paste the weapon list into his entry so that the whole thing is based around radial buttons and one menu, as opposed to checkboxes and submenus which are quite cumbersome on mobile and desktop.

**Comment by Ragnar69** [comment]
Frost Claws on Wulfen are costed at 0 points, correct is 15

Grey Hunters should be allowed to have 2 special weapons when the unit has 10 models (including WG pack leader)

Chain Swords on Grey Hunters don't work at all. The field seems to be connected to all GH units and also seems to affect the number of GHs in the unit

WG pack leaders on Grey Hunters are costed 13 points, shouldn't they cost 14?

(ven.) Dreadnought can't take stormbolter or hv. flamer with Great Wolf Claw
