### ISSUE TITLE
Dark angels sergeant option

### ISSUE THREAD

**Issue by georidio** [BSData/wh40k-7th-edition#388]
when selecting weapons for a sergeant it should be possible to replace each weapon with items from the melee special weapons list rather than just one....is allowing a pair of lightening claws to be purchased by sacrificing the ranged weapons options. I would expect that this should be the case for any sergeant from any squad but it only really applies to tactical, vet and assault sergeants.

**Comment by Thairne** [comment]
There was some discussion about this on the DakkaForums... Lemme take a look and verify if this was considered allowed, since I don't remember anymore ;)

**Comment by georidio** [comment]
Sweet cheers man, had a word with my local gw manager and he reckons it's a bit ambiguous but that you should be able to have 2 melee if you forego your guns.....based on how it's worded in the wargear section anyway.

**Comment by Thairne** [comment]
Well, there's the thing - some people go this route:

Replace Bolt Pistol for Chain Sword
Replace Chain Sword for melee weapon
Replace both for two melee weapons.. 

So yes, you could equip 2 melee weapons with this. However, the wording IS ambiguous since it states
"A model can replace one weapon with the following:"
There's a discussion about basically the same wording with relics here
http://www.dakkadakka.com/dakkaforum/posts/list/616758.page

Some claim ONE Weapon is exactly that - ONE weapon. If you exchange two weapons, you didn't exchange ONE weapon, but TWO weapons and is therefore invalid.
Company Veterans however e.g. are allowed to take a PAIR of Lightning Claws. So I lean to agree with "only one weapon" since here is a specific exception.

So, as I read it, you'd be only able to get one LC on Sergeants of any kind.

**Comment by georidio** [comment]
I can see the logic however the gw guy I spoke to agrees with me that you can replace one weapon with one weapon....ie one bolt pistol with one claw & one chainsword with one claw.....giving you a pair.

**Comment by georidio** [comment]
Sorry meant to add to that last message that the wording in the wargear list is 'replace one weapon with one of the following' which implies no limit other than how many weapons you get base....not what they are classed as.

**Comment by Thairne** [comment]
I know, and both interpretations are perfectly acceptable.
I even found a threat that handles this exact very question:
http://www.dakkadakka.com/dakkaforum/posts/list/583437.page#6608882

It's funny, C:SM is worded differently (as said in the thread:)
"The way it's worded in this is the exact way it's worded for the relics in both DA books and C:SM books. However, the C:SM book specifies the sarg can replace his bolter with a chainsword, then "a model can replace his bolt pistol and/or melee weapon with one of the following:". This allows the C:SM sarg to go LC/PF, but not the DA one (using the reading of one relic per model). "
With the lack of a FAQ we can only guess this is the intended way since DA came out before SM. Still, RAW it is not possible I think.

And GW Employees are not any more official than the rnd guy you ask on the street. You can play it like that in your local meta, other places might disagree however. I'd suggest you add an option to your Sergeant that allows this, as I can't include this in the general release for everyone without doubt...

**Comment by georidio** [comment]
I can understand not wanting a release that isn't part of a general consensus. Thing is though the threads in question here look to be referring to relics which have a limited quantity in the universe as opposed to specifcly manufactured cc weaponry....and while the main point of 'semantics' is still valid the context is slightly different and from what I can tell has been triggered by people piling all the gear on one guy, 'ie being douchbags' it just makes send to me that if a sgt is taking lightening claws he'd take a pair but the only way to get around the idea of him trying to fire a gun with claws on is to make him have to discard one weapon for one claw and another weapon for another claw.,....also ( trying not to be a douche myself here but possibly failing) in a previous iteration of the bsi the option was there allowing the sgt to have the claws....it's only been changed recently hence me noticing, did it get changed due to popular demand or was an individual's choice?

**Comment by georidio** [comment]
Just as a thought I am not a coder and while I can get the feral gist of the xml I'm not 100% on how I would change it locally for data file and how I would then get my iPhone to recognise the local file.....any advice is appreciated on that score.

**Comment by georidio** [comment]
Not that the advice isn't appreciated on the rest of the thread....I'm just making this worse aren't i....I'll just shut up now :)

**Comment by Thairne** [comment]
It's all fine, don't worry ;)
While relics are, fluffwise, more rare than simple weapons this has no bearing whatsoever on the rules.
The disappearance of the option is most likely my doing: I redid the entire structure of the Dark Angel files to be more easy to maintain. While doing that I also added quite some constraints, modifiers and some fixes like this one.

I guess, while basically we agree to disagree, I'll bow to the majority vote. How do others see this?

**Comment by senpai514** [comment]
One is one. As the codex reads sgt's can only get one melee weapon.

**Comment by MasterSlowPoke** [comment]
It should be better to allow Battlescribe users to get two melee weapons, as it's better to be permit illegal lists over restricting legal lists. In groups where they allow it, you want to let people build their lists.

**Comment by georidio** [comment]
First up thanks for the input all, I admit I had no idea this was such a can of worms to open up :) looks it's a fairly even split on how to approach this (although locally to me people seem to think like I do but we can see how people read it the other way too) I look forward to seeing how thing end up after more than 4 opinions land. :)

**Comment by Thairne** [comment]
So, without further opinions the votes are 2:1 against the change (me included). I'd rather have the restrictive way for those that do not do rules lawyering and may get in trouble otherwise. Imagine showing up for a tourney and the guy you just beat claims your list invalid...

**Comment by Thairne** [comment]
Nevermind, had a better idea ;)
