### ISSUE TITLE
Adeptus Ministorum bugs

### ISSUE THREAD

**Issue by Toreador13** [BSData/wh40k-7th-edition#3910]
- [x] Cannonness profile is still 7th edition profile. 
- [x]  Uriah Jacobus no profile. 
- [x]  Celestian Superior profile is still 7th edition.
- [x] Laud Hailer has bolding in code. <b>ADEPTA SORORITAS</b>
- [x] Ministorum Priest no profile.  
- [x] Seraphim Superior has no weapon  options 
- [x] Battle Sister squad bolt pistol needs to be collective 
- [x] Dominion Squad Dominion Bolt pistol needs to be collective
- [x] Seraphim Squad Seraphim Bolt pistol needs to be collective. 
- [x] Retributor squad Retributor Bolt pistol needs to be collective

**Comment by Toreador13** [comment]
Is anyone working on this file actively? I can make these changes and deploy tonight.

**Comment by CloverFox** [comment]
fixed in 53f678dde4dcb04d59f849d00da787a2dcf8cbc9 (v20): (note these were already reported under  #3854)
Uriah Jacobus no profile.
Ministorum Priest no profile
 Seraphim Superior has no weapon options

fixed in 21221ff7faa4a5ac717dd8cb7e151ef1deb2e99a (v21)
 Battle Sister squad bolt pistol needs to be collective
 Dominion Squad Dominion Bolt pistol needs to be collective
 Seraphim Squad Seraphim Bolt pistol needs to be collective.
 Retributor squad Retributor Bolt pistol needs to be collective

**Comment by Toreador13** [comment]
I thought there was an open thread I had posted in, but couldn't find it. It was closed. I think that leaves only three things on this list.

**Comment by CloverFox** [comment]
fixed in 52cb5c211a5efb58369ce16e5b96dfb62b13f4e7 (v22)
 Cannonness profile is still 7th edition profile.
 Celestian Superior profile is still 7th edition.
 Laud Hailer has bolding in code. ADEPTA SORORITAS
