### ISSUE TITLE
Codex: Astra Militarium => A few formatting issues.

### ISSUE THREAD

**Issue by Kangodo** [BSData/wh40k-7th-edition#395]
**1. Yarrick is "free" in the entry-list.**
Why do we have him for free and then a modifier for his points?
I guess it's because of a formation, but can't we put the modifier in the formation so a 'regular' list sees him correctly?

**2. Militarum Tempestus Platoon.**
They have a minimum of 4 Scions and then another minimum of 1 scion.
The result is that it shows the platoon as 82 points, but goes down to 70 when you actually add them.
Solution is really simple: Put the minimum of the sub-entry at 0.
But you probably had a good reason to do it like this, so I am not so happy on changing it without asking.
Is it possible to change this?

**Comment by ghost** [comment]
There's no sensible reason for Yarrick to be displayed like that. He comes with the 'Fortress of Arrogance', so I should've just deducted his points from that. It was probably down to the order I built the catalogue? Fixed now to make it so.

As for the Tempestus Platoon; this is a relatively new issue to Battlescribe. The left-hand tree never used to include the points of items in entry groups, not even the default selection, meaning the values displayed were usually all over the place anyway. You have to have 1 regular Scion, to make up the group of 4, which is why the minimum was set, but it's redundant, like you say, and I've changed it now. _That'll probably affect a lot of other units..._
