### ISSUE TITLE
Separating Horus Heresy

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-7th-edition#40]
So, what do everybody think?

I have no real insight into HH. Is it even possible? How hard are it's dependencies on 40k?

Are any catalogues besides those specifically HHed used in roster making for 30k?

**Comment by Toreador13** [comment]
Not exactly sure why it would be split out. But I could see it being split just to make it easier on users. I didn't look at the other two books, but the first is setup a lot like a typical 40K army. 
![aodfoc](https://cloud.githubusercontent.com/assets/6875311/2834850/352480da-cfe1-11e3-935a-c0043d5dbe00.jpg) The biggest issue that I can see is that if it becomes easier to make a cat file for each legion, plus Mechanicus and whatever other forces they end up with could get messy and confusing with the normal files. The first book does not allow any allies to other codexes other than guard. So no xenos, or anything else. But all the stat lines and everything else should be the same. So I think the only real reason would be simpler to keep it separate. The gst file would be pretty much the same.

**Comment by Sandy756X** [comment]
I just commented on this in the refresh issue! Here is what I said:

"I was initially against separating Horus Heresy from the regular gst, but the more I think about it my only hesitation is future updates/version changes. I don't want it to get left behind as updates come along. Separating them would mean that somebody would have to make any changes/updates twice, since HH still uses the core 40k rulebook. If that is not a problem, I might actually be for it."

There are several extra force orgs in the later books.  They are in the Refresh gst if you want to look.  I have already created the Mechanicum and am finishing up the Legions .cat and, I will say this loud for everybody: @Jonskichov without the ability to hide/show/etc entries I will indeed have to make a separate .cat for EACH legion.  Now, when another book comes along and adds a unit that is available to everybody, I will have to add it to every single legion .cat (that's 19 total folks, including one for generic/unaffiliated lists).

**Comment by Sandy756X** [comment]
@amis92 from the other issue:  I have the 3rd book and the army lists.  (Managed to snag the collectors edition).  That's what I'm basing this off of.  

Second issue that would need to be addressed: Allies.  Allies would need to be copied over and manually transferred every time they were updated for the main gst.  Ideally once the Imperial Army is created in the next trilogy that will be irrelevant but until then...

**Comment by amis92** [comment]
Well yes, as @Millicant has uploaded the refreshed gst, I saw a list of few HH force types. The only reason for me to suggest split is to throw these 4/5 force types out.

And really, it's 30k not 40k anyway, right? ;D
It's not really important, as as I guessed categories boil down to being the same, so only changing gst id would be enough here and there, and providing the updated IG, as I understand.

I think if we do this, we do this at once with updating 40k gst. So do we agree to do this? To split HH from 40k?

**Comment by Toreador13** [comment]
We are now all piling on @Jonskichov, but yeah the whole hiding bit has come up in the past.Would be great for Forgeworld, and if you have ever looked at the Bolt Action files I have had to make 15 cat files just to display Germany's forces during ww2. I have to do this for each nation, and when I find a bug or update them due to a FAQ, I have to go through each one and check it. It is a very long process each time to make the files, and try and keep them updated.

**Comment by Sandy756X** [comment]
@amis92 Yes I think it would be as simple as turning my "refresh" gst into the "Horus Heresy" gst.  

As far as updating, only those .cats that are available to HH would need to be manually added.  This SHOULD be as simple as taking a copy of the updated .cat and manually changing the gst reference id to the 30k id. However, it required that anybody who updates the file does this EVERY TIME there is a change.  Again, eventually it shouldn't matter as it will be all self-contained (supposedly) but for now, I just want to be clear on what is required.

**Comment by Sandy756X** [comment]
Unless anyone objects, I'm going to move forward on this.  

I will: 
- Close 35, and include them in this separation
- Rename the "new-gst" branch as the "horus heresy" branch and continue my work there, adding ONLY horus heresy force orgs and catalogues. 
- Add it to the main once it's finished, eliminating any HH force orgs or catalogues from the master 40k gst.  
- Include anticipated refreshes, specifically profile types.  I will then include any other refresh tasks that we decide upon once 7th ed arrives.  

Sound good to everybody?

**Comment by amis92** [comment]
Don't we want to create separate repository? Having, for example, two Astra Militarum catalogues differing only by gst id in 40k repo may not be the best idea.

I can create hh30k repository, or just horus-heresy. And until there are no releases, it won't show up on battlescribedata.appspot. I think at least. SO we keep it in 40k or do in new one?

**Comment by Sandy756X** [comment]
I had planned to keep it "in the family" of 40k as it were, since it is the same game (generically) even if it is unique.  

As far as the duplication of catalogues, that is a temporary situation.  Down the road the Imperial Army will be released and eliminate the need for double Guard .cats.  Even then, I'm inclined to say that the number of people allying in Guard are rare, so they might be better off making two rosters, one with their primary HH force, and a second (in the primary gst) of their allied IG/AM.  

That said, I'm planning on skipping the branch and adding them to the master once they are cleaned up.

**Comment by Sandy756X** [comment]
Hey @Toreador13 any word from @Jonskichov on whether or not hiding/showing entries is planned?  I'm hesitating how to finalize my legion .cat.  Should I leave them all in one file and hope for hide/show to come along, or give up hope and separate them all out for cleanliness sake?

**Comment by Jonskichov** [comment]
@Toreador13 @amis92 @Millicant

Hi all - I return from the wilderness. Well, I got caught up doing this: http://steamcommunity.com/profiles/76561197961190428/myworkshopfiles/?appid=107410 and wasn't paying much attention to things :P

Re. Hiding stuff, the next release will not show items where the min/max is 0, or where the user is unable to make a change (e.g. min/max both 1). I can also add a "hidden" flag, just like rules profiles if that's useful. I bow to you guys' requirements ;)

Re. Splitting out 30k - I'm personally all for it. In cases where wh40k codices are usable under 30k, then that's going to be a bit annoying to keep things in sync (at least if there are lots of them) - making changes in both repos... That said, it should be just a case of doing the work in the wh40k repo, then copying changed files accross into the 30k repo and changing the gst ID. Not _too_ bad.

Also, if 30k's force orgs are different enough (or are going to be), then a separate gst is probably needed. gsts don't change much though so even keeping the 40k and 30k ones in line shouldn't be much effort. On the other hand, if the gsts remain the same across 30k and 40k, then there's no problem having the same gst with the same id in both repos. It just means the 30k and 40k data will live in the same folder when BattleScribe downloads them. It will keep whichever gst has the higher revision number.

Finally, I think a separate 30k repo would be great. This helps users (they only download what they need and don't get loads of extra cats they don't want) and it helps us (less files being downloaded saves us bandwidth).

(P.S. Welcome aboard Millicant, glad to see you signed up!)

**Comment by Jonskichov** [comment]
Oh and also, Will it not be better to have separate HH cat files for each legion? Better to have multiple small cats then one massive one. Or are the legions similar enough that this isn't needed? (I don't know the HH lists at all...)

**Comment by Sandy756X** [comment]
Hey Jon!  Thanks for the welcome aboard, I'm really excited to be contributing.  :)

A hidden flag would be AWESOME as well as the ability to use a modifier to change it.  Thank you so much for including that feature, it will add a lot of versatility to catalogue creation!

As far as the HH stuff goes - I have finished the HH gst, along with the first three books of Mechanicum lists, and the generic Legion list.  I would be super excited if we made a separate repository - I can upload it all today!  With the addition of hidden entries, I will continue to make all the legions available in a single catalogue, appearing as they should from the book.

And yes, the legions are best represented via one catalogue, in my humble opinion.  They share 90% of their entries and have a few special units, HQs, and "rites of war" which are unique for each legion.  The Rites of War and the selection of a unique Legion are the main reason the hide/show will be so valuable, since instead of tons of illegal options, I can make it appear as it should!  

Lastly, once I new repository is created, I will upload the new gst and catalogues, which can close out this issue as well as #35.

**Comment by Jonskichov** [comment]
Haha @Millicant you finally broke me :P

To be fair, my main reason to be hesitant to do hidden items was bugs (on my end). If is screw things up, users might not see the options they expect to. But hey, I have the time and I'll put out a beta. So should be cool :)

Re. splitting up catalogues, you're the boss :) I just want to say that bigger catalogues means longer loading times, so please consider this when making your decision.

**Comment by amis92** [comment]
Hiya there. As I see we agree on the need to separate 30 and 40k, I've created repository for horus heresy: https://github.com/BSData/horus-heresy .

That said, I'm not sure that was the intent. Maybe we wanted to keep all this in wh40k repo, just create new id for gst. But I think that as not many % of players use the 30k system, we should separate it into another repo. So, here we have it. Now @Millicant , we wait for your files! :)

**Comment by amis92** [comment]
@Millicant do you think we can safely remove the HH file from this (wh40k) repo tomorrow when 7th ed hits? Or shall we leave it for some time still?
