### ISSUE TITLE
ENHANCEMENTS repository update

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#456]
I see guys that many reported bugs seems to be caused by older versions of the files in the data folders.  Could it be possible,  when clicking the Update button that it would simply erase the older files first before updating in order to prevent this?  I know it would make updates slower but wouldn't it be better after all?

**Comment by Thairne** [comment]
For the desktop version where you basically can assume a connection that can handle the load I'd think this should be possible. Mobile on the other hand...
Are you sure however that, even after updating, the files are still the old version? In this case I'd rather presume that it's a bug in BS itself. Anyway, this is nothing that we data authors could fix since that's a feature of Battlescribe.

**Comment by amis92** [comment]
Unfortunately @Thairne is correct, @Viper666 . Things like that are best placed on BScribe's UserVoice: http://battlescribe.uservoice.com
