### ISSUE TITLE
Dark Angels Melta Bombs

### ISSUE THREAD

**Issue by jfrey89** [BSData/wh40k-7th-edition#459]
Unfortunately they still aren't showing up in the version currently hosted on appspot despite showing that the issue was fixed here.

**Comment by amis92** [comment]
@jfrey89 Please do not open second issue for the same topic. A quick search for "melta bombs" would have given you the correct issue, #451 . Closed issues can be re-opened and that would be more appropriate. As **Thairne** said there, it'll be fixed with a new release, and since then we haven't done it yet. I'm doing it right now, but next time please, be a little more patient. :)

**Comment by jfrey89** [comment]
Apologies! I wasn't aware that you could reopen previously closed issues.

Thanks!
