### ISSUE TITLE
CSM and CD: Be'lakor

### ISSUE THREAD

**Issue by Blastershoot** [BSData/wh40k-7th-edition#479]
I'm not able to add Be'Lakor as a HQ for the Chaos Space Marine, but I see that you can add him as HQ for Chaos Daemons.

Is my fault?

If yes, can you help me please?

If not, can you update the CSM whit Be'lakor?

Tnaks a lot for you hard work.

**Comment by NebSeele** [comment]
A bit of both here, it's not documented well (mostly as it's the first time it's come up) here so it's my part but there is some user interaction that can be done to fix it. 

I had put a tag for "Show Dataslates" in the Non-Codex options entry at the top (hiding the non formation dataslate options off the bat), partly to expand on the option as opposed to simply having a blank and show FW tab. 

I had also done it as to have it so that the CSM codex would essentially be Codex-only for beginners to the file/those who go by codex only, and all the extra options would then be enabled as needed by meta/as the player felt more confident/the player looking for new options.

If you were to "show dataslates" in the "Non-codex options" above the HQ selections, it would show Be'lakor and Cypher. The option to show Forgeworld is also there as well.

Edit: Third reason I put the tabs in is to follow suite with the SM file, to which I try to follow standards wise (the lack of things like chapter tactics and the insane amounts of options that plagued the layout of the catalogue that prompted the hidden tags notwithstanding) and the fact that chaos has force org swapping based on certain options (which are themselves hidden, really made troops a mess to work with). 

An example of what the catalogue used to be like is still around though (for now) in The Crimson Slaughter catalogue. 

In any case, I've left the issue open for feedback on the dataslates option, leaving only Forgeworld to be bound to the hide tags (pandorax is not yet implemented, working on Black Legion and Crimson Slaughter, so the feedback would ultimately determine how those files are handled)

**Comment by Blastershoot** [comment]
Find it. Thank you.
I have a good knowledge of the CSM and CD, but i've never noticed that "No Force Org Slot" option at the top.
I would also thank you for the great job you are doing on these datafile. I'm using it a lot since i found "Battlescribe" and the datafile on the appspot.
If you think useful, i can help you a bit...evenf if I'm not "so good" in eglish.
