### ISSUE TITLE
Grey Knight Relics:

### ISSUE THREAD

**Issue by Xabre1342** [BSData/wh40k-7th-edition#484]
Is there a particular reason why Grey Knight Leaders can only choose a single Relic of Titan?  in other words: Can they be check boxes, not Radio Buttons?

**Comment by new-neon** [comment]
One Leader may take only one Relic becouse in Wargear List say next:
"Relics of Titan
Only one of each Relic of Titan may be taken per army.
A model can take one of the following:"
Key words : "A model can take one of the following:"

**Comment by amis92** [comment]
I'm starting to think people really don't read codexes anymore. And feeling guilty because we enable them to do so by creating so complete catalogues. :(

**Comment by Xabre1342** [comment]
Your compassion for people who misread a codex is impressive.  You must be very proud.

In the codex, the relics appear in two places.  The rules for 'one per character' only show up in the wargear entry, and not in the descriptions of the relics themselves, where it simply says 'one of each per army'.

**Comment by amis92** [comment]
@Xabre1342 
That might've sounded mean, I'm sorry for that. Anyone can misread, that's true.

My opinion still stands, questions like that are more appropriate on forums, such as dakkadakka. I do like how much attention we got in half the year of activity, and I do value the feedback. However even here, simple search for that same term gives you an answer. https://github.com/BSData/wh40k/issues?q=grey+knights+relics

Using such features is important for internet community, because it helps to avoid redundancy of question/answer pairs.

Finally, my post wasn't directed at you and was by no means offensive. It was a general disgust for how many instances of this questions I've seen since Codex came out. On the other hand, you directly answered to me, and 've done that with fair amount of sarcasm, which might actually be offensive. Try to avoid that in future.

**Comment by Kangodo** [comment]
I'm sure it wasn't that serious ;) but we got this question a dozen times.
It makes me wish we had some way of communicating this in a better way, which is one of the reasons I started the BS-data thread on Dakkadakka.

**Comment by Xabre1342** [comment]
In Hitchhiker's Guide to the Galaxy, they put it best: 'Of course you knew we were going to blow up the Earth, we posted it on Alpha Centauri ten years ago, all you had to do was go and read the notice!'

in other words: if you don't know to look on DakkaDakka, it's hard to find information there.  My very first post 10 minutes after making my account was about the relics, after checking the eBook and only seeing the part for the relic descriptions.  I didn't even know this place existed until I tried reporting the bug about the relics.
