### ISSUE TITLE
Plague hulk missing from Chaos Demons and CSM

### ISSUE THREAD

**Issue by althornin** [BSData/wh40k-7th-edition#491]
The blight drone has been added, but not the plague hulk

**Comment by NebSeele** [comment]
Might I ask what  Version Of battles one and the catalogue numbers are? I just checked a non Dropbox linked Device and its on the csm one at the very least.

**Comment by althornin** [comment]
Hrm. Is there a general problem with Dropbox linked devices? 

Because on my phone and desktop, v90 of CSM codex allows neither...

**Comment by althornin** [comment]
V30 of the demons codex allows the blight drone, but not the plague hulk

**Comment by NebSeele** [comment]
I refer to the GitHub as the Dropbox (whether that's true or not), and as my phone is not connected to the GitHub (I actually installed bs onto it to check this issue and it came up as ver 90 and 30).

 it is strange that it cannot find the plague hulk especially since I have not deleted it from the csm file and have largely left the daemons file alone. 
Csm does need the show forge world tab selected (non-codex options) to show fw so please check to see if that's the issue, though checking daemons has the same bug for me (on phone).

I will have a proper look into it once I can get back to my pc as I am not able to do so here.

**Comment by NebSeele** [comment]
CSM still had the plague hulk, the Daemons strangely did not. I have re-added the hulk into the Daemon file and it will be out soon.

**Comment by althornin** [comment]
Thanks - looks good :)
