### ISSUE TITLE
Eldar: 2 CAD & FW options

### ISSUE THREAD

**Issue by Xabre1342** [BSData/wh40k-7th-edition#495]
Tried creating a 2 CAD force, and using the 'show FW' army roster option.  If you select it for _both CADs_ (for instance, you want FW Fast Attack slots in both lists), then the toggle seems to work against each other.  Easy enough to fix if you only put them in one CAD, but seems like the code is working against itself.  regardless of which force org you select, you can only use the 'Show FW' for one CAD.

**Comment by amis92** [comment]
That sounds plausibly true. Unfortunately.

**Comment by Kangodo** [comment]
I found the issue!
"show if Roster has equal to 1 selection of"
That should be either 'if parent force' or 'at least 1'.
Because when you select it twice, the Roster now has 2 selections which is not equal to 1 and thus he hides it.

Maybe I should re-open to other thread to point out things like this.
I also think it's unnecessary to have a defaulted 'hide' in Codices like Eldar, it's only usefull with C:SM.

**Comment by amis92** [comment]
@Kangodo how do we stand here? What's the status?

**Comment by Kangodo** [comment]
I thought an Eldar-player would do that ;) But I looked at it and I think I got them all.
Also tested it and it now works correctly.

I still think an army like Eldar doesn't need to be hidden by default..
