### ISSUE TITLE
[Anon] Bug report: Inquisition

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#517]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** No

**Description:** Under Inquisition codex, the IA2 2E valkerie shows up as 125 points. Should be 100 points.  Bolter sponsons show up as 20 points per model. Should be 10.

**Comment by Kangodo** [comment]
Inquisition-Codex had an update after this.

**Comment by Lynkon** [comment]
The issue being discussed here is not the price of the dedicated transport Valkyries within the Inquisition Codex, but the "Inquisitorial Valkyrie Assault Carrier Squadron" from Imperial Armour 2 Ver. 2. The "Inquisitorial Valkyrie Assault Carrier Squadron" version are 100 points, with 10 point Heavy bolter sponsons.

**Comment by Lynkon** [comment]
What does the "Invalid" tag indicate? That the bug identified is invalid? or that Kangodo's statement is invalid?

**Comment by amis92** [comment]
Invalid - label for issue. So, I tagged whole thread as invalid, meaning - no further action is set to be taken. Because the issue came out as invalid report.

I often set tags because they do provide quick information later when searching for that topic.

Keepi in mind, I don't check each and every issue before tagging it that or another way. I simply try to seed this behaviour of tagging (I feel it's succesfull), so some tags may be incorrectly assigned.

But because the issue isn't closed, someone should investigate it further. I don't have access to those books. And labels can be changed.

**Comment by senpai514** [comment]
Ill get it

Here we will have two different versions of the valkryie with different point costs. @Kangodo the update for Codex Inquisition does not affect the carrier squadron from IA2 2nd ed, that book itself would require a separate errata update

**Comment by Lynkon** [comment]
Does the closed flag mean it was changed or will be changed?

**Comment by Kangodo** [comment]
It was "closed in 30a86d4", that means it was fixed in a commit and thus it has been changed.
Users will notice the change once we upload all the changes.
