### ISSUE TITLE
Bug Report: Chaos Space Marines. 

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#552]
Android platform. most recent build.

Plague Marines - Heavy weapon choices are not displaying the selected weapon profiles inside the box with the other weapons. Example: Plasma Gun selected but weapon profile not shown. It is showing a Combi-Bolter though its not selected. May have the wrong weapon ID coded for the Plasma Gun showing it as Combi-Bolter.

Plague Marine Champion - Does not have a Plague Knife.

Plague Marine Heavy weapon wielders are losing their Plague Knife, blight grenades and krak grenades.

Obliterator - With the Mark of Nurgle is not showing/giving his +1 Toughness. It also would be nice if it displayed his available weapon choices in his stat box as well.

Forgefiend in standard base configuration has TWO Hades Cannons.

Chaos Landraider shows "Chaos Landraider: Capacity" I imagine the intention was to show display capacity and restrictions.

Chaos Rhino - Does not list its transport capacity or list itself at a transport.

Feature request: If you take The Gift of mutation put it on a line by itself and make room or leave space at he end of it to pencil in or write in what you rolled. The suggestion carries over to the Rewards and Champion of Chaos boon rule as well. The extra space is geared to those who print the army list. For the ones who don't print. Give an option to select the the Mutation, champion of chaos or rewards during army creation. When you do the eye symbol to play your army it will show the mutation, boon or reward.

**Comment by NebSeele** [comment]
I'll get onto this sometime today. I actually had most of the changes (that I can do, some I can't alter) to go a couple of days ago, but technical difficulties and no time to finish it off stopped me.

**Comment by NebSeele** [comment]
(TL:DR Warning, long winded explanations)

Turned out I didn't lose as much of the original bugfix as I originally thought, however I had to make a couple of changes to Plague Marines. 

I re-added the Plasma Pistol as an option for special weapons.
I added a "Plague Marine with Special Weapon" option. Modifiers allow for the original plague count to be reduced below 4 for each plague with spec selected.  The bolt pistol will now come with the selection of the special weapons, barring plasma pistol (which then you get the Boltgun).

the second option was because the modifiers to reduce the original model counts failed to work correctly with the current Plague layout. It also created more problems.

Linked Krak Grenades, so Krak profiles now display when selecting plagues.

As for the rest:

Obliterator modifiers: Added for both Nurgle and Slaanesh. There are others that do not modify, so seperate issues should be reported (if you want them, it's not entirely needed after all).

Forgefiend: Renamed the actual entry to say "Two" of the main guns. This is due to an earlier issue with patching up the FW entries, having similar results to the Plague issue above (modifiers spat out errors instead of decrementing the actual options).

Land Raiders: Yeah, each of the Transports now have the "Transport Capacity: (vehicle)" as the profile for Tansport vehicles no longer exists in the game system (and the standard vehicle profile does not denote that kind of information). I cannot take credit for this idea as I only modified it and applied it across all transports, where as the original entry (for the land raider in addition) was there before I joined and started the CSM PoP.

Rhino: Was absent its transport rule, so added it.

as for the Feature requests (which is why I won't close this for a few more days despite the actual bugs fixed):

I left out those kind of tables from the catalogue in order to keep people from using the battlescribe file ONLY when referring to the rules (in addition, many of the rules are paraphrased as well). Their addition would mean that players would be able to use their rosters for the rules instead of actually having the codex.

When I began the Profile Overhaul Project, I intended for the rosters to be quick but resonably detailed and easily accessible references, not a replacement to the rules and codex.

If it felt by other users and contributors, that the Obliterator weapons and the Chaos Boons (and the other tables) are better served inside the roster, I will have no issue adding them as a rule and linking them as needed. You'd probably only get the one entry for the boon though since it doesn't duplicate the entries in the final roster.

Added note: The gift of Mutation is a profile entry. Profile entries don't do spaces, so I can't take the table onto the end of it as it would become an unreadable wall of text.
If the Boon makes it into the catalogue in the end, then it would be a rules entry instead.

**Comment by lacyj3** [comment]
Good work and thanks!

**Comment by Kangodo** [comment]
One question: CSM Raptors seem to have two options for Mark of Chaos.
Is this correct or did you make a mistake there?

**Comment by neconamis** [comment]
NOTE:  There is still problem with not being able to lower the number of default plague marines when they are selected as troop choices (such as with Typhus as HQ).  Works great as Elite choices though.

**Comment by NebSeele** [comment]
Both bugs are fixed and will be up soon (closing this issue).
