### ISSUE TITLE
Chaos Plague Champion weapons

### ISSUE THREAD

**Issue by e400** [BSData/wh40k-7th-edition#581]
Hello,

Currently the Plague Champion only has Blight and Krak grenades as his default wargear, but as I understand the codex, he should also have a boltgun, bolt pistol, and plague knife. He then has the option to take melee/ranged weapons from the wargear list.

Also, "melee" is spelled "meele" for all the weapon type of:
Plague marine plague knives
Plague marine close combat weapons
Lord's power fist
Lord's power axe
Daemon prince's close combat weapon
Terminator power axe
Terminator chain fist
Possibly others, those were the ones I saw.

Many thanks.

![melee](https://cloud.githubusercontent.com/assets/9986098/5224593/e7939e6a-76ce-11e4-89fa-6a54b17317cf.png)
![champion](https://cloud.githubusercontent.com/assets/9986098/5224594/e8583b3a-76ce-11e4-8e53-5e6de7a89c8f.png)

**Comment by NebSeele** [comment]
This was one of the issues I ran into with the last plague marine bugfix, which is why it's currently set up like that.

While the plague champion has those weapons by default, he does not keep them when he gains the special weapons. One of the limitations I found with Battlescribe is that the modifiers will only say that the min/max allowed item is now zero, but doesn't strike them from the list. Meaning that options taken would cause errors to be spat out and break the roster.

The weapon choice is in fact a shared entry (that largely conforms to the rest of the aspiring champion equivalent entries in the codex, hence why it's shared), which is why Plague Knife isn't on it. It also adds to the complexity with the modifiers issue above.

If need be though, I could go back and make individual weapon choice modes for each of them if need be (it's not the first time this problem caused a rewrite of how options are taken, won't be the last) but to me the original weapon choice options was pretty standard for power armour units.

As for the Melee/meele thing, that's a simple spelling error (on my part). I'll have that fixed up when I can.

Edit: extra sentence or two to clarify a bit more.

**Comment by amis92** [comment]
So, um, what now? Are we done here?

**Comment by NebSeele** [comment]
I've not heard back on this one. I don't have much time (or access to a proper machine to do so) between here and the new years either to do changes like this. 

I'll close this, however I'll implement it into the PoP when I resume work on the project in January.
