### ISSUE TITLE
Weapons options for the Astra Militarum Chimera

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k-7th-edition#64]
I'm not used to edit repo files

Could someone edit the Astra Militarum - Codex.cat in order to add the Autocannon and TL heavy bolter Forgeworld weapon options for the Chimera?

Thx!

**Comment by ghost** [comment]
It didn't seem right to give a vehicle some upgrades from one book & some from another (the points for things like camo netting & the dozer blade, as well as the Chimera itself, are different), which is why I haven't added those already.
So I emailed FW about this and other items affected by the new codex - they are producing an FAQ. I'll update the file when that is available.

**Comment by Viper666-Qc** [comment]
Thx for the info!

Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : khambatta notifications@github.com
Date :2014/06/03  04:00  (GMT-05:00)
À : BSData/wh40k wh40k@noreply.github.com
Cc : viper666 jfviper666@hotmail.com
Objet : Re: [wh40k] Weapons options for the Astra Militarum Chimera (#64)

It didn't seem right to give a vehicle some upgrades from one book & some from another (the points for things like camo netting & the dozer blade, as well as the Chimera itself, are different), which is why I haven't added those already.
So I emailed FW about this and other items affected by the new codex - they are producing an FAQ. I'll update the file when that is available.

---
