### ISSUE TITLE
Commissar bug in Astra militarum catalog

### ISSUE THREAD

**Issue by justinhardin** [BSData/wh40k-7th-edition#716]
I'm unable to add a standard commissar to a roster using the Astra militarum catalog/data file. I can add its to...say... An infantry squad but then immediately get a roster validation alert saying I have too many commissars.

Looking at the data file, <code>max in force</code> is set to 0 which I'm guessing is the problem.

Another preference/pedantic issue...after reading the rules, commissars should probably be categorized as 'no force org slot' as they are attached to units during game setup, not at roster creation.

**Comment by senpai514** [comment]
You may include one Commissar for every "Company Command Squad" or 'Platoon Command Squad" 
You need to one of the 2 qualifying units in order to validate the Commissar that you want to take in any of the eligible squads he can be a part of.

**Comment by justinhardin** [comment]
I have a platoon command squad... As a matter of fact I'm trying to add the commissar to the platoon command squad. I'm not sure if screenshots will come through on github but I've included a screenshot in this email.

**Comment by justinhardin** [comment]
![image](https://cloud.githubusercontent.com/assets/3800689/6066178/087ee9e0-ad20-11e4-8cc2-761f07a7f0b1.jpg)

**Comment by senpai514** [comment]
what mobile platform are you using?

**Comment by senpai514** [comment]
ok so I get no error on desktop modifiers work properly. Apple app I get an error.
@amis92 this seems to be something with the apple version of the app.  From what I see it appears that none or very few of the modifiers we input into a catalogue work in Apple versions of Battlescribe.

**Comment by amis92** [comment]
Reported on Twitter, as the Apple update was recently pushed. It may or may not solve those problems though.

**Comment by Jonskichov** [comment]
Is this in the current AM data file?

I'll test on my end. Might just have been a bug in the iOS version (Android was a bit ahead of iOS).

**Comment by justinhardin** [comment]
I just download the latest Desktop (Mac Installer) and I'm no longer
getting the commissar validation error. w00t! so 1.15.06 resolves the issue.
I confirmed that my iPad has 1.15.05 and it still has the commissar
validation issue.

**Comment by Jonskichov** [comment]
So it looks like this issue is still in the release I submitted recently. The Android and desktop versions are running the same code, and don't show the problem though. This leads me to believe there's some issue in the tooling/frameworks on the iOS side of things.

Since this could be a real tough issue to pin down, and I don't want to hold things up, I'm going to let the iOS version carry on through approval for now. If I can find the issue before it's released I'll resubmit with the fix.

Otherwise, since it's not a show-stopper, I'll let the app out with the bug in place if I can't find the problem in time.

**Comment by amis92** [comment]
Outdated.
