### ISSUE TITLE
No Permission to Push Local Changes

### ISSUE THREAD

**Issue by ansacs** [BSData/wh40k-7th-edition#793]
I attempted to add the detachments and Renegades and Heretics army list from IA-Vraks. However when I try to sync my files to the wh40K master I always get the following message;

Sync failed to push local changes
It seems you do not have permission to push your changes to this repository.

**Comment by amis92** [comment]
Well that's because you cannot directly push changes. Use pull request functionality to do so.

So:
1. Copy the files you've modified to some location.
2. `fork` wh40k repo on GitHub website (upper-right)
3. Clone the repo locally using GitHub app.
4. Copy changed files into the newly cloned location.
5. Commit them.
6. Push those changes into your fork.
7. Create pull request (I think you can do that now directly from GitHub for Windows app - but if not, it's on the website too).
Done!

**Comment by cbraatz** [comment]
I had the same problem but in my case, my account was not confirmed. I resolved clicking fork and then I received an email to confirm it and after doing this I could sych correctly.
