### ISSUE TITLE
Chaos Space Marine Codex - Forge World

### ISSUE THREAD

**Issue by mickyster** [BSData/wh40k-7th-edition#807]
There is no option to for forgeworld IA13 outside of the Lords of War in the standard CSM but there is in Crimson Slaughter.

**Comment by NebSeele** [comment]
The expanded options entry has the option to display FW, since the chaos file was starting to get a bit big without the hidden FW entries. In saying that, when I go to do the bug fixes for csm later today, I might change how the extra options work so it's easier for people to use. Since it's recurring enough, the Show [FW] tab can easily afford to be on its own.

**Comment by NebSeele** [comment]
I have split off Force options and show Forgeworld into their own tabs. Should make building a force easier now. Will be uploaded soon.

**Comment by amis92** [comment]
@NebSeele how's status here?

**Comment by NebSeele** [comment]
this one's done. No real need to keep it open and am surprised the commit didn't close it.
