### ISSUE TITLE
Cultists Marks

### ISSUE THREAD

**Issue by TheHiddenBruceLee** [BSData/wh40k-7th-edition#821]
When marking a squad of cultists with Tzeentch(at least haven't tried the others). In the IOS app it charges you 1 point more for the squad than there are members.  So a 1 point mark ends up costing 11 points on ten men.  It is charged immediately on the squad champion for the 2 pots before adding additional cultists.  When lists are saved and shared to desktop versions of battlescribe the cost is corrected.

**Comment by NebSeele** [comment]
Might've been a modifier issue for the Tzeentch one. In any case, the way the marks calculate their costs in the next version will be changed to the "Cultists in Unit" selection instead of the Autogun/Autopistol/Heavy Weapons selection that the current version uses. The Cultist Champion's modifier will remain the same.

Edit: I may have to leave this one open for further testing. While I have checked the modifiers and they all look correct on the Catalogue editor, the Tzeentch entry was one point higher than Slaanesh's entry in the Roster editor during testing. This should not happen and I have no explanation for this.

**Comment by Stribbs** [comment]
#865 
Bug Fixed
