### ISSUE TITLE
[Anon] Bug report: Khorne Daemonkin

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#866]
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Its nice to see that the Deamonkin Khorne is online...but there are too many problems in there...

For the CSM the Speacial Weapons costs 0 Points but Power Fist for the Champ 50?!
Pls rework the Data,i love to use this Programm but with this Problems i have to make a list per Hand...

**Comment by amis92** [comment]
Thank you for your opinion. We cannot however accept such negative feedback. Instead, please come join us and sacrifice the time spent on writing such reviews on fixing the files.

Next time, if you don't want to fix them yourself, simple "the Speacial Weapons costs 0 Points" and "Power Fist for the Champ 50" would suffice.

**Comment by NebSeele** [comment]
Saying to fix the problems really doesn't help to fix them. As it stands I am aware of issues in the Daemonkin codex, a great deal of it is because it's still in the early stages. 

If you can list the bugs in the Daemonkin file (as well as the catalogue version) it would help in fixing the catalogue.

**Comment by NebSeele** [comment]
At this point, I assume most of the bugs from this time period have been resolved. Since nothing else is available information wise, I am going to close it.
