### ISSUE TITLE
Warhammer 40k.gst: Blood Host Detachment

### ISSUE THREAD

**Issue by NebSeele** [BSData/wh40k-7th-edition#871]
As noted in previous bugs, the Blood host detachment is currently not available. Each time I go to add it to the Game system editor, I keep getting the error "Modifier must have parent that exists in the parent force".  I am making sure that everything is correct so I don't know what's causing this (granted I am not that familiar with the Game System Editor).

Is this a common occurence? Have I overlooked something?

**Comment by Kangodo** [comment]
I am not getting this error.
For the Decurion I made a Core, Auxiliary and Command-type.
It would be quite simple to make the Blood Host, so I will create it for you, upload it and inform you if it is done :)

Edit: Weird, every time I try to save I get the same error too.

**Comment by Kangodo** [comment]
Okay, after ten minutes of yelling, screaming, begging and crying I found out that:
Everything works fine until I start to add the modifier.
At that point it tells me that the parent does not exist in the Blood Host Detachment, probably because it has the same unique ID as the Core from the Decurion.

@amis92 Do you have any idea on what to do?

**Comment by amis92** [comment]
#873

Well, I've just copy-pasted contents of Decurion force type in XML. :) I _think_ it might have had to do with the order of Categories you've created. In my case, the battlescribe always saved core _after_ command, and because command referenced not yet present core, error was thrown. Not sure, though.

EDIT: Also, I don't have time to check if it works appropriately, that's why I've made pull request. Test it and merge if all is right.

**Comment by NebSeele** [comment]
The core basis works fine enough, though the min/max's are still the decurion, however the issue of saving is no longer the problem. I'll merge it across and re-adjust the blood host accordingly.

**Comment by cartag** [comment]
Neb, I have a copy of the catalog that I made while waiting for somebody else to make one. Here's the link to it, I'd like to work with you on keeping it updated if you want a second set of eyes looking at things. 

https://dl.dropboxusercontent.com/u/13435935/Repository/Khorne%20Daemonkin.catz
