### ISSUE TITLE
[Anon] SM Clan Raukaan - HQ chapter relic choices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#88]
The Clan Raukaan HQ choices should not be limited to one chapter relic choice. From what I understand the only restriction is the Mindforge staff can only be carried by a librarian and replaces his force weapon .

**Comment by ghost** [comment]
The chapter relics for the supplements work the same way as with the main codex: a character may only have one, and if it is a weapon, he must exchange one of his other weapons for it. We checked this with GW when we made those files.

**Comment by Redryad** [comment]
Except the space marine codex doesn't limit you to one. Some one even checked with the army builder that came with the interactive iBook edition because GW didn't address it. Also the space marine data file doesn't limit it either.

**Comment by Stegadons** [comment]
I think it doesn't limit because each relic is one-in-roster, but until character has something to replace with relic, he can have many relics.
I will check it with codex as soon as I can get to it (it will take a couple of days)

<div>-------- Sākotnējā ziņa --------</div><div>No: Redryad notifications@github.com </div><div>Datums:22.06.2014  09:41  (GMT+02:00) </div><div>Kam: BSData/wh40k wh40k@noreply.github.com </div><div>Tēma: Re: [wh40k] [Anon] Bug report: Space Marines - Supplement - Clan
  Raukaan.catz (#88) </div><div>
</div>Except the space marine codex doesn't limit you to one. Some one even checked with the army builder that came with the interactive iBook edition because GW didn't address it. Also the space marine data file doesn't limit it either.

**Comment by Redryad** [comment]
There's a previous evidence of it to with the crimson slaughter supplement. It gives a character build that uses multiple relics and both csm codex and sm codex use the same wording for their relic sections.

**Comment by ghost** [comment]
I'm not involved with the vanilla Space Marine or CSM data files here, so I can't comment on them. If you want to get those fixed, please raise a new ticket.

**Comment by Redryad** [comment]
No I don't want them fixed, I am using them as reference for why it is not limited to one relic.

**Comment by Redryad** [comment]
I am also referencing the actual codexs not just the data files for why this is wrong.

**Comment by Stegadons** [comment]
I can confirm - any HQ can have one relic per weapon exchanged (usually two - ranged and melee exchange) unless rules on that HQ state "can select **one** item form Chapter Relics list" or something similar.

**Comment by ghost** [comment]
I dunno where you're getting that from, @Stegadons, the SM codex definitely say "may replace **one** weapon with **one** of the following... It doesn't say "and/or", and it doesn't say "any", just one.

**Comment by Stegadons** [comment]
@khambatta Because one weapon exchanged = one relic. Not all weapons for relic, two for one, or any other exchange rates. 
Relics list says one weapon for one relic, character's list still says "may take **items** from [..] Chapter Relics list"

**Comment by Redryad** [comment]
Like I said check the crimson slaughter supplement it actually references how to kit a chaos lord to reproduce one of the named characters from dark vengeance and lists him having multiple relics. The ibook interactive edition of sm codex also comes with an army builder that lets you pick multiple relics.

**Comment by Redryad** [comment]
Also none of the item lists say "any" all of them say "one of the following" except special issue wargear which specifies "one of each of the following".  It also doesn't say and/or because not all models that can have relics have a bolt pistol and/or chainsword, as well as the fact that not all of them exchange weapons. There is more evidence pointing to being able to have more than one then is ponting to not. This applies to all 6th edition codexs as well since they use the same wording.

**Comment by Redryad** [comment]
If they ment for you to only have one they would have said "a model can replace one weapon any one of the following" or specified "a model may only have one item from the chapter relics list" instead they onle specified "only one of each chapter relic may be taken per army"

**Comment by ghost** [comment]
> If they ment for you to only have one they would have said "a model can replace one weapon any one of the following"

They do. Pg 159. The AM codex has "only of each" as you say, but the SM codex goes further.

**Comment by Redryad** [comment]
No they don't I quoted the section you referenced and that was only pointing to not having two of the same relic not restricting the number of different relics they could have.

**Comment by Redryad** [comment]
In fact they both say "only one of each relic/heirloom may be taken per army."  Each means you can have two different ones in the same army, and nothing says they can't be on the same character. Also from what I am reading in the am codex an HQ could have as many as three different heirlooms. And again you have said nothing about the other points I referenced.

**Comment by Kangodo** [comment]
Weapons seem to have a max of 2 now, and no max in roster. So I think I can close this?

Edit: Apologies, was too quick and didn't notice it's for another SM-file ;)

**Comment by Redryad** [comment]
Wait what? Where's that? Besides that's not what I was talking about.
