### ISSUE TITLE
[Anon] SM Codex - missing FW chapter tactics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#89]
When building a detachment from Codex: Space Marines none of the Forge World Chapter Tactics selections are available (i.e. Carcharodons, Mantis Warriors, or Fire Hawks)

**Comment by Kangodo** [comment]
I added the chapters from the FW-pdf.
I did not add chapters that are the same as Ultramarines, like Fire Angels, because I am unsure about the interaction with unique characters that are limited to UM's.
And I grouped them with Adaptes Astartes and Forgeworld, so non-FW players can still find their own chapter easily.
