### ISSUE TITLE
Chaos Daemonkin: Bloodreaper points cost

### ISSUE THREAD

**Issue by Skulltaker** [BSData/wh40k-7th-edition#916]
Bloodreaper (Bloodletter character) upgrade is 5 points, not 15. Sorry if this was posted elsewhere, tried to make sure but didn't see anyone else mention it.

**Comment by NebSeele** [comment]
The Bloodreaper upgrade is actually for the cost of the entire model and actually adjusts the unit count accordingly. Seems a strange idea except that the chaos marine champions work like that (as they can't be not taken) and bloodreaper would have shown up in the entry both ways.

Edit: Just in case, as a future reference. The daemon unit champions being the model+upgrade costs rather than the Codex: Daemons upgrade costs only is intentional.

I personally am not a fan of the Daemon's way as Battlescribe can sometimes be muddy on how the catalogue could/should be read. In saying that it does work for daemons who do have champions that are upgrades. Which of course brings me to the core reason behind the decision.

The chaos marine entries as stated, MUST have the champion, who's champion costs are in the base unit costs and are a buffer. Since they had to stand out for this reason, it would be highly inconsistent if the daemon entries didn't. In the end it's just more keeping the units consistent with each other.
