### ISSUE TITLE
Skitarii Formation 'Battle Maniple'

### ISSUE THREAD

**Issue by darkestvisions** [BSData/wh40k-7th-edition#922]
'Battle Maniple' first adds both Sydonian Dragoons and Ironstrider Ballistarius, where army book shows formation is to choose one or the other. Error is given because both are selected ("Battle Maniple has 1 too many selections from Ironstriders (maximum 1).

However, deselecting one choice gives a new error ("Battle Maniple must have 1 more selections of Ironstrider Ballistarii (minimum 1)"). Adding a second version of the still active choice does not resolve this.

Error occurs on both iPad and Mac Battlescribe, using Skitarii data v6.

**Comment by senpai514** [comment]
@axisofentropy I know what is causing this error for your catalogue after reviewing through your entry system. Message me direct through gitter chat and I can help you and I have a few suggestions / recommendations I would like to offer for your consideration to simplify the Skitarii catalogue.

**Comment by axisofentropy** [comment]
I've corrected the second error but not the first.  This tells the roster user what they need to change (remove one of the two) so maybe this is sufficient.

Correcting the first error is more difficult.  Both the Battle Maniple and Ironstrider Cavaliers formations link to these units, but require minimum 0 and 1 selections respectively.  I've added modifiers changing the minimum selections, but Battlescribe does not honor them when adding a new entry, only for validation.

I could fix this by duplicating the Ballistarii and Dragoons shared entries, but I'm reluctant to do that because duplication is bad, although I was forced to duplicate in this catalog file once before (the Alphas' rifles.)

@senpai514 sure I'd like to hear your ideas. here is fine or send me an email axisofentropy at gmail

**Comment by amis92** [comment]
@axisofentropy / @senpai514 have you communicated? How's status here?

**Comment by pretzalcohuatl** [comment]
Want me to just fix this?

**Comment by amis92** [comment]
Let's wait for some response. Or do you have an idea that does not involve duplication?

**Comment by pretzalcohuatl** [comment]
yeah, i have an idea

**Comment by amis92** [comment]
:) nice. Have you checked it works as expected in roster editor?

**Comment by pretzalcohuatl** [comment]
yes, you start off with the dragoons because they're cheaper, but you can radio button the balistarii instead

**Comment by axisofentropy** [comment]
(that fix involved duplication but that's probably worth it.)

**Comment by pretzalcohuatl** [comment]
yeah, right now duplicating entry groups with min=1 max=1 and default set is the only way to ensure that a shared entry is instantiated
