### ISSUE TITLE
Bug: Daemonkin of Khorne "Chaos Space Marines"

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#928]
Ipad

Bolt Pistols appear on Stat line but the 'Bolters' do not.

**Comment by NebSeele** [comment]
Bolters have to be selected manually using the "Equip Boltguns" in order to account for mixed  equipment options as it's the boltgun that's replaced/complimented with the CCW.

Can't really have them in the base profile as it causes problems otherwise with the unit weapon loadouts. (Codex: Chaos space marine issues from past) It's annoying and problematic, but it's either that or terminator like profiles for the chaos marines over a boltgun/ccw (since the rest of the profiles are collectively shared).

**Comment by NebSeele** [comment]
No real work around this issue that doesn't create much larger problems, so I'm closing. The boltguns can be selected in any number you wish, as well as CCW's and a mix of both (and the profile will update).
