### ISSUE TITLE
Bug: Daemonkin of Khorne 'possessed '

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#944]
iPad 

Possessed have no Champion or option to add one.

**Comment by NebSeele** [comment]
Checked on phone, this is weird as it doesn't show up in the entry itself, but shows when in the general roster list as well as when you view the htm like version of the roster. Only thing I can think of is that it's not showing because there's no additional options to select the app just doesn't show it outside of unit selection and html view.

**Comment by amis92** [comment]
Yeah... BattleScribe doesn't show required, non-modifiable options. Lately someone complained about lack of Shield Generator on Riptide. Same situation - it's there, but doesn't show when editing unit.
