### ISSUE TITLE
Bug: Harlequin

### ISSUE THREAD

**Issue by lacyj3** [BSData/wh40k-7th-edition#996]
in case the closed issue can't be seen.

![solitare](https://cloud.githubusercontent.com/assets/9757195/7594737/bc61aa7a-f8b0-11e4-978c-6f2d8cc36cab.jpg)

**Comment by lacyj3** [comment]
![troupe](https://cloud.githubusercontent.com/assets/9757195/7594743/c1fc7c62-f8b0-11e4-8940-6053591da278.jpg)

**Comment by lacyj3** [comment]
![crescendo](https://cloud.githubusercontent.com/assets/9757195/7594750/c8fc96f0-f8b0-11e4-9256-3552dbad4c87.jpg)

**Comment by lacyj3** [comment]
![enigmas](https://cloud.githubusercontent.com/assets/9757195/7594807/25ae307a-f8b1-11e4-9dee-eaa47ef2cbcf.jpg)

**Comment by Savoronedge** [comment]
At the beginning of the data sheets (before the "Troupe" entry), there is a
chart showing the point cost for the Enigmas. The footnotes for that chart
explain this and other possible concerns.

**Comment by lacyj3** [comment]
Well.....that is classic GW style.  I can see a lot of mistakes in that!

**Comment by senpai514** [comment]
Duplicate to #995 (didn't need to be done)

The biggest thing folks overlook is that relics since the are listed in several places sometimes folks don't look at the right list to find what they need. You have the page as shown which has the stats and descriptions but then there is also the page that has all the upgrade lists, melee weapons, ranged weapons and relics with the points cost for each. That is the page need that should should any restrictions that apply to any of the above option list
